### ISSUE TITLE
Keylime Cloud Node Bundle overwrites /lib/libz.so.1

### ISSUE THREAD

**Issue by geedo0** [keylime/keylime#1]
# Environment
 * OS / version: [Heads](https://github.com/geedo0/heads/commits/server_heads)
 * Processor architecture: x86_64
 * TPM Manufacturer: 
```
 tpm_version
  TPM 1.2 Version Info:
  Chip Version:        1.2.5.81
  Spec Level:          2
  Errata Revision:     3
  TPM Vendor ID:       WEC
  Vendor Specific data: 0000
  TPM Version:         01010000
  Manufacturer Info:   57454300
```
 * Keylime version: [Commit](https://github.com/mit-ll/python-keylime/commit/2e7716c1393116c8a39aa47989a0eecdfd07a3b2)

# Description 
The Keylime Node tarball overwrites libz.so.1 inside the standard Heads distribution. Though named the same, the two are not the same and are incompatible with each other. That is, Heads' libz doesn't work with Keylime and Keylime's libz doesn't work with Heads. In particular, Keylime's version of libz breaks kexec which we depend on for launching our tenant's OS.

The exact path of the offending file:
/lib/libz.so.1
  *Libz is a library for handling zip files

We workaround this issue by hacking in a new hacking in a new LD_LIBRARY_PATH that backs up the old libz. [link](https://github.com/geedo0/python-keylime/tree/bolted)

## Expected behavior vs. actual behavior 
Keylime Node Tarball should either be compatible with the libz distributed with Heads or it should provide it's own that doesn't collide with the one inside Heads.

## Steps to reproduce problem
1. Build the Keylime Node Tarball
1. Extract over Heads' rootfs
1. Try to launch keylime_node or kexec. Only keylime_node will work.

**Comment by jetwhiz** [comment]
We should keep an eye on this going forward and think of a way to create a real workaround.

**Comment by lukehinds** [comment]
keep-alive

**Comment by lukehinds** [comment]
keep
