### ISSUE TITLE
Implement workaround for old tpm2-tools wrong GUID parsing in tpm2_eventlog

### ISSUE THREAD

**Issue by THS-on** [keylime/keylime#1003]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 35
 * Processor architecture: x86
 * TPM Manufacturer: swtpm
 * Keylime version: latest master

# Description 
tpm2_tools fixed their GUID parsing in https://github.com/tpm2-software/tpm2-tools/pull/2745 unfortunately this breaks the example boot policy because it expects the broken GUIDs.

## Expected behavior vs. actual behavior 
The example policy works fine with a refrence state created by `create_mb_refstate`.

Instead the following error is returned:
```
 'Event': {'VariableName': '8be4df61-93ca-11d2-aa0d-00e098032b8c', 'UnicodeNameLength': 10, 'VariableDataLength': 1, 'UnicodeName': 'SecureBoot', 'VariableData': {'Enabled': 'Yes'}}} Event has unexpected ('VariableName', 'UnicodeName') combination ('8be4df61-93ca-11d2-aa0d-00e098032b8c', 'SecureBoot')
``` 

`'8be4df61-93ca-11d2-aa0d-00e098032b8c` is the correctly parsed GUID, but the policy expects the wrongly parsed one `61dfe48b-ca93-d211-aa0d-00e098032b8c`.

## Steps to reproduce problem
1. Update TPM tools to 5.2
2. Generate new refstate with `scripts/create_mb_refstate /sys/kernel/security/tpm0/binary_bios_measurements ref.json`
3. Run policy manually with `python -m keylime.elchecking example ref.json  /sys/kernel/security/tpm0/binary_bios_measurements`
4. See error message from above

@mpeters should we just add the wrong and right GUIDs to the example policy depending on the tpm2-tools version or try to re parse the GUIDs?

**Comment by mpeters** [comment]
> should we just add the wrong and right GUIDs to the example policy depending on the tpm2-tools version or try to re parse the GUIDs?

That's a good question. What is our minimum supported tpm2-tools version?

**Comment by maugustosilva** [comment]
@THS-on what is the downside of simply adding both right and wrong GUIDs on the example policy, with the proper comments?

**Comment by kkaarreell** [comment]
> > That's a good question. What is our minimum supported tpm2-tools version?
> 
> Good question probably that what is currently shipping in RHEL 8.

I would say rather RHEL9. Still, even the v5.0 there doesn't work ATM since it doesn't support the required tpm_eventlog option.

**Comment by THS-on** [comment]
> @THS-on what is the downside of simply adding both right and wrong GUIDs on the example policy, with the proper comments?

@maugustosilva other than having invalid GUIDs to check against nothing really....
Users might get confused if they read the same log using the IBM TSS, but I think this is not an issue in practice.

**Comment by kkaarreell** [comment]
@THS-on This issue can be closed now, correct?

**Comment by THS-on** [comment]
Yes, I think we won't implement the reparsing of the GUIDs to fix them manually.
