### ISSUE TITLE
Use EK certificate not stored in NVRAM

### ISSUE THREAD

**Issue by iammrgenie** [keylime/keylime#1027]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 20.04
 * Processor architecture: x86 (UP xtreme board)
 * TPM Manufacturer: Intel
 * Keylime version: v6.3

# Description I am using a UP xtreme i7 board to test Keylime for a project. While testing an agent, we saw this;

2022-06-13 15:03:24.092 - keylime.tpm - INFO - Flushing old ek handle: 0x81000000
2022-06-13 15:03:24.803 - keylime.tpm - WARNING - No EK certificate found in TPM NVRAM
2022-06-13 15:03:24.803 - keylime.tpm - INFO - Flushing old ak handle: /var/lib/keylime/secure/tmptiagr2ng
2022-06-13 15:03:25.030 - keylime.cloudagent - INFO - Agent UUID: UP-WHL01

Which basically meant that there was no ek certificate present on the board. Went ahead to check with the tpm2_nvreadpublic command and realized the board did not come with the ek certificate. As such, I went ahead and generated an ek key pair and retrieved the ek certificate from the intel provided website. How do I configure keylime to use this certificate?

PS. I tried importing the certificate into the nvram but I keep failing with that also. I tried using the tpm2_nvdefine command to define the index for the key. 

tpm2_nvdefine 0x01c00002 -C o -s 1033 -a ppwrite|writedefine|write_stclear|ppread|ownerread|authread|no_da|written|platformcreate // to define the NVRAM index. This is where I keep getting errors.

Error:

WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:344:Esys_NV_DefineSpace_Finish() Received TPM Error ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x000002c2) ERROR: Failed to define NV area at index 0x1C00002 ERROR: Esys_NV_DefineSpace(0x2C2) - tpm:parameter(2):inconsistent attributes ERROR: Unable to run tpm2_nvdefine

## Steps to reproduce problem
1. 

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
Thank you for reporting this.

You cannot set the `written` attribute and you also cannot set `platformcreate` if you try to define the NV index under the owner hierarchy. Something like this should work:
```
tpm2_nvdefine 0x01c00002 -C p -s 1033 -a "ppwrite|ppread|ownerread|authread|no_da|platformcreate"
```
After that you should be able to use `tpm2_nvwrite` to write the EK certificate to that NV index.

Just out of interest does `tpm2_getekcertificate` work? I think tpm2-tools includes code that downloads the EK certificate from the intel servers if necessary.

**Comment by iammrgenie** [comment]
Hi. Thanks for responding. 

tpm2_getekcertificate works. I used that to get the certificate from the intel servers. However, I am still having some issues defining the NV index.

```
tpm2_nvdefine 0x01c00002 -C p -s 1033 -a "ppwrite|ppread|ownerread|authread|no_da|platformcreate" 
WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:333:Esys_NV_DefineSpace_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x000009a2) 
ERROR: Failed to define NV area at index 0x1C00002
ERROR: Esys_NV_DefineSpace(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Unable to run tpm2_nvdefine
```

This is what I get when I try the command you recommend. I also tried with the `-P keylime` as authentication but same error.

**Comment by iammrgenie** [comment]
It seems I can write to another index but not 0x1c0002. I tried

`tpm2_nvdefine 0x1500015 -C o -s 1033 -a "authwrite|ownerwrite|authread|ownerread|no_da" -P keylime` and it works fine. But when I try `tpm2_nvdefine 0x1c00002 -C o -s 1033 -a "authwrite|ownerwrite|authread|ownerread|no_da" -P keylime`, I get 

`WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:344:Esys_NV_DefineSpace_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x00000082) 
ERROR: Failed to define NV area at index 0x1C00002
ERROR: Esys_NV_DefineSpace(0x82) - tpm:handle(unk):inconsistent attributes
ERROR: Unable to run tpm2_nvdefine
`

**Comment by THS-on** [comment]
What does `tpm2_nvreadpublic` output?

**Comment by iammrgenie** [comment]
Shows the index I successfully created 

tpm2_nvreadpublic
0x1500015:
  name: 000bef2a626e049269ba29be2617603f461118f8430e157f57d1654222ef32e2b006
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|authwrite|ownerread|authread|no_da
    value: 0x6000602
  size: 1033

**Comment by THS-on** [comment]
Ok. Maybe the TPM does not allow you to create that NV handle for whatever reason.

Maybe someone with deeper TPM knowledge can help @kgold2?

**Comment by iammrgenie** [comment]
Seems like it. Is there a way to tell keylime to look in a different NVRAM index for the EK certificate?

**Comment by THS-on** [comment]
> Is there a way to tell keylime to look in a different NVRAM index for the EK certificate?

Currently there is not. The index is specified in the spec, so allowing it to read from another location does not make really sense, but maybe a external path to a PEM file, for systems where the EK certificate is not distributed via the NV of the TPM. @mpeters what do you think?

**Comment by iammrgenie** [comment]
So I went ahead to change the hardcoded values in the tpm_main.py so keylime would use an nv index I specified. However, I noticed the certificate I received from the intel server is not in an accepted format.

`tpm2_getekcertificate -u rsa_ek.pub -o ek_cert.bin https://ekop.intel.com/ekcertservice/`

which returns this bin file

{"pubhash":"LrZoQvxmVFvsHGfXgDICeCaEmTFUZGYCLghBgpSNSBo%3D","certificate":"MIIE6DCCBI2gAwIBAgIUFyFzONq6-rSaEgQBgYcYyzO1gnIwCgYIKoZIzj0EAwIwgaYxCzAJBgNVBAYMAlVTMQswCQYDVQQIDAJDQTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0aW9uMUAwPgYDVQQLDDdUUE0gRUsgaW50ZXJtZWRpYXRlIGZvciBDTkxfRVBJRF9QT1NUX0IxTFBfUFJPRF8yIHBpZDo5MRYwFAYDVQQDDA13d3cuaW50ZWwuY29tMB4XDTE5MDQxNjAwMDAwMFoXDTQ5MTIzMTIzNTk1OVowADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ4ag9w2wEG0Tarnla7fw61JmcTNT4ViOBCkgCTgD7tlIRWF_Dqk5z1x48BBDVXSIUQ3Fmxhcr6SdxmhFkMktI3_OFw9q9wlCTKtqj3WKQjfQUTpl_GojI2U88rMwqL15hHzMAP98ungdBv0731rxmRpBCJX66ZOnaZzKWbN-UG35CFd-kYGLOSPOANRJkli0tLl16jk8MdFAblQx2vPgIdMz3uWqK7pSWbj1lbRQiXTGPgL9Bf9OxNPhH_cOJYFXOr8lerCmLBehjXI-ieQAf1hwWFDrHjsTkkfjH6zgZk5sei49voHUmIs_mldQ4hKg0wRnzHUPEsttgFDSamZl8cCAwEAAaOCAnEwggJtMA8GA1UdEwEB_wQFMAMBAQAwDgYDVR0PAQH_BAQDAgUgMBAGA1UdJQQJMAcGBWeBBQgBMCQGA1UdCQEBAAQaMBgwFgYFZ4EFAhAxDTALDAMyLjACAQACAWcwUAYDVR0RAQH_BEYwRKRCMEAxFjAUBgVngQUCAQwLaWQ6NDk0RTU0NDMxDjAMBgVngQUCAgwDQ05MMRYwFAYFZ4EFAgMMC2lkOjAwMDIwMDAwMB8GA1UdIwQYMBaAFBegBXXQXljjiBIQu5ixBFu0wwY5MGgGA1UdHwRhMF8wXaBboFmGV2h0dHBzOi8vdHJ1c3RlZHNlcnZpY2VzLmludGVsLmNvbS9jb250ZW50L0NSTC9la2NlcnQvQ05MRVBJRFBPU1RCMUxQUFJPRDJfRUtfRGV2aWNlLmNybDCBgAYIKwYBBQUHAQEEdDByMHAGCCsGAQUFBzAChmRodHRwczovL3RydXN0ZWRzZXJ2aWNlcy5pbnRlbC5jb20vY29udGVudC9DUkwvZWtjZXJ0L0NOTEVQSURQT1NUQjFMUFBST0QyX0VLX1BsYXRmb3JtX1B1YmxpY19LZXkuY2VyMIGxBgNVHSAEgakwgaYwgaMGCiqGSIb4TQEFAgEwgZQwWgYIKwYBBQUHAgEWTmh0dHBzOi8vdHJ1c3RlZHNlcnZpY2VzLmludGVsLmNvbS9jb250ZW50L0NSTC9la2NlcnQvRUtjZXJ0UG9saWN5U3RhdGVtZW50LnBkZjA2BggrBgEFBQcCAjAqDChUQ1BBIFRydXN0ZWQgUGxhdGZvcm0gTW9kdWxlIEVuZG9yc2VtZW50MAoGCCqGSM49BAMCA0kAMEYCIQD4Yi2LxeEIVn8vKyuy7Tw0Ry0tgBcv5S4jGPT-zpd-gQIhAI7cWkjgZ5y93iFOYR0QoZu3BP2MyivCfzK74yxxwaLV"}

when I try to use openssl to verify this file. This is what I get

`unable to load certificate
139941582808384:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE`

Any help on this?

**Comment by iammrgenie** [comment]
`tpm2_getcap properties-fixed`
TPM2_PT_FAMILY_INDICATOR:
  raw: 0x322E3000
  value: "2.0"
TPM2_PT_LEVEL:
  raw: 0
TPM2_PT_REVISION:
  value: 1.38
TPM2_PT_DAY_OF_YEAR:
  raw: 0x8
TPM2_PT_YEAR:
  raw: 0x7E2
TPM2_PT_MANUFACTURER:
  raw: 0x494E5443
  value: "INTC"
TPM2_PT_VENDOR_STRING_1:
  raw: 0x496E7465
  value: "Inte"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x6C000000
  value: "l"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_TPM_TYPE:
  raw: 0x0
TPM2_PT_FIRMWARE_VERSION_1:
  raw: 0x1930001
TPM2_PT_FIRMWARE_VERSION_2:
  raw: 0x0
TPM2_PT_INPUT_BUFFER:
  raw: 0x400
TPM2_PT_HR_TRANSIENT_MIN:
  raw: 0x3
TPM2_PT_HR_PERSISTENT_MIN:
  raw: 0x7
TPM2_PT_HR_LOADED_MIN:
  raw: 0x3
TPM2_PT_ACTIVE_SESSIONS_MAX:
  raw: 0x40
TPM2_PT_PCR_COUNT:
  raw: 0x18
TPM2_PT_PCR_SELECT_MIN:
  raw: 0x3
TPM2_PT_CONTEXT_GAP_MAX:
  raw: 0xFFFF
TPM2_PT_NV_COUNTERS_MAX:
  raw: 0x80
TPM2_PT_NV_INDEX_MAX:
  raw: 0x800
TPM2_PT_MEMORY:
  raw: 0x6
TPM2_PT_CLOCK_UPDATE:
  raw: 0x400000
TPM2_PT_CONTEXT_HASH:
  raw: 0xB
TPM2_PT_CONTEXT_SYM:
  raw: 0x6
TPM2_PT_CONTEXT_SYM_SIZE:
  raw: 0x100
TPM2_PT_ORDERLY_COUNT:
  raw: 0xFF
TPM2_PT_MAX_COMMAND_SIZE:
  raw: 0xF80
TPM2_PT_MAX_RESPONSE_SIZE:
  raw: 0xF80
TPM2_PT_MAX_DIGEST:
  raw: 0x20
TPM2_PT_MAX_OBJECT_CONTEXT:
  raw: 0x3A0
TPM2_PT_MAX_SESSION_CONTEXT:
  raw: 0xF8
TPM2_PT_PS_FAMILY_INDICATOR:
  raw: 0x1
TPM2_PT_PS_LEVEL:
  raw: 0x0
TPM2_PT_PS_REVISION:
  raw: 0x103
TPM2_PT_PS_DAY_OF_YEAR:
  raw: 0x0
TPM2_PT_PS_YEAR:
  raw: 0x0
TPM2_PT_SPLIT_MAX:
  raw: 0x80
TPM2_PT_TOTAL_COMMANDS:
  raw: 0x64
TPM2_PT_LIBRARY_COMMANDS:
  raw: 0x64
TPM2_PT_VENDOR_COMMANDS:
  raw: 0x0
TPM2_PT_NV_BUFFER_MAX:
  raw: 0x800
TPM2_PT_MODES:
  raw: 0x0

**Comment by idesai** [comment]
@iammrgenie use [this](https://github.com/tpm2-software/tpm2-tools/blob/master/scripts/utils/icert2pem.sh) to parse the pem cert.

**Comment by THS-on** [comment]
@idesai thanks for the script. It works on the cert provided by @iammrgenie.

Is there a Intel way to provision the EK certificate after the fact at the correct index (0x01c00002)?

**Comment by iammrgenie** [comment]
@idesai the script works great. Thank you for that. @THS-on I went ahead to manually change the NVRAM address accessed by the tpm_main.py file. I then defined a custom NVRAM index and uploaded the .der file into the NVRAM and run the keylime_agent script. Everything seems to be working with that. 

However, I think an easier method other than changing the NVRAM index accessed by the tpm_main.py would be very convenient. Being able to provision the correct index would of course be the best approach. So any clues on how to do this would be much appreciated

**Comment by iammrgenie** [comment]
The processor of the board is an 8th Generation Intel® Core™ i7 formerly called Whiskeylake. The last BIOS update provided by the manufacturer was in 2020, which I have already applied.

**Comment by THS-on** [comment]
I think we will add an option to load an EK certificate from disk. Here is the issue that tracks that enhancement: https://github.com/keylime/enhancements/issues/80

**Comment by iammrgenie** [comment]
Thanks. I think would be really convenient. Thanks for all the help
