### ISSUE TITLE
EACCESS on /dev/tpmrm0 due to missing supplementary group membership after dropping privs

### ISSUE THREAD

**Issue by berrange** [keylime/keylime#1038]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 36
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm 
 * Keylime version: 6.4.1

# Description 
Starting keylime_agent crashes immediately with
```
2022-06-23 08:24:11.879 - keylime.cloudagent - INFO - Dropped privileges to keylime:keylime
2022-06-23 08:24:11.895 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 33, in <module>
    sys.exit(load_entry_point('keylime==6.4.1', 'console_scripts', 'keylime_agent')())
  File "/usr/lib/python3.10/site-packages/keylime/cmd/agent.py", line 14, in main
    keylime_agent.main()
  File "/usr/lib/python3.10/site-packages/keylime/keylime_agent.py", line 685, in main
    (ekcert, ek_tpm, aik_tpm) = instance_tpm.tpm_init(
  File "/usr/lib/python3.10/site-packages/keylime/tpm/tpm_main.py", line 907, in tpm_init
    self.warn_emulator()
  File "/usr/lib/python3.10/site-packages/keylime/tpm/tpm_abstract.py", line 116, in warn_emulator
    if self.is_emulator():
  File "/usr/lib/python3.10/site-packages/keylime/tpm/tpm_main.py", line 903, in is_emulator
    return self.get_tpm_manufacturer() == "SW"
  File "/usr/lib/python3.10/site-packages/keylime/tpm/tpm_main.py", line 870, in get_tpm_manufacturer
    retDict = self.__run(["tpm2_getcap", "properties-fixed"])
  File "/usr/lib/python3.10/site-packages/keylime/tpm/tpm_main.py", line 233, in __run
    raise Exception(
Exception: Command: ['tpm2_getcap', 'properties-fixed'] returned 1, expected 0, output [], stderr [b'ERROR:tcti:src/tss2-tcti/tcti-device.c:452:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: Permission denied \n', b'ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: device \n', b'ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI \n', b'ERROR: Could not load tcti, got: "device:/dev/tpmrm0"\n']
```

We can see the 'keylime' user is a member of the 'tss' group:

```
# su - keylime -s /bin/id
uid=981(keylime) gid=980(keylime) groups=980(keylime),59(tss) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

and that the /dev/tpmrm0 device is owned by the 'tss' group:

```
# ls -al /dev/tpmrm0 
crw-rw----. 1 tss tss 253, 65536 Jun 23 06:56 /dev/tpmrm0
```

The problem is keylime's ``change_uidgid`` method makes no effort to load supplementary groups.

## Expected behavior vs. actual behavior 
Expected to start and open the /dev/tpmrm0 device without throwing an exception.

## Steps to reproduce problem
1. Provision a Fedora 36 virtual machine in KVM, exposing a virtual TPM using swtpm
2. Run keylime_agent

**Comment by ansasaki** [comment]
For me this looks like a packaging mistake. In my opinion the service should run as `keylime:tss` instead of `keylime:keylime`.

**Comment by ansasaki** [comment]
Hum, I think I'm a bit confused here. So, is the expected behavior for a process running under a given user to have all permissions given by all groups that includes that user?

**Comment by berrange** [comment]
> Hum, I think I'm a bit confused here. So, is the expected behavior for a process running under a given user to have all permissions given by all groups that includes that user?

Yes, that's the whole point of giving a user membership of multiple groups. In this case, the 'keylime' primary group lets admins share resources between keylime and another service or user, while the 'tss' secondary group gives keylime ability to access the TPM.  If keylime merely had 'tss' as its only primary group, there's no mechanism to share stuff between keylime and another account, without also granting access to every other service with 'tss' group membership.

**Comment by ansasaki** [comment]
OK, thank you, I learned something today! I always thought that the goal of supplementary groups was to compartmentalize access to resources so that a process could run using only the required access. In other words, for me the user could run a process using restricted access by selecting a subset of its supplementary groups.

I think we need a clone of this issue in https://github.com/keylime/rust-keylime. The rust agent will soon be the official agent, so we need to fix this there.
