### ISSUE TITLE
Project namespace

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#104]
"Oh no, not another rename!"

So opening this as its been on my mind for a while, but had bigger fish to catch at the time. I was speaking with an associate who wanted to try out Keylime and they asked me  'should I use "python-keylime" or "rust-keylime". I then explained how python-keylime provides the server components and that rust-keylime will eventually provide the agent. After explaining this I realised its kind of confusing for users, that we are naming the projects by their code base, rather then their function.

My recommendation (which is open to discussion here),  is that we rename this project to just 'keylime', and 'rust-keylime' to 'keylime-agent'.

I have done an impact assessment and its low. All we need to do is rename the projects in github settings and make a PR to change the URL in some of the README.md's. Anyone going to https://github.com/keylime/python-keylime or https://github.com/mit-ll/python-keylime will get redirected to https://github.com/keylime/keylime , likewise https://github.com/keylime/rust-keylime to https://github.com/keylime/keylime-agent

@frozencemetery @jetwhiz @nabilschear @leonjia0112 @atothRedHat @mbestavros

**Comment by lukehinds** [comment]
@frozencemetery @jetwhiz @nabilschear @leonjia0112 @atothRedHat @mbestavros

**Comment by lukehinds** [comment]
Another option is we keep them as they are, but we document it clearly. I see this as the inferior option TBH, but you folks could perhaps convince me otherwise.

**Comment by jetwhiz** [comment]
I guess that depends on what the eventual goal is for rust-keylime.  Are there any eventual/future plans to convert (e.g.) the verifier into rust as well?  

If it is going to stay only the node then I agree that python-keylime and rust-keylime is a bit confusing.

**Comment by lukehinds** [comment]
There was a discussion that the verifier and registrar would be ported to rust (before I came along so not sure if anything was committed too), but realistically if this happens, this work would not be complete anywhere in the near future.

Should that happen, then there is nothing to stop us changing namespaces again (or archiving python code and moving rust into /keylime), Its that certain or immediate that it should prevent us from addressing the current concern with naming.
