### ISSUE TITLE
script_vtpm_register.py wrong ext

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#106]
`script_vtpm_register.py` should have a `.sh`  extension (its a bash script).

**Comment by lukehinds** [comment]
hands off

**Comment by jetwhiz** [comment]
@nabilschear -- was there a reason why this had a shell extension instead of python, or can we just change this?  will this break anything with the vtpm procedures?

**Comment by nabilschear** [comment]
no, that was an oversight.  it should be .sh.  I even found where i screwed it up in our local github instance back in 2018.  That said, I'm not totally sure what that script does.  It was checked in by a previous developer (robert rudd) back in 2015.  So, i'm fine with getting rid of it as I doubt it works in the way we want.
