### ISSUE TITLE
Code improvement: refactor the use of temporary files in tpm_main.py

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#1067]
# Environment
 * OS / version: any 
 * Processor architecture: any
 * TPM Manufacturer: any
 * Keylime version: any

# Description 
The current use of temporary files in tpm_main.py is at once odd and inefficient. @aplanas and @THS-on have suggested some better, more pythonesque ways to rewrite it.

## Expected behavior vs. actual behavior 
Once the changes are in place, there will be no changes in behavior.

## Steps to reproduce problem
1.  Just inspect `tpm/tpm_main.py` in particular methods such as `_tpm2_checkquote` and `_tpm2_printquote` in `tpm` class

**Comment by stefanberger** [comment]
I think this issue should either have its title adjusted since tpm_main.py does not contain temporary files anymore, or be closed.

**Comment by maugustosilva** [comment]
@stefanberger you're right. Closing it now.
