### ISSUE TITLE
TEST_MODE should not update KEYLIME_DIR in config.py

### ISSUE THREAD

**Issue by lkatalin** [keylime/keylime#1075]
Proposal: remove the special handling for tests using [`TEST_MODE`](https://github.com/keylime/keylime/blob/9a60e8218d21b7d178be9fb90bbd476ba2aa83ba/keylime/config.py#L62-L73) and instead set `KEYLIME_DIR` to a temp dir for testing explicitly
Reference: https://cloud-native.slack.com/archives/C01ARE2QUTZ/p1645128109579199

Importance: this should help the Rust tests pass keylime/keylime CI

**Comment by lkatalin** [comment]
@avery-blanchard @THS-on @mbestavros

**Comment by lkatalin** [comment]
The Rust agent is already using a `KEYLIME_DIR` env var: https://github.com/keylime/rust-keylime/blob/master/src/common.rs#L421

Interestingly I don't see any `keylime_dir` config in `keylime.conf` under the cloud agent.

**Comment by mpeters** [comment]
`TEST_MODE` does more than just override the `KEYLIME_DIR` it also sets `DISABLE_EK_CERT_CHECK_EMULATOR` to `True` and sets `MOUNT_SECURE` to `False`.

It seems `DISABLE_EK_CERT_CHECK_EMULATOR` is mainly used by the tenant, but controlling `MOUNT_SECURE` will definitely affect the agent.

So are you proposing we drop `TEST_MODE` altogether? If so, how do we handle these other flags? Or are you proposing that `TEST_MODE` just stop overriding `KEYLIME_DIR`?

**Comment by lkatalin** [comment]
Thanks @mpeters , good clarifying questions.

IMO it probably just makes sense to stop overriding `KEYLIME_DIR`. From @THS-on 's [original comments](https://cloud-native.slack.com/archives/C01ARE2QUTZ/p1645128109579199):

> We already have the env variable `KEYLIME_DIR` to set the `WORK DIR` (default `/var/lib/keylime`). So i propose that we remove the special handling for tests from the python side and set `KEYLIME_DIR` to a temp dir for testing explicitly. KEYLIME_DIR should then also be implemented for the rust agent.
