### ISSUE TITLE
Python agent and rust agent differently parse revocation scripts in action list

### ISSUE THREAD

**Issue by Koncpa** [keylime/keylime#1085]
# Description

There is a issue with parsing a revocation scripts in action list. Python keylime agent parse differently two and more scripts in action_list, than python rust agent. Python agent parse each script with comma and rust agent parse scripts by lines.

## Expected behavior vs. actual behavior 
Revocation scripts will be parse by same way for both type of agents vs. revocations scripts are parsed differently for each type of agents. From my point of view it should be parsed scripts by lines in action list file.

## Steps to reproduce problem

1. Install tmt via `sudo dnf install -y tmt-all`
2. Clone specific branch where is test scenario for different algorithm `git clone --branch script_sudo https://github.com/Koncpa/keylime-tests.git`
3. Run test scenario with needed setup tasks, need to be inside cloned repo dir: `tmt run -vvv plan --name distribution-keylime-tests-github-ci prepare discover -h fmf provision --how virtual -i Fedora-36 -c system execute --how tmt --interactive login finish ` 

# Relevant logs
```

Aug 24 08:28:04 ip-172-31-24-208.us-east-2.compute.internal keylime_agent[4559]: 2022-08-24 08:28:04.921 - keylime.cloudagent - WARNING - Exception during execution of revocation action local_action_modify_payload
Aug 24 08:28:04 ip-172-31-24-208.us-east-2.compute.internal keylime_agent[4559]: local_action_sudo_script: No module named 'local_action_modify_payload\nlocal_action_sudo_script'
```

[ANOTHER LOGS](
https://artifacts.dev.testing-farm.io/322520e7-2e41-4538-b029-233624b3a918/)

**Comment by mpeters** [comment]
@Koncpa I think this should be moved to the rust-keylime repo as it seems to be a bug on their side. It's fine if the new agent does both cases (comma or newline) but it at least needs to support the old way.

**Comment by Koncpa** [comment]
Sure, I will close here and open new issue in rust.
