### ISSUE TITLE
Code improvement: fix Python typing issues

### ISSUE THREAD

**Issue by mdrocco** [keylime/keylime#1131]
# Environment
 * OS / version: any
 * Processor architecture: any
 * TPM Manufacturer: any
 * Keylime version: any

# Description 
Static code analysis reports several typing issues in most Python files.

## Expected behavior vs. actual behavior 
There will be no changes in behavior, apart from (hopefully) a reduced rate of failures due to unforeseen subtleties.

## Steps to reproduce problem
1. Run any Python file through a static type analyzer (e.g. `pyright`)

**Comment by THS-on** [comment]
@mdrocco I think this can be merged into https://github.com/keylime/keylime/issues/929, right?

**Comment by mdrocco** [comment]
Thanks for pointing it out, too bad I missed it in the first place, I will merge.
