### ISSUE TITLE
Upgrade minimum python version to 3.10

### ISSUE THREAD

**Issue by mdrocco** [keylime/keylime#1137]
Python 3.10 is already assumed implicitly here and there in several scripts, I think we should make it official. Alternatively, I will fix the code as part of #929 .

**Comment by aplanas** [comment]
I am packaging Keylime for openSUSE and some SLE versions, and Python 3.10 is only available in the Tumbleweed version. I know that there are packages for Fedora and RH. Moving too fast the Python interpreter would be a problem, as the distributions (specially the enterprise one) cannot move at this speed.

If it is assumed in some scripts that can be OK, but the code needs to be CI tested for older versions, to be sure that those are still supported.

**Comment by THS-on** [comment]
We target Python 3.6 as our lowest supported version. If something does not work on Python 3.6 it is considered a bug in most cases. Note that for dataclasses we ship a compatibility module to make it work with 3.6.

**Comment by mdrocco** [comment]
Thank you @aplanas and @THS-on for clarifying. I realized the issue raised by the type checker is circumvented by the `_CONFIG_FALLBACK` mechanism in `config.py`. I can safely close this issue.
