### ISSUE TITLE
Verifier not logging into a file: /var/log/keylime/verifier.log

### ISSUE THREAD

**Issue by zkolpet** [keylime/keylime#1174]
# Environment
 * OS / version: Ubuntu 22.04
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: 6.5.0

# Description 
Verifier component is not logging into a file /var/log/keylime/verifier.log when set so in verifier.conf.

config preview:
Destination for log output, in addition to console. If left empty, the log
output will only be printed to console (recommended for containers to avoid
filling data storage). The accepted values are:
'file': The log output will also be written to a file named after the
        component in '/var/log/keylime/verifier.log'
'stream': The log output will be written to a common file in
          'var/log/keylime/keylime-stream.log'
log_destination = file

This log file: /var/log/keylime/verifier.log is not simply created. I have the same settings for registrar and registrar is creating and logging into this log file just fine: /var/log/keylime/registrar.log.

## Expected behavior vs. actual behavior 
Expected:
Verifier component is logging into **/var/log/keylime/verifier.log** when **log_destination = file** set in verifier.conf

Actual:
Verifier component IS NOT logging into **/var/log/keylime/verifier.log** when **log_destination = file** set in verifier.conf

## Steps to reproduce problem
1. Start keylime server side
2. See that no /var/log/keylime/verifier.log is created.

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
Thanks for reporting. I have found the cause of issue: the log_destination option is in the revocation section, which makes this fail. See:
https://github.com/keylime/keylime/blob/56e951a851b9a12a58fa473da94d1c1bf1415676/scripts/templates/2.0/verifier.j2#L200-L207

On another note this only logs the entries produced directly by the verifier and not other components in Keylime used by the verifier (e.g. IMA).

**Comment by zkolpet** [comment]
Fix confirmed. Moving the log section out of [revocations] section makes it work and /var/log/keylime/verifier.log is now properly generated.

Thank you
