### ISSUE TITLE
Keylime server logs created with not secured permissions

### ISSUE THREAD

**Issue by zkolpet** [keylime/keylime#1207]
# Environment
 * OS / version: Ubuntu22.04
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: 6.5.2

# Description 
verifier.log and registrar.log created with wrong permisssions 644. These are not secured enough permissions. All logs should be created with permissions 640.

## Expected behavior vs. actual behavior 
Expected: verifier and registrar logs are created with 640 permissions

## Steps to reproduce problem

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
I think the issue here is that we set the umask in the main method after the logging module already created the files.
See here: 
https://github.com/keylime/keylime/blob/5db2f7b94fe0bf36e8ca2e2218eedc159bb0a297/keylime/cloud_verifier_tornado.py#L1356

We can either call umask when initializing the logging or just move those calls out of the `main()` method and put them before calling anything else.

@aplanas @sergio-correia @ansasaki opinions on how we should solve that?

**Comment by zkolpet** [comment]
I am fine with whatever solution as long as it works :)

**Comment by aplanas** [comment]
> We can either call umask when initializing the logging or just move those calls out of the `main()` method and put them before calling anything else.
> 
> @aplanas @sergio-correia @ansasaki opinions on how we should solve that?

IMHO none. `umask` is a trigger bomb and we are already on top of it.

I inspected the code of Python logging module and there is no place to set the file permissions, but I think that a bit better approach is now when the logging configuration is done, just before, to be sure that we create the file and do a `os.chmod` unconditionally later.

A better approach is IMHO what `rust-keylime` is doing: write that in stdout! That way systemd will take care of it and make the service logs accessed by `journalctl` : ))

**Comment by zkolpet** [comment]
Hi,

little workaround I did for now is what @aplanas mentioned above as "a bit better approach":

in keylime_logging.py module (last 3 lines in below code):

    if loggername in LOG_TO_FILE:
        logfilename = os.path.join(LOGDIR, f"{loggername}.log")
        if not os.path.exists(LOGDIR):
            os.makedirs(LOGDIR, 0o750)
        if not os.path.isfile(logfilename):
            with open(logfilename, "a"):
                os.chmod(logfilename, 0o640)

**Comment by aplanas** [comment]
Do you want to make a PR?

**Comment by THS-on** [comment]
> A better approach is IMHO what rust-keylime is doing: write that in stdout! That way systemd will take care of it and make the service logs accessed by journalctl : ))

We also support that. The file logging is mostly there for legacy reasons. We can also just remove it.

**Comment by mpeters** [comment]
I agree that it's weird that each service logs to `STDOUT` and to a logfile and would rather that it just sent to `STDOUT` and packaging/systemd can take care of the rest. But we should make sure to coordinate it in a way with packagers so it doesn't disrupt users too much.
