### ISSUE TITLE
Fedora package orphaned

### ISSUE THREAD

**Issue by travier** [keylime/keylime#1212]
The Fedora package has been orphaned: https://src.fedoraproject.org/rpms/keylime

**Comment by mpeters** [comment]
@sergio-correia or @ansasaki can you comment on this?

**Comment by ansasaki** [comment]
@mpeters I think @sergio-correia can take it, as he is a co-maintainer, but he is on PTO this week. I can try to take the package maintenance if we can't wait for Sergio

**Comment by travier** [comment]
I'd suggest someone from the project here take the package and then orphans it again if needed to transfer it to someone else.

**Comment by ansasaki** [comment]
I'll take it then, we can transfer it later if needed
