### ISSUE TITLE
Add a CI test for tpm2-tools v3.X

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#123]
As per PR: https://github.com/keylime/keylime/pull/118#issuecomment-490278494

Add CI tests for:

tpm2-tss version 2.0.x
tpm2-tools 3.X from https://github.com/tpm2-software/tpm2-tools/ (not our fork)
tpm2-abrmd version 2.0.3

**Comment by THS-on** [comment]
With the end-to-end test we cover now a wide range of supported tpm2-tools versions and we no longer require custom build versions of tpm2-tools. @mpeters I think this can be closed.
