### ISSUE TITLE
install.sh referenced repo updates

### ISSUE THREAD

**Issue by atothRedHat** [keylime/keylime#128]
# Description 
The following repo references in install.sh should be replaced with official keylime repo locations 

KEYLIME_GIT=https://github.com/mit-ll/keylime.git
TPM4720_GIT=https://github.com/mit-ll/tpm4720-keylime.git

**Comment by lukehinds** [comment]
Taking this one as its fixed in the coming Python 3 port:

https://github.com/keylime/keylime/pull/126

**Comment by axelsimon** [comment]
Done, thanks for pointing this out @atothRedHat. I also see that the copyright mention in `installer.sh` is still:
> Copyright 2017 Massachusetts Institute of Technology.

Might want to update that.
