### ISSUE TITLE
Configurable database selection using ORM

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#130]
Some users may prefer to use a more production suitable database such as postgres.

We can provide a toggle during installation, & within the `keylime.conf` where the user can set their own preferred database, so either `database =` `sqlite` \ `postgres`. 

We also require ORM for building out the auth system and an early iteration of multi tenancy.

**Comment by lukehinds** [comment]
Going to start on this, as we need to rework the database for the UI and Auth.

After some thought, the best way to do this is to use sqlalchemy - this then abstracts away the complexities of having to format raw strings differently for each DB and introduces an ORM approach to ease implementation of a multi tenancy model with many-to-many , many-to-one and other relational DB design patterns.

**Comment by nabilschear** [comment]
that sounds great!  the db support is terrible.  i do hate databases

**Comment by rajdroid** [comment]
Yeah, ORM abstraction will make code more elegant. BTW, if you need a helping hand with anything @lukehinds do let me know.

**Comment by lukehinds** [comment]
> Yeah, ORM abstraction will make code more elegant. BTW, if you need a helping hand with anything @lukehinds do let me know.

Thanks @rajdroid , I will definitely tag you for review if you have some ORM experience.

**Comment by rajdroid** [comment]
Sure @lukehinds.

**Comment by lukehinds** [comment]
@jetwhiz / @nabilschear 

I am bit confused about:

https://github.com/keylime/keylime/blob/c409cc462d03042b26d8e9af39212138a2c990a7/keylime/cloud_verifier_common.py#L424-L432

These look like table row names, but we don't create them as part of the database schema? 

I see we add them as default values here:

https://github.com/keylime/keylime/blob/c409cc462d03042b26d8e9af39212138a2c990a7/keylime/keylime_sqlite.py#L84-L87

But again no table rows have been created from what I can see?

**Comment by lukehinds** [comment]
Oh hold on, I get it. I guess this is to strip the values out from the request response and not add them to the DB?

**Comment by nabilschear** [comment]
yeah, sorry the db support is terrible because i hate databases (and suck at interacting with them).  there were some things that i didn't want to have be persistent across threads/processes.   So, a verifier thread holds on to an agent dictionary with all this data.  Some of that data is also synced to the database, but the exclude_db keys in the dict are not.  It's basically ephemeral process/thread local state associated with the agent.  some of which can't be serialized (e.g., pending event)
