### ISSUE TITLE
Investigate removal of shell=True calls

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#131]
`shell=True` is susceptible to shell execution attacks from unsanitized input [0]

Investigate what hardening we can do.

[0] https://security.openstack.org/guidelines/dg_avoid-shell-true.html

**Comment by bu3alwa** [comment]
Is there a reason why we use Shell=True?

**Comment by lukehinds** [comment]
```
def ping(myserver):
    return subprocess.check_output('ping -c 1 %s' % myserver, shell=True)

>>> ping('8.8.8.8')
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=5.82 ms
```

```
>>> ping('8.8.8.8; rm -rf /')
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=6.32 ms
rm: cannot remove `/bin/dbus-daemon': Permission denied
rm: cannot remove `/bin/dbus-uuidgen': Permission denied
rm: cannot remove `/bin/dbus-cleanup-sockets': Permission denied
rm: cannot remove `/bin/cgroups-mount': Permission denied
rm: cannot remove `/bin/cgroups-umount': Permission denied
```

:)

https://medium.com/python-pandemonium/a-trap-of-shell-true-in-the-subprocess-module-6db7fc66cdfd

**Comment by lukehinds** [comment]
never answered your question, we should not be using it, its better to use `False`

```
def ping(myserver):
    args = ['ping', '-c', '1', myserver]
    return subprocess.check_output(args, shell=False)
```
```
>>> ping('8.8.8.8; rm -rf /')
ping: unknown host 8.8.8.8; rm -rf /
```

**Comment by bu3alwa** [comment]
@lukehinds yea we should use False. I am just wondering why we are using True in the first place? Is there anything in keylime that needs the tag True?

**Comment by lukehinds** [comment]
No, no reason. It's just code from when the project was more of a prototype whereas now we are trying to refactor things to be a bit more secure and optimised.

**Comment by kaifeng** [comment]
I am taking this assignment o/
