### ISSUE TITLE
keylime_attest should return non-zero exit code on attestation failure

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1334]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 37
 * Processor architecture:  x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current upstream [5278a84](https://github.com/keylime/keylime/commit/5278a84fcac927da49933a8396874909fc7dfa59)

# Description 
When running `keylime_attest` to do off-line attestation the script itself should return non-zero exit code (e.g. 1) when some agent fails the attestation.

## Expected behavior vs. actual behavior 
Exit code is 0 both for successful and unsuccessful attestation.

## Steps to reproduce problem
1. fail the agent
2. run `keylime_attest` script
See e.g. https://github.com/RedHat-SP-Security/keylime-tests/pull/336 (durable-attestation test is passing because the test has not yet been updated to expect non-zero exit code)

# Relevant logs
```
               out: :: [ 10:39:24 ] :: [   PASS   ] :: Command 'keylime_attest' (Expected 0, got 0)
                out: :: [ 10:39:24 ] :: [   PASS   ] :: File '/var/tmp/rlRun_LOG.WlcJOaB1' should contain 'WARNING - File not found in allowlist: /bad-script.sh' 
                out: :: [ 10:39:24 ] :: [   PASS   ] :: File '/var/tmp/rlRun_LOG.WlcJOaB1' should contain 'ERROR - IMA ERRORS: Some entries couldn't be validated.' 
                out: 2023-03-13 10:39:24.014 - keylime.durable_attestation_fetch_and_replay - INFO - ---------- Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 was NOT in "attested" state at 03/13/2023, 10:39:22 (TPM delta: 0): ima.validation.ima-ng.not_in_allowlist {"message": "File not found in allowlist: /bad-script.sh"}
                out: :: [ 10:39:24 ] :: [   PASS   ] :: File '/var/tmp/rlRun_LOG.WlcJOaB1' should contain 'keylime.durable_attestation_fetch_and_replay - INFO -.*Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 was NOT in "attested" state at.*' 
```

**Comment by kkaarreell** [comment]
Hi @maugustosilva , what is your opinion on this one?

**Comment by maugustosilva** [comment]
Should absolutely return non-zero. It is a bug, will fix it, thanks.
