### ISSUE TITLE
Faced error when trying Keylime with a TPM emulator

### ISSUE THREAD

**Issue by Ruoyu-y** [keylime/keylime#1342]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)
No

# Environment
 * OS / version: centos8/ubuntu22.04
 * Processor architecture: x86
 * TPM Manufacturer: None
 * Keylime version: latest 

# Description 
Try Keylime with the commands listed on the web page. When it comes to 'vagrant up --provision', some error poped out:
TASK [ansible-keylime-tpm20 : Install TPM Emulator service] ********************
fatal: [keylime-fedora1]: FAILED! => {"changed": false, "msg": "Source /root/keylime/ima_stub_service/tpm_emulator.service not found"}
Checked the code in the repo and there's no such 'ima_stub_service' folder available in the repo. Is this an outdated ansible playbook??

## Expected behavior vs. actual behavior 
should bring up a emulator service and continue the installation process.

## Steps to reproduce problem
1. git clone https://github.com/keylime/keylime-vagrant-ansible-tpm-emulator
2. vagrant up --provision

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
I think @mpeters did fixed the vagrant setup, to work again, so I think this issue can be closed
