### ISSUE TITLE
Use logging instead of print statement

### ISSUE THREAD

**Issue by ozoder** [keylime/keylime#137]
There are multiple instances where info/warnings/errors are printed to the standard output using the print statement. Where it makes sense, we should use logging instead. Some of the more notable files using print are:

- keylime/common.py
- keylime/ima.py
- keylime/user_data_encrypt.py
- keylime/serve_uuid.py

Since the Python 3 port will be finished soon, it's worth postponing the work on this issue until the port is done to avoid merge conflicts.

**Comment by lukehinds** [comment]
https://github.com/keylime/keylime/pull/144
