### ISSUE TITLE
keylime/cloud_verifier_tornado.py:  when the enable_agent_mtls config of verifier is set false, we need to use http to replace https

### ISSUE THREAD

**Issue by hustliyilin** [keylime/keylime#1373]
We need to decide whether to provide a http or https service according to `enable_agent_mtls` config of verifier.

**Comment by ansasaki** [comment]
Are you sure this is not already done? The context to access the agent is generated by the `generate_agent_tls_context`, which basically returns `None` when the `enable_agent_mtls` option is `False`

I see in the code:
https://github.com/keylime/keylime/blob/6604cb5ddb923a8de4dc784b03f9afbc2d2df3c0/keylime/web_util.py#L316-L319

**Comment by hustliyilin** [comment]
Hi @ansasaki ，

When I run `keylime_verifier &` with the `enable_agent_mtls=false`， it means I will use the http rather than https. Then I use the RESTful APIs about verifier, there is an error like this,

![image](https://github.com/keylime/keylime/assets/6824093/53aa39d9-28d4-47eb-a61a-8802d17bbe2b)

I read the codes in the [cloud_verifier_tornado.py](https://github.com/keylime/keylime/blob/master/keylime/cloud_verifier_tornado.py#L1552),  I find that the `ssl_options=ssl_ctx` isn't related about the `enable_agent_mtls` config. 

![image](https://github.com/keylime/keylime/assets/6824093/53b197b2-d57c-4a0f-9af0-7a28e68cf624)

So I initiate the PR #1372 to fix this issue.

**Comment by mpeters** [comment]
Shouldn't `enable_agent_mtls` be about the agent's APIs not the verifier's?

**Comment by ansasaki** [comment]
> Shouldn't `enable_agent_mtls` be about the agent's APIs not the verifier's?

@mpeters Right, now I understand the confusion. 

@hustliyilin The `enable_agent_mtls` option is about the agent API, meaning if the verifier should access the agent via HTTP or HTTPS. IIRC, there is no way to disable HTTPS for the verifier API, and in my opinion it should not be implemented.

For testing purposes, you can set the `trusted_client_ca` and `trusted_server_ca`  with the keyword `all`, which will disable certificate verification, but will not disable HTTPS.

**Comment by maugustosilva** [comment]
@hustliyilin the explanation provided by @ansasaki is correct. `enable_agent_mtls` was carefully negotiated as way to disable the need for TLS certificates on the **agents** when communicating back to `verifiers` and `registrars` (in an exceptionally well-controlled production environment where other mechanisms (e.g, NAC, EK pre-recording) significantly decreased the likelihood of identity spoofing). 

If you want/need to disable mTLS between "server-side" components (`verifiers` and `registrars`) we should have a much longer discussion about it.

**Comment by hustliyilin** [comment]
Thank you very much for the explanation @maugustosilva @ansasaki . I understand now, I close this issue now.
