### ISSUE TITLE
Validate against Fedora CoreOS

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#140]
Establish if Keylime can be run on Fedora CoreOS and what the state of TPM support is.

Experiment if we can provision Keylime with the ignition template system:

https://fedoramagazine.org/introducing-fedora-coreos/

**Comment by lukehinds** [comment]
Keep

**Comment by lukehinds** [comment]
@JAORMX

**Comment by lukehinds** [comment]
ref; https://github.com/coreos/rpm-ostree/issues/1883

**Comment by bu3alwa** [comment]
Is there anything I can help with this issues?

**Comment by lukehinds** [comment]
> Is there anything I can help with this issues?

Hi @bu3alwa , so sorry. I missed your comment here. I think we might be able to find something more defined to work on if you're interested. Could you jump onto https://gitter.im/keylime-project/community and we can have a chat and find something that's a good fit for you to work on!

**Comment by TheNewGuyAtGithub** [comment]
hey, I am new this. And want to handle this issue. lemme know if you want something>
