### ISSUE TITLE
Set all string declarations using f-strings

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#141]
Once Python 3 support is in, we should port string declaration to using f-strings.

f-strings are much easier to read. for example:

```
>>> name = "Eric"
>>> age = 74
>>> f"Hello, {name}. You are {age}."
'Hello, Eric. You are 74.'
```

Can be used in function calls:

```
>>> def to_lowercase(input):
...     return input.lower()

>>> name = "Eric Idle"
>>> f"{to_lowercase(name)} is funny."
'eric idle is funny.'
```

There are also much faster then `%s` and `str.format()`

This would make a line such as the following, much easier to read:

https://github.com/keylime/keylime/blob/d46237141be8585d337518ec95f91953c637afff/test/test_restful.py#L559

More details here: https://www.python.org/dev/peps/pep-0498/

**Comment by amylily1011** [comment]
This one sounds like fun! May I take this issue, @lukehinds ?

**Comment by lukehinds** [comment]
Hi @amylily1011 yes please!

I would wait for the Python 3 patch to merge first though, as f-strings only work in Python 3 (we currently working on Python 2!)

**Comment by amylily1011** [comment]
I will keep an eye on #32 , when it gets merged.

**Comment by amylily1011** [comment]
Hey @lukehinds, I got a head start on the f-string on your python-3 branch. It's still WIP, but really fun, so far. I expect to be done with this sometime next week, (I think), how do I push it to your branch?

**Comment by lukehinds** [comment]
Hi @amylily1011

Good question, you should be able to add a commit on top of my patch. If you like we can work together doing this over gitter when I return (about one week). Or if you want I can push the latest and we then merge yours on top (as I expect your work will have less merge conflicts to fix up) 


Thank you for working on this, really appreciate your contributions!

**Comment by amylily1011** [comment]
@lukehinds 
Sure! Let's do this over gitter, I should be done then too.

**Comment by lukehinds** [comment]
hi @amylily1011 - The Python 3 stuff is almost complete now, all the performance issues are resolved. Lets merge that and I can help you layer these on top. That way we can get CI to pass too.

**Comment by amylily1011** [comment]
Hey @lukehinds sounds good! I'm pretty much done with the f-string as well.

There is only one line that I'm not sure how to turn it into the f-string:

`logger.error("IMA ERRORS: template-hash %d fnf %d hash %d good %d"%tuple(errs))`

because it calls the tuple. 

So I left it for now :P

But I'm ready when you're ready.

**Comment by amylily1011** [comment]
Hi @lukehinds,
I'm going to be in the CEST timezone until Wednesday and then I'll be on GMT+7 (Bangkok). Feel free to set up anytime to sync, so we can merge it on top of your branch :) .

**Comment by lukehinds** [comment]
hi @amylily1011 , not forgotten about you, the patch is almost merged now and we can then get your code in! :)

**Comment by amylily1011** [comment]
Hey @lukehinds,
I'm halfway copying the diff over, so I guess, we can cancel the meeting at 4pm for now :).

**Comment by lukehinds** [comment]
hi @amylily1011 

I am on gitter and online now, so just instant message me whenever you like (that also stands for anytime, meeting or not).

**Comment by lukehinds** [comment]
keep alive
