### ISSUE TITLE
database_pool_sz_ovfl option is ignored

### ISSUE THREAD

**Issue by mslacken** [keylime/keylime#1428]
# Environment
 * OS / version:  openSUSE Tumblweed
 * Processor architecture: x86_64
 * TPM Manufacturer:  virtual
 * Keylime version: 7.3.0

# Description 

The option 
```
database_pool_sz_ovfl
```
is silently ignored. Although its set I see following error
```
QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 
```
with `journctl -u keylime_verifier`.

The option was set `/etc/keylime/verifier.conf` and for debugging purpose in `/usr/etc/keylime/verifier.conf`.

**Comment by maugustosilva** [comment]
Hi @mslacken, which database have you used on this test? Can you provide the contents of `database_url` from your `/etc/keylime/verifier.conf`?

**Comment by mslacken** [comment]
I just used the 'SQlite' backend as I did not want to configure that much. I don't have the paths right now, but can provide them later.

**Comment by maugustosilva** [comment]
Ah, I see... `sqlite` backend does not have support for `database_pool_sz_ovfl`, it is explicitly ignored on this particular case.
