### ISSUE TITLE
We have to modify the default binding and listening IP about the agent, verifier, and registrar server manually when they are deployed on different machines

### ISSUE THREAD

**Issue by Jingshui1037** [keylime/keylime#1445]
The default binding and listening IP in `templates/2.0` about the agent, verifier, and registrar server are all `127.0.0.1` which means they only can be accessed by the same machine according to the following codes:
- agent：https://github.com/keylime/rust-keylime/blob/master/keylime-agent/src/main.rs#L701
- verifier: https://github.com/keylime/keylime/blob/master/keylime/cloud_verifier_tornado.py#L1467
- registrar: https://github.com/keylime/keylime/blob/master/keylime/registrar_common.py#L473 and https://github.com/keylime/keylime/blob/master/keylime/registrar_common.py#L513

So we have to modify the default binding  and listening IP about the agent, verifier, and registrar server manually when they are deployed on different machines. Maybe it isn't friendly to the users. 

Therefore, I want to modify the default binding and listening IP about the agent, verifier, and registrar server as `0.0.0.0` in the #1444

**Comment by aplanas** [comment]
IMHO 127.0.0.1 is the correct one as a default. It is true that the default is not usable during deployment, but the default in upstream should me a secure one.

**Comment by THS-on** [comment]
I agree with @aplanas on this. The defaults should be as secure as possible.

**Comment by maugustosilva** [comment]
The default should be as secure as possible, and there is at least two mechanisms to override the defaults: a) passing a **custom** template when invoking `keylime_upgrade_config` (option `--templates`) or b) setting the environment variable `KEYLIME_AGENT_IP`.
