### ISSUE TITLE
keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography: error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["RawCertificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }

### ISSUE THREAD

**Issue by Jingshui1037** [keylime/keylime#1452]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

No

# Environment
 * Keylime version: master

# Description 

Parsing the following certs in the `tpm_cert_store` will cause these warnings when using `keylime_tenant` with user-selected PCRs monitoring.
-  NTC2.pem
-  NUVO_1111.pem
- NUVO_0100.pem
- NUVO_2111.pem
- NUVO_2110.pem
- NUVO_1110.pem
- NTC1.pem

![image](https://github.com/keylime/keylime/assets/135581562/e3553002-a5a1-48a6-883f-ab8807b3d0f4)

Can we fix these warnings?

**Comment by sergio-correia** [comment]
Related: https://github.com/pyca/cryptography/issues/7189

**Comment by THS-on** [comment]
Those warnings are expected and we could make them maybe more readable.  @ansasaki @maugustosilva what do you think?

**Comment by maugustosilva** [comment]
We should/could make it more readable indeed, but functionally there is nothing "wrong" here, and WARNING is the correct debug level.
