### ISSUE TITLE
Move installer.sh to using packages

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#146]
I recommend we start using packages for the installer.

They are more stable and simplifies the installation a lot!

Packages also work better for Fedora, as the packages include SELinux labels (which means being able to run without needing to disabled SE). I also believe the Ubuntu tpm2-tools package has the needed code release upstream.

We should instead move tools / tss etc compiling to a CI job 

@nabilschear @jetwhiz  agree / disagree?

**Comment by nabilschear** [comment]
i think that would be great, but a lot of work to support for many distros.  I like the idea of keeping the installer for our tier2 distro support and then focus on getting fedora to work just with rpms.

**Comment by lukehinds** [comment]
> i think that would be great, but a lot of work to support for many distros. I like the idea of keeping the installer for our tier2 distro support and then focus on getting fedora to work just with rpms.

I am sure I could do something, I could add a flag to build the tools instead of using packages.
