### ISSUE TITLE
Take down the old readthedocs link?

### ISSUE THREAD

**Issue by arkivm** [keylime/keylime#1469]
# Description 
#1104 made the old documentation obsolete. However, it is still hosted at https://keylime-docs.readthedocs.io/en/latest/, containing outdated information. Even worse, that's the first result on google if you search for keylime docs. 

Could it be taken down in favor of the new documentation hosted at https://keylime.readthedocs.io/en/latest/? The [repo](https://github.com/keylime/keylime-docs) is archived anyway. Or, the old readthedocs should point to the new documentation if you don't want to take em down.

**Comment by ansasaki** [comment]
Hello @lukehinds, could you please help us with this?

**Comment by arkivm** [comment]
The [old doc](https://keylime-docs.readthedocs.io/en/latest/) now points to the latest documentation (as of 20:05 UTC). Feel free to close this issue if you get a confirmation from @lukehinds.

**Comment by maugustosilva** [comment]
Taking down the old doc has become an issue, since we lost the password to the aforementioned repository during the PTL (multiple) transitions... @mpeters @lukehinds The best we can aim for is to keep synchronizing the new and old doc repositories for the time being, IMO
