### ISSUE TITLE
Public Key parse error in tpm2_objects.py

### ISSUE THREAD

**Issue by Isaac-Matthews** [keylime/keylime#1471]
# Environment
keylime/master

# Description 
Using `pubkey_parms_from_tpm2b_public()` from `tpm2_objects.py` returns `Error: Misparsed either modulus or keybits` when processing some keys. This is because too much is being skipped  when the scheme algorithm is null.

I have a fix for this that I will add.

## Expected behavior vs. actual behavior 
Expected: provide the function with a tpm key and return the public key
Actual: error due to modulus not matching keybits

## Steps to reproduce problem
1.  Use the function on the following two RSA keys (turn into bytes first). The first will not work, the second does work.

Key1: `[1, 54, 0, 1, 0, 11, 0, 4, 0, 242, 0, 32, 173, 107, 58, 34, 132, 253, 105, 138, 7, 16, 191, 92, 193, 185, 189, 241, 94, 37, 50, 227, 246, 1, 250, 75, 147, 166, 168, 250, 141, 229, 121, 234, 0, 16, 0, 16, 8, 0, 0, 0, 0, 0, 1, 0, 148, 114, 75, 95, 217, 254, 147, 58, 133, 68, 247, 133, 18, 126, 241, 49, 4, 132, 110, 155, 14, 64, 56, 61, 154, 135, 16, 203, 94, 246, 32, 77, 154, 2, 17, 242, 40, 224, 29, 114, 255, 218, 57, 225, 162, 172, 241, 231, 37, 155, 87, 179, 214, 27, 130, 113, 41, 37, 104, 141, 59, 49, 9, 210, 22, 255, 152, 130, 99, 44, 152, 103, 125, 9, 3, 94, 209, 190, 110, 47, 217, 198, 92, 48, 199, 84, 69, 30, 68, 68, 99, 254, 38, 84, 243, 98, 132, 137, 115, 24, 26, 207, 252, 69, 250, 28, 173, 209, 98, 134, 196, 138, 15, 245, 230, 129, 170, 242, 248, 117, 53, 31, 9, 49, 89, 99, 199, 98, 209, 81, 45, 57, 80, 130, 186, 138, 39, 80, 156, 145, 70, 159, 4, 114, 178, 90, 248, 227, 68, 177, 33, 100, 45, 24, 57, 149, 128, 181, 177, 141, 221, 179, 137, 103, 113, 115, 5, 93, 181, 151, 30, 222, 237, 27, 1, 196, 28, 20, 133, 10, 209, 61, 181, 161, 233, 68, 219, 254, 82, 129, 159, 202, 80, 129, 18, 234, 111, 252, 1, 230, 111, 125, 59, 177, 243, 164, 162, 50, 254, 218, 192, 64, 57, 218, 148, 248, 54, 139, 56, 45, 236, 192, 114, 122, 195, 48, 78, 146, 116, 40, 105, 112, 163, 175, 113, 186, 207, 212, 104, 79, 90, 106, 147, 25, 78, 118, 17, 233, 109, 166, 51, 97, 250, 190, 178, 165]`

Key2: `[1, 56, 0, 1, 0, 11, 0, 5, 0, 242, 0, 32, 84, 55, 24, 35, 38, 228, 20, 252, 167, 151, 213, 241, 116, 97, 90, 22, 65, 246, 18, 85, 121, 124, 58, 43, 34, 194, 29, 18, 11, 45, 30, 7, 0, 16, 0, 22, 0, 11, 8, 0, 0, 0, 0, 0, 1, 0, 202, 18, 147, 51, 106, 138, 80, 164, 15, 249, 35, 17, 39, 197, 244, 85, 13, 211, 109, 157, 10, 238, 226, 140, 232, 52, 156, 171, 44, 125, 115, 142, 238, 107, 135, 234, 96, 125, 137, 210, 191, 221, 23, 191, 83, 44, 107, 154, 141, 104, 61, 120, 174, 76, 244, 76, 210, 249, 203, 12, 64, 209, 138, 225, 206, 251, 159, 65, 64, 180, 40, 59, 31, 52, 105, 88, 172, 96, 63, 224, 143, 114, 28, 2, 139, 86, 73, 88, 27, 35, 11, 111, 141, 205, 99, 242, 196, 1, 244, 65, 95, 172, 119, 177, 74, 201, 80, 176, 93, 68, 53, 64, 103, 94, 44, 178, 214, 134, 42, 39, 169, 203, 165, 28, 239, 139, 236, 191, 140, 169, 189, 22, 237, 14, 245, 4, 218, 109, 175, 141, 220, 108, 57, 102, 217, 106, 210, 158, 46, 37, 89, 120, 10, 16, 132, 238, 96, 61, 112, 241, 7, 196, 106, 3, 63, 143, 131, 173, 183, 220, 77, 108, 158, 151, 192, 122, 108, 123, 119, 74, 21, 39, 67, 100, 87, 7, 41, 248, 248, 76, 148, 1, 78, 154, 247, 96, 227, 195, 146, 195, 2, 155, 77, 4, 33, 93, 246, 103, 202, 26, 113, 111, 43, 19, 249, 181, 66, 158, 156, 138, 180, 215, 197, 40, 204, 36, 169, 165, 79, 13, 114, 2, 162, 163, 108, 201, 244, 221, 23, 246, 78, 20, 146, 246, 251, 234, 10, 93, 176, 241, 178, 18, 74, 215, 136, 159]`

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by stefanberger** [comment]
> Actual: error due to modulus not matching keybits

Is this an error occurring during parsing or when using the key?

**Comment by Isaac-Matthews** [comment]
During parsing, the error is in the `pubkey_parms_from_tpm2b_public` function, specifically [this error](https://github.com/keylime/keylime/blob/master/keylime/tpm/tpm2_objects.py#L302).
The error occurs because `keybits` is wrong so doesn't match the length of the modulus, and this is because `keybits` is being taken from the wrong place due to the extra +2 to skip.

**Comment by stefanberger** [comment]
> During parsing, the error is in the `pubkey_parms_from_tpm2b_public` function, specifically [this error](https://github.com/keylime/keylime/blob/master/keylime/tpm/tpm2_objects.py#L302).
> The error occurs because `keybits` is wrong so doesn't match the length of the modulus, and this is because `keybits` is being taken from the wrong place due to the extra +2 to skip.

I just tried with your 2nd key and it worked fine. Maybe it's the 1st key?

**Comment by stefanberger** [comment]
> > During parsing, the error is in the `pubkey_parms_from_tpm2b_public` function, specifically [this error](https://github.com/keylime/keylime/blob/master/keylime/tpm/tpm2_objects.py#L302).
> > The error occurs because `keybits` is wrong so doesn't match the length of the modulus, and this is because `keybits` is being taken from the wrong place due to the extra +2 to skip.
> 
> I just tried with your 2nd key and it worked fine. Maybe it's the 1st key?

It is the 1st key that's not working ...


```
diff --git a/keylime/tpm/tpm2_objects_test.py b/keylime/tpm/tpm2_objects_test.py
index 7022d15..c1ef36e 100644
--- a/keylime/tpm/tpm2_objects_test.py
+++ b/keylime/tpm/tpm2_objects_test.py
@@ -262,6 +262,22 @@ class TestTpm2Objects(unittest.TestCase):
         self.assertEqual(new_ec_pubkey_n.x, correct_ec_pubkey_n.x)
         self.assertEqual(new_ec_pubkey_n.y, correct_ec_pubkey_n.y)

+    def test_pubkey_from_tpm2b_public_rsa_2(self) -> None:
+        test_pubkey_bytes = base64.b64decode(
+            #'ATgAAQALAAUA8gAgVDcYIybkFPynl9XxdGFaFkH2ElV5fDorIsIdEgstHgcAEAAWAAsI'
+            #'AAAAAAABAMoSkzNqilCkD/kjESfF9FUN022dCu7ijOg0nKssfXOO7muH6mB9idK/3Re/U'
+            #'yxrmo1oPXiuTPRM0vnLDEDRiuHO+59BQLQoOx80aVisYD/gj3IcAotWSVgbIwtvjc1j8s'
+            #'QB9EFfrHexSslQsF1ENUBnXiyy1oYqJ6nLpRzvi+y/jKm9Fu0O9QTaba+N3Gw5Ztlq0p4'
+            #'uJVl4ChCE7mA9cPEHxGoDP4+DrbfcTWyel8B6bHt3ShUnQ2RXByn4+EyUAU6a92Djw5LD'
+            #'AptNBCFd9mfKGnFvKxP5tUKenIq018UozCSppU8NcgKio2zJ9N0X9k4Ukvb76gpdsPGyE'
+            #'krXiJ8='
+            'ATYAAQALAAQA8gAgrWs6IoT9aYoHEL9cwbm98V4lMuP2AfpLk6ao+o3leeoAEAAQCAAAAAAAAQCUcktf2f6TOoVE94USfvExBIRumw5AOD2ahxDLXvYgTZoCEfIo4B1y/9o54aKs8eclm1ez1huCcSklaI07MQnSFv+YgmMsmGd9CQNe0b5uL9nGXDDHVEUeRERj/iZU82KEiXMYGs/8RfocrdFihsSKD/Xmgary+HU1HwkxWWPHYtFRLTlQgrqKJ1CckUafBHKyWvjjRLEhZC0YOZWAtbGN3bOJZ3FzBV21lx7e7RsBxBwUhQrRPbWh6UTb/lKBn8pQgRLqb/wB5m99O7HzpKIy/trAQDnalPg2izgt7MByesMwTpJ0KGlwo69xus/UaE9aapMZTnYR6W2mM2H6vrKl'
+        )
+        new_rsa_pubkey, name_alg = pubkey_parms_from_tpm2b_public(test_pubkey_bytes)
+        print(f"{dir(new_rsa_pubkey)}  {new_rsa_pubkey.key_size}")
+        print("%x" % name_alg)
+        print(f"{type(new_rsa_pubkey)}")
+
     def test_pubkey_from_tpm2b_public_ec_without_encryption(self) -> None:
         new_ec_pubkey = pubkey_from_tpm2b_public(
             bytes.fromhex(
```

**Comment by Isaac-Matthews** [comment]
Ah yes my mistake, Key1 is the one that doesn't work, I will edit the issue.

**Comment by stefanberger** [comment]
You can take my test case and remove the silly print's and add it to the PR...
