### ISSUE TITLE
Add new IDevID and IAK configuration options to templates

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#1475]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: current master

# Description 
The IDevID and IAK related changes introduced new configuration options: https://github.com/keylime/rust-keylime/pull/608

This issue is to track the addition of the new configuration options to the configuration templates. Ideally this should be done with a minor configuration version bump.

## Expected behavior vs. actual behavior 
Expected: The IDevID and IAK related changes are present in the configuration templates
Actual: The IDevID and IAK related changes are not present in the configuration templates

## Steps to reproduce problem
1. Check configuration templates in `templates`

**Comment by Isaac-Matthews** [comment]
I will be adding this along with the finalised idevid/iak related config options in the next PR. Thanks.
