### ISSUE TITLE
Wrong configuration file paths in user guide (documentation)

### ISSUE THREAD

**Issue by derpedda** [keylime/keylime#1509]
# Environment
 * OS / version: All
 * Processor architecture: All
 * TPM Manufacturer: All
 * Keylime version: 7.8.0, commit [c7fae12](https://github.com/keylime/keylime/commit/c7fae12b4c11212994381f1ca435a8541bfc2a17)

# Description 
The documentation in the user_guide is inconsistent in regards to where the configuration files should be stored. The text states they should be in `/etc/keylime/`, but the table states that they should be stored in `/var/lib/keylime/*`.
This inconsitency is confusing for the user and also wrong, as all config files currently live in `/etc/keylime/` 

## Expected behavior vs. actual behavior 
I would expect the table to reflect the correct paths inside `/etc/keylime/*`, currently they point to `/var/keylime/*`

## Steps to reproduce problem
1.  Go to the Documentation or source-code 
    Doc: https://keylime.readthedocs.io/en/latest/user_guide/configuration.html
    code: https://github.com/keylime/keylime/blob/master/docs/user_guide/configuration.rst

# Relevant logs
Not relevant

I am also willing to do the change myself and do a PR for that

**Comment by maugustosilva** [comment]
Thank you, the paths are clearly incorrect. Please, by all means, open the PR and will merge promptly.
