### ISSUE TITLE
Action levels

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#155]
For IMA and tpm_policy we could set a action level of (node) FAILURE state or continued operational but reporting the failure.

This way a `critrical_whitelist` could be constructed of assets that are considered high security (libs, /etc contents).

A second `monitor_whitelist` could be constructed of assets of interest, but not seen as critical to the point of failing a node.

If a whitelist / IMA comparison fails for a critical list we put the agent into a failed state.

If a whitelist / IMA comparison fails for a minor list we fail notify, but don't go into a failed state.

**Comment by nabilschear** [comment]
this is an interesting idea.  we'll need to add a new state for the node to be in at the verifier (e.g., CloudAgent_Operational_State)

**Comment by jetwhiz** [comment]
We would also need to make some updates to the WebApp to support this.  In particular: 

https://github.com/keylime/keylime/blob/01785a25077fbb6b2c2220395a3fd99300583d43/keylime/static/js/webapp.js#L257-L283

https://github.com/keylime/keylime/blob/01785a25077fbb6b2c2220395a3fd99300583d43/keylime/tenant_webapp.py#L402

**Comment by rajdroid** [comment]
@lukehinds May I look into this feature?

**Comment by lukehinds** [comment]
I was thinking about your for this one @rajdroid  !

For a change like this one, please outline a design / change proposal into a document first (google doc)

Main points we need to consider are how do we notify the non critical items and for the whitelists, we need to consider structure. 

For example, do we have multiple files (whitelist1.txt , whitelist2.txt) or a single file with some sort of yaml / toml style:

for example

```
critical:
  bdc084cc61c67dada53ff92c3235fbc774eace36aceb11967718399837e36485  /boot/System.map-5.1.17-300.fc30.x86_64
  187e65c35f449df145b57940cb73606623ab1eccc352f5b0d9b64c4d2ad3be58  /boot/vmlinuz-5.0.9-301.fc30.x86_64

monitor:
  7fb94b644d95de6ed2f70c247cf9a572027815b8f6a00b8c5f7b9fd2feef0ff1  /usr/lib/kbd/consolefonts/lat7a-14.psfu.gz
  540f7b2732b8018be45dcfdf737fa6e51d9f5924d85b6c1987ddb4215260b49f  /usr/lib/kbd/consolefonts/lat2-12.psfu.gz
 ```

Tagging @amylily1011 for UI considerations

Let us know when you have something to share, and we can review in the g-doc!

**Comment by rajdroid** [comment]
Hi @lukehinds,

Sure I will prepare a design doc and share it with all for feedback.

**Comment by lukehinds** [comment]
unassigned @rajdroid 

this should also be raised an enhancement
