### ISSUE TITLE
ima_policy freezes machine

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#156]
The following IMA_POLICY freezes the boot of Fedora 30 (not sure on other OSes)

https://github.com/keylime/keylime/blob/master/demo/ima-policies/ima-policy-keylime-etc

![DSC_0835](https://user-images.githubusercontent.com/7058938/65318289-470aa200-db95-11e9-988e-faebfbf591e2.JPG)

**Comment by jetwhiz** [comment]
Can you comment out the new stuff (vs. https://github.com/keylime/keylime/blob/master/demo/ima-policy) and see which line causes it to fail?

**Comment by lukehinds** [comment]
I can take a look when I get back next week, it takes a bit of time, as you need to use a live rescue image to get a mount on /dev/mapper/root and make the change, reboot etc.
