### ISSUE TITLE
The `verification-keys` field in runtime policy is a string, but the specification expected an array

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#1564]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: current master (691f713)

# Description 
The enhancement that introduced runtime policies specified the `verification-keys` as an array:

https://github.com/keylime/enhancements/blob/2a462b60a1f40f257abf728af3269c1301752adc/70_ima_policy.md?plain=1#L241-L246

The code implemented the field as a single string:

https://github.com/keylime/keylime/blob/0b57e6c97cbfde83d2ab4a04952e2cf33b550e6f/keylime/ima/ima.py#L89

## Expected behavior vs. actual behavior 
Expected: The implemented schema should follow the specified schema
Actual: The implemented schema differs from the specified schema 

## Steps to reproduce problem
1. Compare the [specification](https://github.com/keylime/enhancements/blob/2a462b60a1f40f257abf728af3269c1301752adc/70_ima_policy.md?plain=1#L241-L246) with the [implementation](https://github.com/keylime/keylime/blob/0b57e6c97cbfde83d2ab4a04952e2cf33b550e6f/keylime/ima/ima.py#L89)

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by ansasaki** [comment]
@mbestavros @THS-on Could you please comment about this?

**Comment by ansasaki** [comment]
The changes required to fix this are extensive, with no benefits: in the end, using a JSON string is actually more flexible than replacing it with a list of  the public keys.

I propose we modify the specification documentation to align it with what was actually implemented. Also, the changes should include a schema validation of the JSON used in the `verification-keys`

**Comment by THS-on** [comment]
@ansasaki yes agree, then lets go this route.

**Comment by ansasaki** [comment]
The JSON schema validation for the `verification-keys` content was added as part of https://github.com/keylime/keylime/pull/1638, via commit c724a9d51d527bdbeba0840d398d017325b46fdf

The missing part is fixing the documentation to reflect the actual implemented schema
