### ISSUE TITLE
Containers failing to build after ecad8c3

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#1579]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: n/A
 * TPM Manufacturer: N/A
 * Keylime version: since (ecad8c3)

# Description 
After switching to pinned versions of containers instead of tagged versions, the builds are failing.
Apparently the github action `docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9` does not support using containers from quay.io, and the docker container registry does not contain the requested image with the specific hash.

## Expected behavior vs. actual behavior 
Expected: The containers are successfully built
Actual: The containers fail to build

## Steps to reproduce problem
1. See the history of  the Action `keylime-container-images` in the Actions tab

# Relevant logs
See https://github.com/keylime/keylime/actions/runs/9909624440

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
There seems to be another issue that the image base is not found now: https://github.com/keylime/keylime/actions/runs/9969780975/job/27547526004

**Comment by ansasaki** [comment]
> There seems to be another issue that the image base is not found now: https://github.com/keylime/keylime/actions/runs/9969780975/job/27547526004

Maybe we should rethink pinning the version instead of using the tag. The problem seems to be that the old image is dropped when a new image is pushed.

**Comment by THS-on** [comment]
@ansasaki is there an archive or some more stable containers? It's unfortunate that they remove the old ones pretty fast. We can of course  copy the Fedora base container into our repo, but then we also need a way to sync that one periodically.

**Comment by ansasaki** [comment]
> @ansasaki is there an archive or some more stable containers? It's unfortunate that they remove the old ones pretty fast. We can of course copy the Fedora base container into our repo, but then we also need a way to sync that one periodically.

I don't think they have an official archive for the images. I would say the easiest solution is for us to push a copy of Fedora base image or update our Keylime base image less frequently .

About updating it periodically, probably the easiest way is to write a scheduled workflow (e.g. monthly) that would fill a PR updating the base image.

**Comment by THS-on** [comment]
@ansasaki this looks like the best way forward, if we want to pin the exact container version. @lukehinds @ansasaki does anyone of you want to implement that?
