### ISSUE TITLE
revocation notifier features fail siliently

### ISSUE THREAD

**Issue by nabilschear** [keylime/keylime#161]
# Environment
 * OS / version: any
 * Processor architecture: any
 * TPM Manufacturer: any
 * Keylime version: master

# Description 

if an agent can't connect to the specified revocation notifier ip, it doesn't throw an error but fails silently.

Also the keylime_ca -c listen command lazy loads the ca certificate.  if it is available, it should check that the provided password was correct.  If the ca dir is not yet available, it should warn.

**Comment by lukehinds** [comment]
hi @nabilschear , are you working on this one?

**Comment by nabilschear** [comment]
not actively.  this unfortunately requires a decent amount of refactoring of the whole notification system.
