### ISSUE TITLE
`keylime_policy` options names are inconsistent

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#1610]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: current master (dc118c780a06cb72725f72bc8100665a07a5a12f)

# Description 
`keylime_policy` option names `--allowlist` and `--exclude-list` are inconsistent. They should both have the `-` or not.

Also some short options are not intuitive, probably better to drop them and keep only the long version. For example `-A` for `--add-ima-signature-verification-key`.

## Expected behavior vs. actual behavior 

Actual:
The options `--allowlist` and `--exclude-list` are inconsistent

Expected:
The options are consistent: either both have the `-` or not:

- `--allow-list` and `--exclude-list` or
- `--allowlist` and `--excludelist`

## Steps to reproduce problem
1. Run `keylime_policy create runtime --help` 

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by sergio-correia** [comment]
What would be the preferred way here?
`--allowlist/--excludelist` or `--allow-list/--exclude-list`?
