### ISSUE TITLE
`keylime_policy` log messages with incorrect level

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#1613]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: current master (dc118c780a06cb72725f72bc8100665a07a5a12f)

# Description 
`keylime_policy` logs a message for each line of the IMA measurement log, with the `INFO` level. Also, configuration files loading are also logged with `INFO` level.

These messages make the command line output excessively polluted. Moreover, these messages are not actionable from the user point of view and should probably be logged with `DEBUG` level.

## Expected behavior vs. actual behavior 
Expected: Messages that are not relevant for the user should be logged with `DEBUG` level
Actual: Messages that are not relevant for the user are logged with `INFO` level

## Steps to reproduce problem
1. run `keylime_policy create runtime --use-ima-measurement-list`

# Relevant logs
The reproducer command generates an output similar to:
```
INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
2024-08-08 17:36:22.993 - policy.create_runtime_policy - INFO - Skipping line that was split into 5 pieces, expected 6: 10 0adefe762c149c7cec19da62f0da1297fcfbffff ima-ng sha256:0000000000000000000000000000000000000000000000000000000000000000 boot_aggregate

{"meta": {"version": 1, "generator": 3, "timestamp": "2024-08-08 17:36:22.993441"}, "release": 0, "digests": {"boot_aggregate": ["0000000000000000000000000000000000000000000000000000000000000000"]}, "excludes": [], "keyrings": {}, "ima": {"ignored_keyrings": [], "log_hash_alg": "sha256", "dm_policy": null}, "ima-buf": {}, "verification-keys": ""}
```

**Comment by marcostork** [comment]
The keylime_policy will have (I believe it still needs to be implemented --ima_measurement_list) an option to create a policy from a given IMA measurement list. Wouldn't it be necessary for the user to know about this?

**Comment by ansasaki** [comment]
> The keylime_policy will have (I believe it still needs to be implemented --ima_measurement_list) an option to create a policy from a given IMA measurement list. Wouldn't it be necessary for the user to be aware of this event?

It is already implemented
