### ISSUE TITLE
tpm2-tools in RHEL

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#163]
To track issue in RHEL

https://bugzilla.redhat.com/show_bug.cgi?id=1755551

**Comment by jetwhiz** [comment]
Assuming we can pull tpm2-tools up to 3.2 in RHEL8, should we try targeting EPEL8 for Keylime so we can install/release it more easily in RHEL as well as Fedora?

**Comment by lukehinds** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1725714

**Comment by lukehinds** [comment]
RHEL has been updated now
