### ISSUE TITLE
installer.sh fails to install

### ISSUE THREAD

**Issue by UntriexTv** [keylime/keylime#1664]
# Environment
 * OS / version:  Every one,  apart from Fedora
 * Processor architecture: X
 * TPM Manufacturer: X
 * Keylime version: latest

# Description 
The installer.sh is outdated and failed to install Keylime on most of the systems I was able to test.
I am already working on the fix in my fork and will create pull request as soon as it'll be discussed in this issue.

I am creating this issue, because according to documentation it's required before contributing

## Steps to reproduce problem
1.  Run installer.sh on any OS apart from Fedora

**Comment by THS-on** [comment]
Which distributions did you try exactly?

Can you check if this PR https://github.com/keylime/keylime/pull/1665 fixes it for you?

**Comment by UntriexTv** [comment]
Thank you, this is actually great. I fixed the installer for RHEL 9, working on 8.
I tested Ubuntu, Debian, Fedora and Rhel8/9. Fedora was the only one that installed.
I'll take the changes you made and will implement mine.
Will it be okay to create pull request in the coming days?

**Comment by THS-on** [comment]
Definitely! Contributions to improve the installer are very welcome.

**Comment by UntriexTv** [comment]
This should fix RHEL8, didn't test RHEL7 yet, but I think there was still problem somewhere.
Worked on this for little while so also took this as opportunity to organize the code.
Could not test distributions anolis and alinux as I didn't find installer for them.
