### ISSUE TITLE
Can AMD's SEV and Intel's SGX be put into use?

### ISSUE THREAD

**Issue by webfast7** [keylime/keylime#1679]
Hello, I saw in the 2024 Q1 and Q2 plans on https://github.com/keylime/keylime/blob/master/ROADMAP.md that there will be support for Intel SGX and AMD SEV, not limited to TPM. Is the current version already ready for use?

**Comment by ansasaki** [comment]
> Hello, I saw in the 2024 Q1 and Q2 plans on https://github.com/keylime/keylime/blob/master/ROADMAP.md that there will be support for Intel SGX and AMD SEV, not limited to TPM. Is the current version already ready for use?

No, it has not been implemented yet.

To discuss and ask this kind of question, please join our #keylime slack channel at the CNCF instance: https://slack.cncf.io/
