### ISSUE TITLE
Failed adding agent with default config

### ISSUE THREAD

**Issue by UntriexTv** [keylime/keylime#1681]
# Environment
 * OS / version: Fedora
 * Processor architecture: X64
 * TPM Manufacturer: Proxmox virtual TPM
 * Keylime version: latest

# Description 
I am researching keylime and my first step is to get functional configuration.
I managed to overcome instalation problems and have rust agent and keylime running. But I have problem adding agent to verifier.

## Expected behavior vs. actual behavior 
After fresh install of keylime (with installer) and rust-keylime run everything in order. It generates certificates and no errors are present.
After running `keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u 309fd0a3-d552-48a0-a744-b513f27c7883`
the output is: 
```
root@localhost:~# keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u 309fd0a3-d552-48a0-a744-b513f27c7883
INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
2024-10-09 17:37:07.930 - keylime.config - INFO - Reading configuration from ['/etc/keylime/tenant.conf']
2024-10-09 17:37:07.930 - keylime.tenant - INFO - Setting up client TLS...
2024-10-09 17:37:07.930 - keylime.tenant - INFO - Using default client_cert option for tenant
2024-10-09 17:37:07.930 - keylime.tenant - INFO - Using default client_key option for tenant
2024-10-09 17:37:07.930 - keylime.tenant - INFO - No value provided in client_key_password option for tenant, assuming the key is unencrypted
2024-10-09 17:37:07.940 - keylime.tenant - INFO - TLS is enabled.
2024-10-09 17:37:08.040 - keylime.cli.policies - INFO - TPM PCR Mask from policy is 0x0
{'code': 200, 'status': 'Success', 'results': {'quote': 'r/1RDR4AYACIAC+GGefanRCWtIdIgB3isCIaYVMJsN+fixhqFJpCIp6O+ABRkamRPTlhvREFDUTN3Tkl3M2dvTgAAAAAASs5mAAAABAAAAAABIBkQIwAWNjYAAAABAAsDAAABACBT/RhG3WyoSg5GW/jamPF+F7xccYapvmP16S33HKnmfA==:ABQACwEAFiNOKuF4N3XvkO6rP3utS4PKz/3WoJW/njGqlWNVHqlvdXdmk8ETvY57o/Whk4WcsR/39jUba6nHA4v4h2muzE++BxOGhokMi1dwwh1fj+DZvejlUQVx7y8t6Y3lMvu11YoHLr04ICCnprWRCXTfR6Io2J0eLgrDSCMMNwgeMt8xYxK75xGSMeawYTHfvHUhxN3ephl7iI1p8QSVySJfqPUsLXIs4Kuu4agNfy92ewcKCQ5fd/FnkidZwiTDp4q8JksHUej67PdxNRrAi2RLmmw9jKoKhVLk/KEqzKjvC8TPiqqSBm9kD2WA7OpfKNfoXQ41K0w9CZ30azJQlMwCoQ==:AQAAAAsAAwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAgAPcbYq9lRNNJVQPD36xGI7P5xgFRykofUt9L1kT/TDApAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=', 'hash_alg': 'sha256', 'enc_alg': 'rsa', 'sign_alg': 'rsassa', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxGBP+EfnBDXSLYmOd4u/\n7mUTCuAo1cxJqUN1DRsnu4jNpdQQqWByuL54/5MUDMj8DNkrbAOQGuDg0UWNA9OW\n45Mm5QCrWzygftGqhrIUxOp+eeTzfdulZ9IGrlcK1SbyR8B+Zh1ppqUYOHYwRUhV\nlCNGxyafkWNOcsgSeTY+4X5ki2eWFy6vouvMyhpFdsp1mKeCGP7cPWP7FHH/DyPu\nfeGiX7GppKiwO5eG0z8145vRGF+0baKRxlaASItPeg5tn3/N53zpqBVHGQzdZ35T\nhMK7cudU6BbTQNKCs+Mjvxq1zR+NOWSx9N/qzfDk7ElcY7APbnxEFTdUDc4MPAEg\nswIDAQAB\n-----END PUBLIC KEY-----\n'}}
2024-10-09 17:37:08.322 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.324 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.326 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.328 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.330 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.332 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.334 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
2024-10-09 17:37:08.336 - keylime.cert_utils - ERROR - No Root CA matched EK Certificate
2024-10-09 17:37:08.336 - keylime.tenant - WARNING - Invalid EK certificate for Agent 309fd0a3-d552-48a0-a744-b513f27c7883 (127.0.0.1:9002)
2024-10-09 17:37:08.336 - keylime.tenant - ERROR - TPM Quote from Agent 309fd0a3-d552-48a0-a744-b513f27c7883 (127.0.0.1:9002) is invalid for nonce: djdONXoDACQ3wNIw3goN
```
With no change in verifier.

I tried with different UUID in agent too.

**Comment by ansasaki** [comment]
> # Environment
> 
>     * OS / version: Fedora
> 
>     * Processor architecture: X64
> 
>     * TPM Manufacturer: Proxmox virtual TPM
> 
>     * Keylime version: latest
> 
> 
> # Description
> 
> I am researching keylime and my first step is to get functional configuration. I managed to overcome instalation problems and have rust agent and keylime running. But I have problem adding agent to verifier.
> ## Expected behavior vs. actual behavior
> 
> After fresh install of keylime (with installer) and rust-keylime run everything in order. It generates certificates and no errors are present. After running `keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u 309fd0a3-d552-48a0-a744-b513f27c7883` the output is:
> 
> ```
> root@localhost:~# keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u 309fd0a3-d552-48a0-a744-b513f27c7883
> INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
> 2024-10-09 17:37:07.930 - keylime.config - INFO - Reading configuration from ['/etc/keylime/tenant.conf']
> 2024-10-09 17:37:07.930 - keylime.tenant - INFO - Setting up client TLS...
> 2024-10-09 17:37:07.930 - keylime.tenant - INFO - Using default client_cert option for tenant
> 2024-10-09 17:37:07.930 - keylime.tenant - INFO - Using default client_key option for tenant
> 2024-10-09 17:37:07.930 - keylime.tenant - INFO - No value provided in client_key_password option for tenant, assuming the key is unencrypted
> 2024-10-09 17:37:07.940 - keylime.tenant - INFO - TLS is enabled.
> 2024-10-09 17:37:08.040 - keylime.cli.policies - INFO - TPM PCR Mask from policy is 0x0
> {'code': 200, 'status': 'Success', 'results': {'quote': 'r/1RDR4AYACIAC+GGefanRCWtIdIgB3isCIaYVMJsN+fixhqFJpCIp6O+ABRkamRPTlhvREFDUTN3Tkl3M2dvTgAAAAAASs5mAAAABAAAAAABIBkQIwAWNjYAAAABAAsDAAABACBT/RhG3WyoSg5GW/jamPF+F7xccYapvmP16S33HKnmfA==:ABQACwEAFiNOKuF4N3XvkO6rP3utS4PKz/3WoJW/njGqlWNVHqlvdXdmk8ETvY57o/Whk4WcsR/39jUba6nHA4v4h2muzE++BxOGhokMi1dwwh1fj+DZvejlUQVx7y8t6Y3lMvu11YoHLr04ICCnprWRCXTfR6Io2J0eLgrDSCMMNwgeMt8xYxK75xGSMeawYTHfvHUhxN3ephl7iI1p8QSVySJfqPUsLXIs4Kuu4agNfy92ewcKCQ5fd/FnkidZwiTDp4q8JksHUej67PdxNRrAi2RLmmw9jKoKhVLk/KEqzKjvC8TPiqqSBm9kD2WA7OpfKNfoXQ41K0w9CZ30azJQlMwCoQ==:AQAAAAsAAwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAgAPcbYq9lRNNJVQPD36xGI7P5xgFRykofUt9L1kT/TDApAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=', 'hash_alg': 'sha256', 'enc_alg': 'rsa', 'sign_alg': 'rsassa', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxGBP+EfnBDXSLYmOd4u/\n7mUTCuAo1cxJqUN1DRsnu4jNpdQQqWByuL54/5MUDMj8DNkrbAOQGuDg0UWNA9OW\n45Mm5QCrWzygftGqhrIUxOp+eeTzfdulZ9IGrlcK1SbyR8B+Zh1ppqUYOHYwRUhV\nlCNGxyafkWNOcsgSeTY+4X5ki2eWFy6vouvMyhpFdsp1mKeCGP7cPWP7FHH/DyPu\nfeGiX7GppKiwO5eG0z8145vRGF+0baKRxlaASItPeg5tn3/N53zpqBVHGQzdZ35T\nhMK7cudU6BbTQNKCs+Mjvxq1zR+NOWSx9N/qzfDk7ElcY7APbnxEFTdUDc4MPAEg\nswIDAQAB\n-----END PUBLIC KEY-----\n'}}
> 2024-10-09 17:37:08.322 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.324 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.326 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.328 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.330 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.332 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.334 - keylime.cert_utils - WARNING - Failed to parse PEM data with python-cryptography (might not be strictly conforming to DER ASN.1 encoding): error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["Certificate::tbs_cert", "TbsCertificate::issuer", 0, 2] }
> 2024-10-09 17:37:08.336 - keylime.cert_utils - ERROR - No Root CA matched EK Certificate
> 2024-10-09 17:37:08.336 - keylime.tenant - WARNING - Invalid EK certificate for Agent 309fd0a3-d552-48a0-a744-b513f27c7883 (127.0.0.1:9002)
> 2024-10-09 17:37:08.336 - keylime.tenant - ERROR - TPM Quote from Agent 309fd0a3-d552-48a0-a744-b513f27c7883 (127.0.0.1:9002) is invalid for nonce: djdONXoDACQ3wNIw3goN
> ```
> 
> With no change in verifier.
> 
> I tried with different UUID in agent too.

Looking at the log you attached, it seems you did not add the EK certificate root CA to the trust store (by default it should be placed at `/var/lib/keylime/tpm_cert_store`) on the machine that is running the `keylime_tenant`.

We have some CA certificates from some TPM manufacturers that we use by default. If you are using a hardware TPM, it means we do not have the CA certificate from your TPM vendor. If you are using a vTPM, then you need to add the CA certificate manually to the trust store.

If you just want to test if your setup is working regardless of the validity of the EK certificate (BEWARE, this is INSECURE), you can disable EK certificate verification on the tenant by setting the `require_ek_cert` to `False` in the `/etc/keylime/tenant.conf` or alternatively simply overriding it by setting the env var `KEYLIME_TENANT_REQUIRE_EK_CERT=False`.

Please, prefer asking this kind of question on our `#keylime` slack channel on CNCF instance: https://slack.cncf.io/
