### ISSUE TITLE
Port warning over 8992

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#171]
This issue may be invalid, as I have yet to fully investigate, but I want to get this noted and recorded.

Quite a lot of folks are going to try out Keylime in a single VM (running everything over localhost).

If you do this, revocation won't work - yet there will be no warning of this.

For example when you start the verifier, it spawns a port on 8992 as does the agent, you then end up with the following:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8992            0.0.0.0:*               LISTEN      6780/python3        
tcp        0      0 127.0.0.1:38562         127.0.0.1:8992          ESTABLISHED 6798/python3        
tcp        0      0 127.0.0.1:8992          127.0.0.1:38562         ESTABLISHED 6780/python3 
```

I believe this may cause an issue for revocation messages being broadcasted? 

@nabilschear , am I making sense or onto something here, or is this misguided?

**Comment by nabilschear** [comment]
i think this is ok.  the verifier is the one listening, then the agent connects.  If revocations aren't working, there may be some other reason.  Overall, I did look at this for making the error handling a bit better for when zmq isn't working.  it's going to be more complicated, but perhaps for this reason and others, we should consider doing it.
