### ISSUE TITLE
openssl as default

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#173]
Packaging efforts are underway and by default they install without go installing cfssl

With this in mind, I have been thinking for a while we should use `openssl` as the default. If we also consider issue #145 it makes even more sense.

@nabilschear @jetwhiz any concerns about this or views?

**Comment by nabilschear** [comment]
openssl doesn't support certificate revocation.  that's the main difference.  there's no interface to creating a CRL in m2crypto (last i checked)

**Comment by lukehinds** [comment]
understood @nabilschear , so I am very much up for enabling folk to set up revocation which we could do in docs, but taking the long term view, with most likely to use a package installer (deb / rpm) for keylime, we need something that works out of the box for an initial install. From there they chose a backend as per #145 

If we install cfssl as an rpm dependency and `go get` the project, we are being opinionated on what they should use. I guess the same could be said about `openssl`, its just that openssl is a bog standard OS package on all systems.

**Comment by nabilschear** [comment]
another option is to see if this would work https://github.com/wbond/crlbuilder/blob/master/docs/readme.md
