### ISSUE TITLE
Track upstream tpm2-tools versions and handling

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#187]
So we are now often hitting issues with non backward compat changes upstream.

At the moment we check for certain commands being available, but we are going to need to be more specific, for example

https://github.com/keylime/keylime/blob/1cf9add6ecf9dd2b5e438bc099f2e1aa2db594a1/keylime/tpm2.py#L428-L432

The above will break on 4.0 now, as `-o` is no longer present as an arg:

```
tpm2_changeauth -c owner newpass
              tpm2_changeauth -c endorsement newpass
              tpm2_changeauth -c lockout newpass
```

I recommend we instead grab the version string, as follows:

```
tpm2_getrandom --version                                                             
    tool="tpm2_getrandom" version="3.2.0" tctis="dynamic" tcti-default=tabrmd dlclose=enabled
```

We can then build a matrix of command syntax to use, and hopefull upstream will stop renaming args and depreciating commands so frequently. 

We also need to have a table showing tools support  (like we did for the OS versions for the installer).

**Comment by jetwhiz** [comment]
Would it be better to target the tpm2-tools `4.x` branch instead of `master`, that way we're targeting something more stable than their `master` branch (which often pushes API-breaking changes)?  

I expect `4.x` is stable now that it is an official release.

**Comment by lukehinds** [comment]
Hi @jetwhiz , would 4.0 be the same as 4.x?

I am happy to go with whatever you feel is the better approach and give us good coverage. Please go ahead and make recommendations as you have a better handle on this then me.

4.0 is the version now in Fedora rawhide / 32 which is where Keylime packaging will initially land. 

I have some code now to really allow us to home in on specific releases or using `<=` or `>=` using `distutils.version.LooseVersion` and `distutils.version.StrictVersion`

**Comment by lukehinds** [comment]
These are the current versions:

| Dist        | tools-version |
| ------------- |:-------------:|
| Fedora 30 | 3.2.0 |
| Fedora 31 | 3.2.0 |
| Fedora 32 | 4.0-1 |
| CentOS 8 | 3.1.1 |
| RHEL 8 | 3.1.1 |

**Comment by jetwhiz** [comment]
It looks like they don't even have a `4.X` branch yet, so I assume they're just using `master` as the staging area for `4.X` for now.
