### ISSUE TITLE
Keylime Raspbian Support

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#190]
To configure tpm2-software see [here](https://lukehinds.com/2019/09/20/tpm-software-on-a-raspberry-pi-3-model-b-with-infineon-optiga-slb-9670-tpm-2-0/)

For IMA to work, it needs to be enabled in the Kernel;

```
CONFIG_IMA=y
CONFIG_IMA_MEASURE_PCR_IDX=10
CONFIG_IMA_LSM_RULES=y
# CONFIG_IMA_TEMPLATE is not set
CONFIG_IMA_NG_TEMPLATE=y
# CONFIG_IMA_SIG_TEMPLATE is not set
CONFIG_IMA_DEFAULT_TEMPLATE="ima-ng"
CONFIG_IMA_DEFAULT_HASH_SHA1=y #
# CONFIG_IMA_DEFAULT_HASH_SHA256 is not set
CONFIG_IMA_DEFAULT_HASH="sha1"
CONFIG_IMA_WRITE_POLICY=y
CONFIG_IMA_READ_POLICY=y
# CONFIG_IMA_APPRAISE is not set
CONFIG_IMA_KEYRINGS_PERMIT_SIGNED_BY_BUILTIN_OR_SECONDARY=y
```

**Comment by sardasanat** [comment]
I added the above assertions to .config to enable IMA, cross-compiled.  How do I proceed to install  keylime ?

**Comment by lukehinds** [comment]
Which OS / dist did you use?

**Comment by sardasanat** [comment]
Cross-compiled on Ubuntu 16.04.  Using Stretch on rpi . Although, mount -t securityfs security /sys/kernel/security  gives error, so I think IMA is not enabled correctlyon Rpi. Presently doing manual install of keylime. Small query, does keylime support only python >3.6 as mentioned in git or 2.7 ( as mentioned in doc) as after install when running verifier, gives  import error of missing modules (e.g asyncio, configparser)

**Comment by lukehinds** [comment]
hi @sardasanat , we are on Python 3.6 &> now with Python 2 support depreciated. The Python2 branch is still available though (just not supported going forward).

**Comment by lukehinds** [comment]
actually , it might be just a case of needing your ima-policy in place.

Try putting https://github.com/keylime/keylime/blob/master/demo/ima-policy into etc ( so `/etc/ima-policy`) and rebooting the machine, we should then see a securityfs (`/sys/kernel/security/ima ascii_runtime_measurements`)

**Comment by lukehinds** [comment]
@sardasanat any luck? I am trying to get this to work as well, so if you have had any success - please update.

**Comment by sardasanat** [comment]
> @sardasanat any luck? I am trying to get this to work as well, so if you have had any success - please update.

Hey @lukehinds sorry for late reply. I actually got working on TPU board with mendel linux for urgent task next 3 weeks so had to keep rpi dev on hold. (later I want to try keylime on TPU). I too thought I need to put ima policy (thanks for same), as when, I will try and update on it. Btw, I recollect, also had trouble installing keylime on rpi, as I thought just to try out payload encryption/attestation  feature (without ima). I recollect had done a manual keylime install, which took few tries to get installed ( albeit syntax errors in its logs ( (I would post those once I reproduce), but the verifier or agent doesnt install. In case you have remarks/steps on keylime manual install on rpi (without ima) would be useful to know. Also just small query 1) am using master version of tss, abrmd, tools. Does keylime support master or as in your post only the specific versions ?

**Comment by lukehinds** [comment]
hi @sardasanat , got it working this side as well.

I am going to play with this some more and then put up a patch to support pi3 in the installer.sh script.

Watch this space.

Any feedback on how it goes with the PTU board would be wonderful, thanks!

**Comment by lukehinds** [comment]
spoke to soon.

I have an issue with IMA not extending into PCR 10.

**Comment by lukehinds** [comment]
@sardasanat  we need this fixed upstream https://github.com/raspberrypi/linux/issues/3291

**Comment by sardasanat** [comment]
@lukehinds thanks. Between, can still use with TPM simulator for dev?

**Comment by lukehinds** [comment]
Yes you can, we have an ima_emulator service you can use as well

**Comment by lukehinds** [comment]
upstream patch: https://github.com/raspberrypi/linux/pull/3297

**Comment by lukehinds** [comment]
@jetwhiz I have IMA working now with the above Kernel patch, I am posting this issue in case you have seen it before:

```
root@raspberrypi:~/keylime# keylime_agent 
Using config file /etc/keylime.conf
2019-10-22 13:46:03.250 - keylime.tpm2 - INFO - Using legacy version of tpm2-tools
WARN: More data to be queried: capability: 0x6, property: 0x100

2019-10-22 13:46:03.458 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2019-10-22 13:46:03.710 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2019-10-22 13:46:03.711 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81010007
2019-10-22 13:46:04.312 - keylime.tpm2 - INFO - Flushing old ak handle: 0x81010008
2019-10-22 13:46:05.598 - keylime.cloudagent - INFO - Agent UUID: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2019-10-22 13:46:05.718 - keylime.registrar_client - INFO - Agent registration requested for D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2019-10-22 13:46:06.151 - keylime.tpm2 - INFO - AIK activated.
2019-10-22 13:46:06.159 - keylime.registrar_client - ERROR - Error: unexpected http response code from Registrar Server: 400
2019-10-22 13:46:06.160 - keylime.registrar_client - ERROR - Response code 400: Error: Auth tag c8fb3e8626608838413616bbe52fe2fcf9fc1212f54042bc54ad7baf996aaf236135d37861ddd8b662a565604b09344e does not match expected value 6f8d0b8a7521dd3187e8d7a3d4bdea76050071c5cd872722b00cc1f297e86947e6cf717c55c62c8794f70317661d73bd
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/local/lib/python3.7/dist-packages/keylime-1.2-py3.7.egg/keylime/cloud_agent.py", line 549, in main
    raise Exception("Registration failed on activate")
Exception: Registration failed on activate
```
