### ISSUE TITLE
cloudagent_ip

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#191]
A `cloudagent_ip` value will be needed for the rust agent when PR https://github.com/keylime/rust-keylime/pull/77 mergers

**Comment by lukehinds** [comment]
For anyone wanting a first issue, this just requires the following line added to `keylime.conf`

`cloudagent_ip = 127.0.0.1`

Just above line 10:

https://github.com/keylime/keylime/blob/master/keylime.conf#L10

**Comment by rajdroid** [comment]
Would love to help

**Comment by lukehinds** [comment]
awesome @rajdroid - I will sponsor you for this first issue. 

I recommend reading https://github.com/keylime/keylime/blob/master/CONTRIBUTORS.md

On how to make a pull request etc. 

You can test your code out within a VM using our Ansible Role here https://github.com/keylime/ansible-keylime-tpm-emulator/

We need a couple of small additions to the above https://github.com/keylime/keylime/issues/191#issuecomment-545394845

We need to enter the configparser call for `cloudagent_ip` here:

https://github.com/keylime/keylime/blob/a5dc201a322c0f490d52cc08cebcef4ae8f4a208/keylime/cloud_agent.py#L551

And add the IP to the logging line to show the agent server started:

https://github.com/keylime/keylime/blob/a5dc201a322c0f490d52cc08cebcef4ae8f4a208/keylime/cloud_agent.py#L555

If possible, please also change this to [f-string format](https://realpython.com/python-f-strings/) 

Once you make the pull request add me as a reviewer please!

If you get stuck, I put the changes in the following gist, but you're welcome to find your own way of doing this if you like. 

last of all, here is the full change in a gist: 

https://gist.github.com/lukehinds/b9aaf207ae7c5725b71a6a26031d92e5

Let me know if you need help with anything and welcome to the community!

**Comment by lukehinds** [comment]
`keylime_agent` will be the CLI command to start the server and test your `cloudagent_ip`

You will need `keylime_verifier` and `keylime_registrar` running first. You can run them in seperate terminal sessions and then use <CTRL-C> to break out.

**Comment by rajdroid** [comment]
Thanks @lukehinds, I will go over the resources.

**Comment by rajdroid** [comment]
Hi @lukehinds, I was trying to create the development setup on my ubuntu guest over the ubuntu host. I used the installer.sh script with args "-s -m". The `keylime_verifier` and `keylime_registrar` started without any issue, but when I start `keylime_agent` it throws an error. Could you please point me where I can get an answer to these questions.

**Comment by lukehinds** [comment]
Hi @rajdroid 

I would recommend you use the ansible emulator role:

https://github.com/keylime/ansible-keylime-tpm-emulator

Just clone this role, install vagrant and run the following:

`vagrant --repo=/home/raj/keylime up --provider libvirt --provision`

Note `--provider` would be either `libvirt` or `vitualbox` - depending on which you use with vargant

`--repo` would be the folder containing your keylime code

You can then do the following:

1. Connect to the machine.
`vagrant ssh`
2. Chnage to root user
`sudo su -`
3. A from the keylime directory mounted via `--repo` install keylime
`python3 setup.py install`

You can then run `keylime_verifier` `keylime_registrar` and `keylime_agent`

ping me on gitter if you hit any issues and happy to help.

**Comment by rajdroid** [comment]
@lukehinds I have added a pull request. Could you please review.

**Comment by rajdroid** [comment]
@lukehinds I think we can close this. I forgot to add **resolve** in my commit message.

**Comment by lukehinds** [comment]
Thanks @rajdroid
