### ISSUE TITLE
Multi-Verifier testing

### ISSUE THREAD

**Issue by cjustacoder** [keylime/keylime#201]
# What has been done:
https://github.com/cjustacoder/keylime/tree/multi-verfier
## for the tenant side: 
- be able to send the request to the provider after getting a quote from its own agent
	- using the GET method to send the request to provider side endpoint
- can get provider quote only once, then enter attestation loop 

## for provider side:
- develop an endpoint `/verifier?nonce=%s&mask=%s&vmask=%s` to receive and handle the request from tenant
- be able to forward these parameters to agent api `/quotes/integrity?nonce=%s&mask=%s&vmask=%s&partial=%s` 
	- using the GET method to send a request to provider agent
- be able to get a quote from provider agent

# Problem: 
- can't forward the quote from provider verifier to tenant verifier, have trouble with proxy things

## Location:
https://github.com/cjustacoder/keylime/blob/0252e67b81ef1a28ae0674987f17da1d3ba6c6f5/keylime/cloud_verifier_tornado.py#L159
https://github.com/cjustacoder/keylime/blob/0252e67b81ef1a28ae0674987f17da1d3ba6c6f5/keylime/cloud_verifier_tornado.py#L421

## Detail:
![graph_representation](https://github.com/cjustacoder/transfer/blob/master/img/Question.png)
From my understanding, when invoking Rest APIs, API can send a response through `common.echo_json_response`. Then the part which sends this request will handle this response inside callback function like `client.fetch(url, callback=cb)`. 
Now I'm inside the callback function in provider verifier, which processes the response from provider agent (the provider quote). I want to send response back to tenant verifier, but `common.echo_json_response` doesn't work inside the callback function. How can I send these content in response to the tenant verifier GET request? 

# How to run the code:
1. Run a full set of keylime instance for provider
	- set cloud_verifier_tornado.py L262 `d['need_provider_quote'] = False` before run the code. https://github.com/cjustacoder/keylime/blob/0252e67b81ef1a28ae0674987f17da1d3ba6c6f5/keylime/cloud_verifier_tornado.py#L262
2. Run a full set of keylime instance for tenant
	- set cloud_verifier_tornado.py L262 `d['need_provider_quote'] = True` before run the code. https://github.com/cjustacoder/keylime/blob/0252e67b81ef1a28ae0674987f17da1d3ba6c6f5/keylime/cloud_verifier_tornado.py#L262	

	- hard coding the provider ip address and port https://github.com/cjustacoder/keylime/blob/0252e67b81ef1a28ae0674987f17da1d3ba6c6f5/keylime/cloud_verifier_tornado.py#L409

# What's the behavior of the code
After provision the tenant agent from tenant's `tenant terminal`, you can see the quote which requests by tenant verifier in the provider's `verifier terminal` ![provider_verifier](https://github.com/cjustacoder/transfer/blob/master/img/provider_verifier.PNG). But in the tenant's `verifier terminal`, you can see there is nothing in response. ![tenant_verifier](https://github.com/cjustacoder/transfer/blob/master/img/tenant_verifier.PNG)

@lukehinds @nabilschear Thank you very much! 

Btw, is this framework applicable and match your expectations @nabilschear?

**Comment by cjustacoder** [comment]
Another thing, I always get `2019-11-07 02:19:32.588 - keylime.tenant - ERROR - Timed out waiting for delete of agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000 to complete at CV` when I delete the agent. Though I can solve this by deleting it again, is there any decent way to solve this?

**Comment by nabilschear** [comment]
i'm looking at this today @cjustacoder

**Comment by nabilschear** [comment]
So, i think that using the away/ensure_future method will be better for this.  Usually all the verifier actions on a REST call to one of its interfaces are all asynchronous.  But getting a quote isn't.  So, I think that you'll need to await the async http client request and the retrn the result to the original caller (the one who talked to the provider verifier)

**Comment by cjustacoder** [comment]
Thanks a lot, @nabilschear , I will continue working under this framework, I think the proxy issue will be solved under this structure.
