### ISSUE TITLE
TPM1.2 Naming "AIK" used in tpm2.py

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#213]
`2019-11-18 08:38:30.539 - keylime.tpm2 - INFO - AIK activated.`

I think this should be `AK activated.` now for TPM 2.0?

**Comment by jetwhiz** [comment]
Attestation Key (AK) seems to be more official, though confusingly the TCG specifications still sometimes use the term "AIK" for the TPM 2.0. 

For instance: https://trustedcomputinggroup.org/wp-content/uploads/TCG-TPM-v2.0-Provisioning-Guidance-Published-v1r1.pdf (page 31)
> Create a restricted signing key (a.k.a. Attestation Identity Key or AIK) and certify it for use to re-port (attest) PCR values. (PRE + OS).

**Comment by lukehinds** [comment]
interesting, bigger fish to fry for now, so we can park this.

**Comment by nabilschear** [comment]
certainly for log messages specific to TPM2, we can use AK.  But i wouldn't refactor the code to remove instances of AIK
