### ISSUE TITLE
Move to using files for EK CA manufactorer certificates

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#218]
Move to use .pem files in a certificates/ directory instead of the current `tpm_ek_ca.py`

This way users can add their own intermediary / root certs for EK trust and not have to edit code (which will be installed at `/usr/local/lib/python3.7/site-packages/` and so wiped out everytime an upgrade occurs.

**Comment by lukehinds** [comment]
@amylily1011 , you might like this one. Its a nice secluded bit of code so you won't have to manage lots of merge conflicts. Let me know if it interests you and we can walk over an approach when we next meet.

**Comment by amylily1011** [comment]
@lukehinds Yes yes, please :-)
