### ISSUE TITLE
Agent consuming excessive CPU during / after IMA measurement

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#223]
# Environment
 * OS / version: Fedora 31
 * Processor architecture:  VM
 * TPM Manufacturer:  Emulator
 * Keylime version: master

# Description 

Some CPU spikes have been observed up to 100%

This continues even after changing the agents operation status to deleted. Only way to stop is to ctrl break the agent.

## Steps to reproduce problem
1. Provision with the following as an example:
`keylime_tenant -t 127.0.0.1 -v 127.0.0.1 --cert /root/democa --exclude /root/excludes.txt --whitelist /root/whitelist.txt --include /root/payload -c add`

# Relevant logs

![](https://i.imgur.com/igRcE4O.png)

**Comment by lukehinds** [comment]
Note: We should test this using different sizes of whitelists and if this proves conclusive , we should look into compression or the design of the WL handling.

**Comment by lukehinds** [comment]
Keep alive.

I think this issue need to morph into an investigation on how to better handle whitelists being iterated over and quieted in the database. It's going to be more of a performance enhancement, than a bug.

**Comment by rajdroid** [comment]
Hey @lukehinds, I can take a look at this one.

**Comment by lukehinds** [comment]
Thanks @rajdroid , it appears to be related to the whitelist size, my guess is we iterate over  in an expensive manner and that spikes resource usage - that is just speculation though, I have not had time to investigate much.

**Comment by droccom** [comment]
Is that the whitelist for IMA measurement? If yes, this is surprising to me, as I thought (based only on log interpretation) that the measurement/IMA matching was performed by the verifier and the agents simply sent the measurements. Did I get it wrong?

**Comment by lukehinds** [comment]
> Is that the whitelist for IMA verification? If yes, this is surprising to me, as I thought (based only on log interpretation) that the measurement/IMA matching was performed by the verifier and the agents simply sent the measurements. Did I get it wrong?

No, you're right @droccom , I have had a dim moment there and used the totally wrong wording. I am referring to handling of `ascii_runtime_measurements` and got mixed up with some work I wanted to do to optimize the verifier SQL queries involving large whitelists. 

So yes, the whitelist goes no where near the agent.

**Comment by droccom** [comment]
Thanks for clarifying!

**Comment by lukehinds** [comment]
@rajdroid any progress, how is it going?

**Comment by THS-on** [comment]
The Python agent is deprecated and will be removed, so it is unlikely this to get fixed.
