### ISSUE TITLE
Include agent hostname or UUID in verifer IMA log message

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#230]
The verifier currently states `Checking IMA measurement list...`

It would be good to some how pull in the hostname or UUID, as when several agents are being polled, the same message is repeated over and over, with no details on which target node is being measured.

https://github.com/keylime/keylime/blob/e2bfff7b1ebcaef9b3dec7d840f18133684e84bf/keylime/tpm_abstract.py#L327-L328

Something like:

`Checking IMA measurement list on agent: D432FBB3-D2F1-4A97-9EF7-75BD81C00000`

**Comment by rajdroid** [comment]
May I work on this @lukehinds?

**Comment by lukehinds** [comment]
Very much, thanks @rajdroid !

**Comment by rajdroid** [comment]
Hi @lukehinds, In normal test scenario with `keylime_registrar`, `keylime_verifier` and `keylime_agent`. I don't see this log message in the verifier. Am I missing something?

**Comment by lukehinds** [comment]
Ah yes, I will show you how to set this up. It might take me a day or two with Christmas tomorrow. In the meantime this blog post outlines the set up:

https://keylime-docs.readthedocs.io/en/latest/user_guide/runtime_ima.html

The difference is that you're using an TPM emulator in the virtual machine, so we need to emulate IMA extending into the TPM. You can do this (just before running `keylime_tenant -v 127.0.0.1 -t 127......') by starting the ima emulator:

`keylime_ima_emulator`

Give it a go, if you get stuck I can help you in here, or in a few days time I can send you a gist with all the steps.

**Comment by rajdroid** [comment]
Yeah no problem @lukehinds. Let me try this resource. If I stuck somewhere, I'll let you know.
And Merry Christmas

**Comment by lukehinds** [comment]
How did you get on @rajdroid ?

**Comment by rajdroid** [comment]
Didn't get a chance to work on it. I was on vacation. Will work on it from tomorrow.

**Comment by lukehinds** [comment]
No worries, in your own time. Wanted to see if you needed help still with getting the logging message to display.

**Comment by rajdroid** [comment]
I got the setup working. Now I'll take look at the code changes.

**Comment by lukehinds** [comment]
thanks @rajdroid I was looking at the code and it looks like quite a few functions will need to carry out agent_uuid value. let me know if you need some help at all.

**Comment by rajdroid** [comment]
yeah, you are right. I had to propagate agent_id from top functions to bottom one, but it's done. Currently testing it, will raise a review in some time.
