### ISSUE TITLE
payload is cached somewhere

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#244]
1. Provision a node using keylime_tenant with a payload using `--payload` or `--include` containing a local_actions script.

2. Fail the machine so that revocation occurs and local_actions run.

3. Delete the node using the keylime_tenant

4. Make an amendment to your local_action script.

5. Provision the node again the same as at step 1.

6. Fail the node

Result

The amendment in step 4 is not present when the script is executed. The local_action is cached somehow and not updated. 

The amendment is situated in secure/unzipped. For the amendment to be active, you need to restart the agent (ctrl-c)

This might be per design, so opening this for discussion. 

Any thoughts @jetwhiz ?

**Comment by jetwhiz** [comment]
Hi @lukehinds , 

This may be because you're resuming the node (bringing it back up after failure) instead of deleting the node and then provisioning it again.  

I think you either need to do `-c update` or do `-c delete` followed by `-c add` if you want to change what you've sent to the node.
