### ISSUE TITLE
Refactor IP / Ports

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#247]
refactor to a better layout and definition of ip's and ports. At the moment most are grouped in together at the top of the file, with no real outline on what is for connecting to a service and what is for a service to bind to. I will create another issue for this.

I have observed a few incorrect behaviours as well, for example for the -c delete command. This calls do_cvdelete which then http posts a DELETE to the verfifier, however it does not pass on the target IP. Instead it takes the IP from the config. Yet if you run the tenant command without a target IP ( -t), it fails. So its basically defining an arg as mandatory, yet not even using it.

```
keylime_tenant -v 127.0.0.1  -f excludes.txt --whitelist ~/whitelist.txt --exclude excludes.txt -c delete
Using config file /etc/keylime.conf
2019-12-22 09:07:36.581 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2019-12-22 09:07:36.582 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_tenant')()
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tenant.py", line 786, in main
    raise UserError("-t/--targethost is required for command %s"%args.command)
keylime.tenant.UserError: -t/--targethost is required for command delete
```

This issue can be for working out what requires changing, any new design considerations etc.

**Comment by lukehinds** [comment]
hey @rajdroid , will keep this open for now or if you prefer you can open a new bug for the '-c delete' quirk.

**Comment by rajdroid** [comment]
Yeah, no problem @lukehinds. I will fix that bug under this issue.
