### ISSUE TITLE
CI Fails on Fedora 31

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#271]
For some reason unknown as yet, setUpModulee.GreenTestSuite fails on Fedora 31 (issue not present on Fedora 30).

**Comment by elfosardo** [comment]
Hi!
I built a Fedora 31 image and I can see this error popping up when trying to get the TPM after starting the registrar:
`Exception: Command: tpm2_startup -c returned 1, expected 0, output [], stderr [b'
', b'** (process:238): CRITICAL **: 17:37:23.404: failed to allocate dbus proxy object: Could not connect: No such file or directory
', b'WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f92334dece0 failed with a0008 
', b'WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-abrmd 
', b'ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: tabrmd 
', b'ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
', b'ERROR: Could not load tcti, got: "tabrmd:bus_name=com.intel.tss2.Tabrmd"
']`

This is the full exception:
`Cloud Agent Thread
Using config file /etc/keylime.conf

2020-04-17 08:09:40.323 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 4.0.1

Traceback (most recent call last):

  File "/usr/local/bin/keylime_agent", line 11, in <module>

    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point

    return ep.load()

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load

    return self.resolve()

  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/cloud_agent.py", line 64, in <module>

    tpm = tpm_obj.getTPM(need_hw_tpm=True)

  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tpm_obj.py", line 88, in getTPM

    __tpm2 = tpm2.tpm2(need_hw_tpm)

  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tpm2.py", line 83, in __init__

    self.__startup_tpm()

  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tpm2.py", line 368, in __startup_tpm

    retDict = self.__run("tpm2_startup -c")

  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tpm2.py", line 295, in __run

    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s"%(cmd, code, expectedcode, retout, reterr))

Exception: Command: tpm2_startup -c returned 1, expected 0, output [], stderr [b'\n', b'** (process:238): CRITICAL **: 08:09:40.329: failed to allocate dbus proxy object: Could not connect: No such file or directory\n', b'WARNING:tcti:src/tss2-tcti/tctildr.c:62:tcti_from_init() TCTI init for function 0x7f8306969ce0 failed with a0008 \n', b'WARNING:tcti:src/tss2-tcti/tctildr.c:92:tcti_from_info() Could not initialize TCTI named: tcti-abrmd \n', b'ERROR:tcti:src/tss2-tcti/tctildr-dl.c:150:tcti_from_file() Could not initialize TCTI file: tabrmd \n', b'ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI \n', b'ERROR: Could not load tcti, got: "tabrmd:bus_name=com.intel.tss2.Tabrmd"\n']

`

**Comment by lukehinds** [comment]
Its all a bit embarrassing in CI at the moment and I think we need to revamp our approach. I feel I need to take a shower when I look over it :)

So for the issue you have there, might be due to the `tpm2-abrmd` service is not running. Take a look at the following section of the test wrapper script:

https://github.com/keylime/keylime/blob/db02ec8fdd9118b80d9cf38d34d6dca3fb625b73/.ci/test_wrapper.sh#L18-L21

What you could do is just run that entire script and hopefully that should have the tpm operational. It will also call `run_tests.sh` which calls the actual unit / functional tests.

That sets the service up and enables it to work with the tpm emulator. 

What I am seeing at the moment is the setUpModule is failing on Fedora 31 is failing, and I guess it must be related to the tpm setup

https://github.com/keylime/keylime/blob/master/test/test_restful.py#L152

I will try and take a look at it today, in the mean time if you're good with containers and getting them running unprivileged, feel free to take a stab at making things better! I am happy to jump in do co debug sessions or explain history / context of any given part.

**Comment by elfosardo** [comment]
@lukehinds  thanks for the reply!
I actually got that when running run_local.sh and testing tpm2, so when running test_wrapper.sh in the Fedora 31 container.
I'm seeing that failure in test_restful.py, in setUpModule, right after launch_registrar(), during the tpm variable assignment:
```
tpm = tpm_obj.getTPM(need_hw_tpm=True)
```
this should be here https://github.com/keylime/keylime/blob/master/test/test_restful.py#L198

**Comment by elfosardo** [comment]
I added a check for the status of tpm2-abrmd and I'm seeing this:
```
reated symlink /etc/systemd/system/multi-user.target.wants/tpm2-abrmd.service → /usr/lib/systemd/system/tpm2-abrmd.service.
Failed to start tpm2-abrmd.service: Unit systemd-udev-settle.service not found.
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
Copying keylime.conf into /etc/keylime.conf
```
Probably forgot something in the container image?
I'll keep looking

**Comment by elfosardo** [comment]
so I got the CI job to complete successfully in a Fedora 31 container
```
OK (passes=29, skips=3)
```
I'll put a PR up and see how that goes

**Comment by lukehinds** [comment]
awesome, thanks @elfosardo !
