### ISSUE TITLE
Keylime agent fails to start with latest version of `tmp2-tools`

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#272]
# Environment
 * OS / version: Ubuntu / 18.04.4
 * Processor architecture: Intel Xeon E312xx (Sandy Bridge)
 * TPM Manufacturer: SWTPM (https://github.com/stefanberger/swtpm)
 * Keylime version: 1.2
 * TPM2-Tools version: 4.2

# Description 
With the latest (top of git) version of `tpm2-tools`, keylime agent fails to start properly, due to the fact the initialization of the TPM module returns an error. The error seems easily identifiable. A change in the parameter on the `tpm2_createek` command line parameters, as demonstrated on the logs present here.

The main error message is: `Exception: createek failed with code 1: [b"tpm2_createek: invalid option -- 'p'\n"]`

It looks like the problem was introduced in `tpm2-tools` around the commit https://github.ibm.com/k8s4g/tpm2-tools/commit/6192d3cb100df526adc78a8764202547006e8139

Installing `tmp2-tools` with the commit id https://github.ibm.com/k8s4g/tpm2-tools/commit/c28932caef2036039901a91cf55eb7ff093c70f5 seems to be enough to restore functionality.

## Expected behavior vs. actual behavior 
Expected: keylime_agent is expected to start successfully
Actual: keylime_agent fails to run

## Steps to reproduce problem
1. Install (from git) the latest versions of `tpm2-tss` (https://github.com/tpm2-software/tpm2-tss.git), `tpm2-tools`(https://github.com/tpm2-software/tpm2-tools.git) and `tpm2-abrmd`(https://github.com/tpm2-software/tpm2-tools.git)
2. Install (from git) the latest version of Keylime.
3. Attempt to start the agent.

# Relevant logs
```
root@localhost:/keylime# keylime_agent
Using config file /etc/keylime.conf
2020-04-13 15:39:22.293 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 4.2
2020-04-13 15:39:22.418 - keylime.tpm - WARNING - INSECURE: Keylime is using a software TPM emulator rather than a real hardware TPM.
2020-04-13 15:39:22.419 - keylime.tpm - WARNING - INSECURE: The security of Keylime is NOT linked to a hardware root of trust.
2020-04-13 15:39:22.419 - keylime.tpm - WARNING - INSECURE: Only use Keylime in this mode for testing or debugging purposes.
2020-04-13 15:39:22.419 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2020-04-13 15:39:22.839 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/cloud_agent.py", line 491, in main
    (ek,ekcert,aik,ek_tpm,aik_name) = tpm.tpm_init(self_activate=False,config_pw=config.get('cloud_agent','tpm_ownerpassword')) # this tells initialize not to self activate the AIK
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/tpm2.py", line 907, in tpm_init
    self.__create_ek()
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/tpm2.py", line 439, in __create_ek
    raise Exception("createek failed with code "+str(code)+": "+str(reterr))
Exception: createek failed with code 1: [b"tpm2_createek: invalid option -- 'p'\n"]
root@css-flex14vm1:/KL# tpm2_createek -v
tool="tpm2_createek" version="4.2-9-g3d78881f" tctis="libtss2-tctildr" tcti-default=tcti-abrmd
```

Attach any relevant log files that can help to debug your issue.

**Comment by lukehinds** [comment]
Many thanks @maugustosilva for reporting and welcome to the KL community.

This should be an easy fix as we have comparison statements for tools versions

https://github.com/keylime/keylime/blob/110c4caa560786e0589a206990ec137b7b37cb57/keylime/tpm2.py#L428-L431

So we would need to work out what flag change has been made for `tpm2_createek` and then add a "4.2" clause.

Is this a pull request you would like to make?

**Comment by maugustosilva** [comment]
Perfect, will create a PR, thanks.

**Comment by lukehinds** [comment]
awesome, thanks.

Some general tips for a PR if you need them> https://github.com/keylime/keylime/blob/master/CONTRIBUTORS.md

**Comment by kaifeng** [comment]
Instead of comparing specific versions, maybe we can use version utilities to compare a range of them.

**Comment by maugustosilva** [comment]
I agree with the use of version utilities, but I am planning into investing more time doing it as part of a next PR, one with a proper "tpm2 version x command" map.
