### ISSUE TITLE
Add support for ECC in TPM 2.0

### ISSUE THREAD

**Issue by jetwhiz** [keylime/keylime#28]
Currently the TPM 2.0 implementation (and tpm2_tools) only supports RSA/RSASSA for encryption and signing.  Add full support, including ECC EK certificate fetching from NVRAM (or by generating it).

**Comment by lukehinds** [comment]
On a side note, once #127 is merged, we can start using ECC for certificate generation, signing etc:

**Comment by THS-on** [comment]
@sergio-correia with the ECC stuff in place for certificates, can you have a look at much is required to also enable it for the AK and EK?

**Comment by sergio-correia** [comment]
Sure, I can do that.
