### ISSUE TITLE
Investigate porting to github actions

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#295]
Would be useful to move to github actions eventually, but we might need to see whats possible first. 

using github actions we can pull in a container from our own registry for example [quay](https://github.com/enarx/enarx/blob/master/.github/workflows/automation-pr.yml)

This might need an [enhancement](https://github.com/lukehinds/enhancements) if its large enough

**Comment by lukehinds** [comment]
fancy a go at this @elfosardo when your plate is bit more clear?

**Comment by THS-on** [comment]
@mpeters the migration was done some time ago (https://github.com/keylime/enhancements/issues/18), so I think this can be closed.
