### ISSUE TITLE
Improve project layout

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#300]
This is a proposal to re-organize source codes logically grouped into separate directories, e.g.:
keylime/cmd for script entries
keylime/db for database model
keylime/common for common utilities
keylime/tpm for the tpm layer

This will make the repo more intuitive and further refactoring easier.

**Comment by kaifeng** [comment]
hmm, please assign

**Comment by kaifeng** [comment]
please assign

**Comment by lukehinds** [comment]
hi @kaifeng , sounds good and thanks for taking this on!

I think this might be a good work piece to do a quick enhancement proposal. 

https://github.com/keylime/enhancements

I would not be concerned with doing anything to lengthy or in-depth. Please add me as a reviewer as it would be nice to do some file renaming at the same time. 

For example we have `keylime_tenant` , but the file is called `cloud_agent` - I would like to deprecate all instances of `cloud` as Keylime is also well suited to edge and IoT.

**Comment by kaifeng** [comment]
Hey @lukehinds o/
you meant to create an issue in the keylime/enhancements? I have no idea how it will be connected to this repo, I was thinking iterating with multiple smaller patches under this issue.

**Comment by lukehinds** [comment]
hi @kaifeng 

It's a new process I would like to get into place for when the project gains momentum and more feature / change proposals arrive. This would be a nice chance for us to check over the process. 

All you would need to do is open an issue here: https://github.com/keylime/enhancements/issues/new/choose and then make a PR to the repo using the template.

You can see an example here:

issue: https://github.com/keylime/enhancements/issues/1
PR: https://github.com/keylime/enhancements/pull/2

The idea is the enhancement (proposal) is reviewed, then merged. Each time you then make a patch you reference the issue in keylime/enhancements  - as keylime and enhancements are in the same org, we can then track everything in the project 

I would not worry about doing a very in depth proposal, I would rather you not be held up from the doing work which is more important, so you could get started in a branch.

The good thing about enhancements is it allows me to track in the project board: https://github.com/orgs/keylime/projects/1 / https://i.imgur.com/r9kuHmS.png

Its much the same as a spec in openstack or a kubernetes enhancement proposal.

**Comment by kaifeng** [comment]
Got it, thanks for the info, I'll create a PR there.
