### ISSUE TITLE
reactivate command broken over type mismatch

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#310]
When running the `keylime_tenant` with `reactivate` the following stack trace occurs:

```
2020-05-12 09:32:34.709 - keylime.cloudverifier - ERROR - can only concatenate str (not "int") to str 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/keylime/cloud_verifier_tornado.py", line 499, in process_agent
    main_agent_operational_state = agent['operational_state']
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 3048, in __getitem__
    return list(self[item : item + 1])[0]  
TypeError: can only concatenate str (not "int") to str
```

The reason for this is because `agent` object is coming in a SQLAclhemy type and not a dict (or list?. So its not just as case of changing ` main_agent_operational_state = agent['operational_state']` to ` main_agent_operational_state = agent.operational_state`

If we do this, then the standard quote operation will fail

We might instead need to perform a type check and have a conditional to process accordingly.

Steps to recreate

1. Add an agent:
`keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f somefile.txt -c add`

2. Reactive
`keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f somefile.txt -c reactivate`

The above error will then throw.

**Comment by lukehinds** [comment]
@kaifeng are you interesting in taking this one on?

**Comment by kaifeng** [comment]
@lukehinds Hi o/
I am still get myself familiarized with the code, so not sure I can handle this, the bad side is my tpm environment crashed after a power shortage, and I am lacking a env to validate my change. After quickly browsing the code, it seems the agent was assumed to be a dictionary, so the change is likely a conversion at the entry of process_agent. The issue behind I think, is the lack of layer of database and serialization/deserialization upon it.

**Comment by lukehinds** [comment]
@kaifeng no worries, I can put in a fix with my auth patch. There are other means to achieve the same option is reactive

Regarding tpms, do you use the emulator?

**Comment by kaifeng** [comment]
I was using VM equipped with vtpm device, which is much like a real environment.

**Comment by lukehinds** [comment]
I am thinking we should move our gate over to using the vtpm, less set up steps.

**Comment by kaifeng** [comment]
I made a patch for this, hope that works.

**Comment by kaifeng** [comment]
> I am thinking we should move our gate over to using the vtpm, less set up steps.

Yep, vtpm make things easier, I don't know if travis support virtual machines, it will cost quite a lot of resources.
