### ISSUE TITLE
Keylime agent should be capable of simply using the already created EK in a TPM

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#313]
# Description 
During startup, `keylime_agent` is pretty forceful and uncompromising on "taking over" the TPM device, including a "startup & clear (`tpm2_startup -c`), "change owner, endorsement and lockout authorizations" (`tpm2_changeauth`) and "generate a new Endorsement Key" (`tpm2_createek`). This means that, when the agent submits an EK to registrar, there isn't a specific way for an administrator to tie a particular (EK) to a specific piece of hardware (e.g., whose "chain of provenance" started at a factory, and included an "air-gapped boot measurement station" before going into production). 

I would like explore and discuss the possibility of changing keylime to allow a "primed" TPM to be controlled by the `keylime_agent`. Almost needless to say, this would be an optional behavior controlled by a new configuration parameter. In this scenario, the agent would query the TPM and simply use the pre-existing EK (which was created beforehand by some other method). The plan here wouldn't require us to *prevent* the `keylime_registrar` from recording any EK submitted (as it is today), but rather to make the (`tenant`-side) script `ek_check_script` to be able to check the EK against a list of properly pre-defined (and previously collected) values.

# Goal
Add a new `keylime.conf` option under `[cloud_agent]` specifying `reinitialize_tpm=True|False`

Am I off the mark here, or is there a specific, real-world, use case such as described?

**Comment by lukehinds** [comment]
hi @maugustosilva 

Just a cursory note for now and will reply in full at a later point.

There are quite a few synergies with the following enhancement:

https://github.com/keylime/enhancements/blob/29be79363f96c7c622497bffb22f87003ce835be/1_persist_agent_restart.md

I wonder if we could combine both.

My initial thoughts are I am open to this and see it as a valid case, but we should also try to keep the current approach as an option for a user who is getting a new machine and wants to be sure its refreshed for their use.

**Comment by maugustosilva** [comment]
@lukehinds apologies for not responding sooner. I have read the document, and I believe I understand your requirements. It looks like that the basic logic in `tpm2.py` for both cases will be exactly the same, with the only difference being the criterion to decide when to use the already created EK (should we preserve AIK too?): in my case, it will be if a given flag is found on `keylime.conf`, in yours, it is base on a result from an early REST GET call. Do you agree?
