### ISSUE TITLE
Rename whitelists

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#324]
So I have been thinking in the spirit of actions such as the following below, we should rename whitelists

https://www.bbc.co.uk/news/technology-53050955

Anyone have any ideas on a new naming convention?

**Comment by jberkus** [comment]
"allowlist" is the most popular replacement from what I've seen on other projects.

Of course, you want at term that's accurate for what the object actually *does*.  Don't drop one vaguely misleading term for another vaguely misleading term.  For example, one project adopted "coverageFilter" because that was actually more appropriate for the structure.

**Comment by lukehinds** [comment]
@jberkus , thanks! You got me thinking, and I may have something which matches closer to the functionality it covers.

`--ima-list`

The former whitelist, is a list of files that will be monitored by IMA (Integrity Measurement Architecture)

**Comment by font** [comment]
I like `--ima-list` as well. Perhaps combine both with:

`--ima-allowed-list`

**Comment by axelsimon** [comment]
I agree with @font it makes sense to use this opportunity to move to a term as descriptive as possible.

An alternative to `--ima-allowed-list` (which a strong advantage of having "allowed" in the term, which sticks with the "allowlist" as a growing replacement for whitelist) could be `--ima-monitored-list`.

Let me know!

**Comment by lukehinds** [comment]
I am ok with that, we should just make sure we have a shorthand flag, as its a lot to type out.

I think while we are at it, it might make sense to change `--excludes` to `--ima-exclude-list`

**Comment by lukehinds** [comment]
hey @mpeters , I wonder if it makes sense to do this change at the same time as you implement the allow lists (I guess your change would already cover this?)

**Comment by mpeters** [comment]
I agree. I kept having to go back and forth between the terms in my proposal simply to make sense with what already exists. I'll do this first.

**Comment by mpeters** [comment]
Do we have to put "ima" in the name? Are we tied to IMA completely such that we couldn't use something else in the future? Not saying we would/should change or make it IMA agnositic, just that on the tenant and verifier side they don't know anything about IMA right? In general I prefer naming thing for what they do, not have it's implemented.

I think I just prefer just the simple `--allowlist`. Thoughts?

**Comment by lukehinds** [comment]
`allowlist` sounds fine to me, or open to other ideas if something better to comes to mind, but sure we are not fixed to IMA as a naming.

**Comment by lukehinds** [comment]
done: https://github.com/keylime/keylime/pull/372
