### ISSUE TITLE
Setup tools is broken on the master branch

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#339]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 18.04
 * Processor architecture: x86_64
 * TPM Manufacturer: virtual TPM
 * Keylime version: 5.7

# Description 
Just tried the following sequence of commands

```
git clone https://github.com/keylime/keylime.git
cd keylime
sudo python3 -m pip install -r requirements.txt
sudo python3 setup.py install
```

## Expected behavior vs. actual behavior 
```
root@h4k1-mstr0:~/keylime# /usr/local/bin/keylime_agent 
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'keylime.cmd'
```

## Steps to reproduce problem
1. Just clone, install and try to execute any of the keylime executables

**Comment by maugustosilva** [comment]
@lukehinds the solution is pretty simple, just adding a single in `setup.py` should be enough to solve the problem `package_data={'keylime': ['*','*/*', '*/*/*']},`

@kaifeng is it possible that it was introduced in PR #302 ?

**Comment by kaifeng** [comment]
If memory served the change should have passed ci at that time, I am not sure this issue is related, sounds like a packaging problem if package_data could resolve. But package_data is used for non-code data, I suspect it may be related to pbr, but need to investigate.
