### ISSUE TITLE
Inconsistency between IMA logs and PCR10

### ISSUE THREAD

**Issue by droccom** [keylime/keylime#341]
@galmasi
@maugustosilva 

# Environment
 * OS / version: Ubuntu 18.04.3
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: 5.7

# Description 
Keylime is ignoring the fact that IMA logs and PCR 10 are not always in sync, as on the agent side they are retrieved at different times, as requested by the verifier.

## Expected behavior vs. actual behavior 
The code section:

https://github.com/keylime/keylime/blob/0a921fa48b768d946ea58dbe7674786186518a35/keylime/tpm/tpm_abstract.py#L336-L344

assumes PCR10 and IMA logs to be synchronized when received by the verifier, i.e. it assumes the latest PCR10 received always equals the aggregated hash of IMA measurements up to the last point of the IMA logs just received. However this is not true in general and the test sporadically fails.

## Steps to reproduce problem
Just run a regular Keylime deployment for some time, with a non-trivial number of nodes. We started seeing the issue with 8 nodes or so.

# Proposed Solution
Drop the assumption of PCR10 and IMA logs to be in sync and consider that a given PCR10 value can match any entry in:
- the IMA logs received along with that PCR10 value
- the previous batch of IMA logs (although this will be rare, it cannot be excluded)

**Comment by lukehinds** [comment]
tagging @jetwhiz

**Comment by mpeters** [comment]
I believe I have experienced this issue as well although I didn't track it down fully since I was just getting the system setup (and the system was a low traffic, so low turnover in the ima measurements).

**Comment by droccom** [comment]
Thanks @lukehinds @mpeters! Feel free to reach out for any further information or/and discussion on this.

**Comment by lukehinds** [comment]
@droccom is this an issue you intend to work on, do you have any code fixes you have tried out. I have yet to dig into this, so thought it prudent I check with you, as you further along the troubleshooting path compared to me.

**Comment by droccom** [comment]
I will propose a fix with a PR as soon as possible.

**Comment by kgold2** [comment]
I think I posted this somewhere - perhaps the same issue is repeated.

Even if PCR 10 matches some subset of the event log, it doesn't matter to the verification.  That PCR 10 may not be the one that was quoted.

Thus, the loop has to be testing the quoted digest against the event log.  PCR 10 is not required.

The verification has to cover all quoted PCRs, not just PCR 10.
