### ISSUE TITLE
pull #328 hsa broken CI

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#351]
Thanks to travis being so unreliable in updating PRs with build status, we managed to merge a patch which has broken CI:

https://travis-ci.org/github/keylime/keylime/builds/723820811

The change in question is:

https://github.com/keylime/keylime/pull/328 

@maugustosilva are you able to take a look at this, you can reach me on gitter.im if you need any help?

**Comment by maugustosilva** [comment]
hey @lukehinds, is this still an issue?

**Comment by lukehinds** [comment]
@mpeters i think this is fixed now?

**Comment by mpeters** [comment]
Yes, sorry. I didn't realize there was an issue for this.
