### ISSUE TITLE
Kernel resource manager

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#361]
@galmasi / @maugustosilva  could you please share some details on how you use the vtpm and kernel resource manager in a container (I think you guys use a container) - if not and its a VM, then how to use the kern resource would still be useful (as we can use the emulator and kern resource manager)

@mbestavros is migrating our CI away from travis, but tpm2-abrmd requires some horrible hacks to mount cgroups for systemd, so the kern resource manager would free us from needing to run a privileged container.

**Comment by maugustosilva** [comment]
In our environment, we test Keylime on a cluster of VMs with `swtpm` (Virtual TPM): we use one VM per `Keylime` "component" (e.g., one VM dedicated to `Verifier` and another dedicated to `Registrar`), in addition to a couple of extra VMs for agents.

Inside each VM we run `Keylime` as a container. Here is the full invocation of a `Keylime Agent` container:

`docker run -td --net host -e KEYLIME_ROLE=agent --name keylime_agent --privileged --device /dev/tpmrm0:/dev/tpmrm0 <IMAGE NAME>`

And inside, container, the following environment variable is set:

`export TPM2TOOLS_TCTI=device:/dev/tpmrm0`

**Comment by lukehinds** [comment]
thanks @maugustosilva !

**Comment by lukehinds** [comment]
Just been working on this. So it looks like your mounting the VMs vTPM into the container?

**Comment by maugustosilva** [comment]
> Just been working on this. So it looks like your mounting the VMs vTPM into the container?

Yes, we are using the (already available) libvirt support for swtpm (vTPM)
