### ISSUE TITLE
Allow _Agents_ on private network to be reached back by _Verifier_ on public network via port mapping

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#370]
I have an use case where the Keylime _Verifier_ and _Registrar_ live on a very secure separate network (actually on a Z mainframe) and it is reachable via a Public address. I believe that with a simple change, we should be able to provide Keylime the ability to let _Agents_, in separate networks, to establish bi-directional communication with Keylime's "Control Plane" (i.e., _Verifier_ + _Registrar).

The basic proposal is: allow each agent to specify an "alternate IP address" and "alternate port". These will get stored on the _Verifier_ database, and it can then use this "alternate" IP/Port pair to contact an Network Port Address Translation device, which will map these "alternate" to actual IP/Port pair used by the individual agent.

An illustrative description of the scenario is the following:
```
 |                              +---------------------------+                              |
 |    +-------------------+     |    NATP Device            |     +-------------------+    |
 |    |       Agent       +-----+---------------------------+----->     Verifier      |    |
 |    |Private IP A:Port A|<+   |                           | +---+Public IP V:Port V |    |
 |    +-------------------+ |   |                           | |   +-------------------+    |
 |                          |   |                           | |                            |
 |                          |   |                           | |                            |
 |                          +---+<-------Public IP T:Port _A|<+                            |
 |                              +---------------------------+                              |
 |                                                                                         |
```
In this case, the _Agent_ can reach out the _Verifier_ directly on the Public IP "V" (due to the NAT device), and whenever the _Verifier_ has to contact back the _Agent_ it does so through the Public IP "T", port **_A** (which is different from agent's Port A).

In order to avoid disruption in the current DB schema, I propose that values `cloudagent_ip` and `cloudagent_port`, under the section `[cloud_agent]` in `keylime.conf` allow the use of colon (`:`) to separate between "real" and "alternate" IP/Port pairs. Before opening up a connection, the _Verifier_ will check for the existence of `:` on the `ip` column on the line retrieved from the database, and will just use the "alternate" one if exist.

Almost needless to say. I have not yet implemented it, and not fully pondered through the implications. For the moment, I do believe that this is going to be a relatively small/simple modification which will greatly expand the use cases for Keylime

@mpeters @lukehinds please let me know what you think of it.

**Comment by lukehinds** [comment]
Just a few thoughts from talking to colleagues (I am not a networking SME)..

"That is what UpNP is for. You just ask the firewall for a mapping"

"rather than change the app, could you not us an ssh tunnel"

My own take is we could accommodate this if it is a simple change, but it would have to be off by default and not disruptive to someone not requiring this functionality.

**Comment by maugustosilva** [comment]
I believe the main decision point here is what we want to provide natively on _Keylime_, versus what can be provided by an admin/automation **prior** to _Keylime_ standup. 

We will not always have UPNP devices available, and might have no direct control of the firewall to do the mapping.

Similarly, we could use an SSH tunnel, but this would be yet another "pre-deployment" requirement.

**Comment by maugustosilva** [comment]
@lukehinds @galmasi

Turns out it can be achieved with zero changes to _Keylime_. I will briefly describe here, and we can further discuss if it is worthy of being included in the documentation.

1) Deploy the _Keylime Agent_ unmodified
2) Perform the "Port/IP mapping" on the NAT device (for instance just run something like `rinetd` there)
3) Invoke `keylime_tenant` with CLI options `-t Public IP T -tp Port _A` (i.e., the mapped Public IP and port)

**Comment by maugustosilva** [comment]
I am closing if for now. Let me know if you want me to include in the documentation.
