### ISSUE TITLE
Drop logics related with DEVELOP_IN_ECLIPSE

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#383]
In our scenario we use keylime as root, I am wondering if the DEVELOP_IN_ECLIPSE is actually in use because it seems a bit old, but no sure if it's in use in the CI (as far as I see the CI is using container as root). If we no longer need that, we probably could drop to make the maintenance easier.

**Comment by lukehinds** [comment]
I don't think anyone uses this, and we should not really have opinonated debug flags around any particular IDE. I am happy for you to nuke all references to it!

**Comment by nabilschear** [comment]
for flavor, this was my little set of developer flags that made it easier to do local development.  At some point we split it into all its various components (like require root etc).  So, i think this is fine to remove.
