### ISSUE TITLE
Incorporate pep8 coverage

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#384]
Adding pep8 checking helps to find potential issues that we are not running in the code path, and apply consistent code style to the project.

**Comment by lukehinds** [comment]
We did have this with codacy, but there seems to be some CI issues at the moment. I will try to investigate.

**Comment by stefanberger** [comment]
The following command line would let us cleanly transition from `pep8` to `pylint` and then crank up the checks by removing what is currently disabled:

```
pylint \
  --disable C0103,C0115,C0116,C0123,C0200,C0325,C0301,C0302,C0330,C0411,C0412,C0414,C0415,C0114,C0122 \
  --disable W0127,W0201,W0223,W0235,W1201,W1202,W0611,W0603,W0613,W0703,W0613,W0102,W0702,W0622,W0212,W1505,W0511,W0631,W0632,W0621,W0612,W0105,W0715,W0101,W0221,W0107,W1509,W0614,W0401,W0601 \
  --disable E0401,E0611,E1300,E1101,E0602,E1205,E1120,E1121,E1123,E1111,E1136 \
  --disable R0801,R0902,R0205,R0903,R0912,R0914,R0915,R1702,R1705,R1711,R1722,R1724,R1720,R0201,R0911,R1723,R1716,R0913,R1714,R0124,R1710,R0904,R1703 \
*.py $(find ./keylime ./test -name '*.py')
```

Everybody can grab a cookie! (#define cookie 'disabled warning')

**Comment by mpeters** [comment]
Yeah, I like this idea as it would definitely help us find problems in code that is either undertested, really hard to test (bad ROI) and utility stuff that isn't applicable to all platforms.

**Comment by stefanberger** [comment]
Problem is it takes a lot longer with pylint (59s) versus pep8 (3.4s).

**Comment by mpeters** [comment]
That's not a huge problem. It's mostly going to be run in the pipeline and the tests already take a lot longer to run than that. And adding it to your workflow as a developer is still not as taxing as running the tests either.

So that extra 55s isn't a problem IMO

**Comment by stefanberger** [comment]
i can send a PR for that then https://travis-ci.com/github/stefanberger/keylime/builds/203187797

**Comment by stefanberger** [comment]
Maybe we can close this issue since this has landed and pylint provides much more than the original thought of using pep8.

**Comment by mpeters** [comment]
Agreed
