### ISSUE TITLE
Agents restored to saved state after verifier restart

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#393]
During Verifier startup, it updates all agents to the saved state, which needs human intervention to reactivate all the agents, this doesn't look like a reasonable action in production, especially when verifier is behind HA.

**Comment by maugustosilva** [comment]
@lukehinds @mpeters @kaifeng we are also trying come up with a solution to this problem. The somewhat "monolithic" architecture of `verifier` makes it hard to solve/fix within. One approach that we have been considering is, upon restart, just "re-add" (via keylime_tenant code) all the `agents` registered on the `verifier` (excluding the ones who did fail attestation)

**Comment by kaifeng** [comment]
@maugustosilva a simple solution would be keeping agent states as it is when verifier starts, while retriggers the agent processing for those states makes sense (get quote for example). In the long run, I think it's worth to introduce a FSM to help with state transitions.

**Comment by mpeters** [comment]
Could that same code that is triggered from tenant requests not also be triggered from restart? There would probably be some refactoring needed but I don't see that as big of an issue as actually invoking tenant commands when the verifier restarts

**Comment by maugustosilva** [comment]
@mpeters this is exactly what we (myself and another colleague) are writing right now. Inside the `main` function on `cloud_verifier_tornado.py`, we get a list of agents that need to be "updated" (i.e., deleted and then added back), and we start a separate process to do exactly it once the tornado web server restarts. Not pretty, not elegant but should solve the problem until we do a proper re-design of the `verifier` code (IMO, it should be split in 3 parts: tenant request processor, agent polling and dispatcher)

**Comment by maugustosilva** [comment]
@mpeters @kaifeng @lukehinds so, the "reactivate agent" operation (issued by the tenant) seems to simplify the recovery after `verifier` restart. There was a small bug there that I am fixing with this PR: https://github.com/keylime/keylime/pull/423

**Comment by maugustosilva** [comment]
@apoorvemohan Please take a look at the linked PR. I believe it starts to address the problems we discussed.

**Comment by apoorvemohan** [comment]
@maugustosilva I tried the PR https://github.com/keylime/keylime/pull/480 opened by @kaifeng. The basic agent-reactivate functionality worked after patching it with https://github.com/keylime/keylime/pull/487.
