### ISSUE TITLE
EE Key too small on CentOS 8

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#395]
Keylime verifier failed to run on CentOS 8:
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]: Traceback (most recent call last):
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:   File "/usr/bin/keylime_verifier", line 11, in <module>
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:     load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_verifier')()
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:   File "/usr/lib/python3.6/site-packages/keylime-0.0.0-py3.6.egg/keylime/cmd/verifier.py", line 23, in main
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:     cloud_verifier_tornado.main()
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:   File "/usr/lib/python3.6/site-packages/keylime-0.0.0-py3.6.egg/keylime/cloud_verifier_tornado.py", line 668, in main
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:     context = cloud_verifier_common.init_mtls()
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:   File "/usr/lib/python3.6/site-packages/keylime-0.0.0-py3.6.egg/keylime/cloud_verifier_common.py", line 153, in init_mtls
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]:     certfile=my_cert, keyfile=my_priv_key, password=my_key_pw)
Nov 09 17:07:11 TPM-client-1 keylime_verifier[1329931]: ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:3542)
Nov 09 17:07:11 TPM-client-1 systemd[1]: keylime_verifier.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 17:07:11 TPM-client-1 systemd[1]: keylime_verifier.service: Failed with result 'exit-code'.

This typically indicates the private key is weak, CentOS 8 is using CipherString @SECLEVEL=3, can work around by lowering security level to 1 or 2. Current code already generates 2048 bits certifcate so I am probably missing something here.

**Comment by kaifeng** [comment]
Raising cert_bits also works, there is nothing needs to do since we have configuration support.

**Comment by mpeters** [comment]
I wonder if we could improve the user experience here. Can we catch this error from the SSL side and provide a more useful message to the user that maybe they need to increase their cert_bits configuration value when this failure occurs?

**Comment by kaifeng** [comment]
Sounds like a good idea, I am reopening to see if we can do some improvements here.
