### ISSUE TITLE
Registrar key password is never used

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#420]
`my_key_pw` is never used:

https://github.com/keylime/keylime/blob/be4b874bf9bc232e6e1dcf747f4a8cd329a33858/keylime.conf#L185

https://github.com/keylime/keylime/blob/be4b874bf9bc232e6e1dcf747f4a8cd329a33858/keylime/registrar_client.py#L41

**Comment by mpeters** [comment]
@maugustosilva and @lukehinds I don't see this config variable in the code anymore so I assume it was removed. It does however still exist in the `keylime.conf` in the repo, so I assume we can remove it, correct?
