### ISSUE TITLE
Make keylime running as non-root

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#436]
keylime can run as root or non-root, but we have to treat them differently for path, validation, etc.
The proposal is to persistently make keylime running as non-root and remove REQUIRE_ROOT, for actions that requires root privilege, sudo should be used.
This will simplify our implementation and have better security control.

**Comment by lukehinds** [comment]
There is an enhancement in place for this work: https://github.com/keylime/enhancements/blob/master/23_dedicated_keylime_user_account.md

I agree it definitely needs to happen and there is nothing stopping work getting underway on the registrar and verifier, the agent is a little more involved as TPM functions require root. Do you know how health rootwrap is @kaifeng , i remember it from openstack. 

tagging @axelsimon who was looking into this.

**Comment by kaifeng** [comment]
@lukehinds openstack is migrating from rootwrap to privsep, rootwrap is considered less secure. Some projects have finished this transition while some are on the way.

**Comment by axelsimon** [comment]
Thanks for bringing this up @kaifeng. Completely agree with your proposal.
i'm looking into it currently. Thanks for mentioning privsep, i'll look into it.

Currently, `keylime_registrar` and `keylime_verifier` run as a keylime user, although they fail to log.
`keylime_webapp` doesn't run, and i'm looking into it.
`keylime_agent` likely needs root for the TPM access, so i've not investigated that one yet.

**Comment by maugustosilva** [comment]
@axelsimon @kaifeng @mpeters So, I tested running the `agent`, both from the command line and as a Systemd service, as non-root (in particular, I tried with user `tss` as this one allows for access to `/dev/tpmrm0`), and was successful in both cases. I believe the time has come to remove the check in https://github.com/keylime/keylime/blob/master/keylime/keylime_agent.py#L453

Please note that we do have the environment variable `KEYLIME_REQUIRE_ROOT` in https://github.com/keylime/keylime/blob/master/keylime/config.py#L71, but it is used mainly for testing, and changes the logging destination quite dramatically.

Thoughts?

**Comment by mpeters** [comment]
I agree now is a good time to remove this. Is this change big enough to need an enhancement proposal to make sure we have all our ducks in a row?

**Comment by maugustosilva** [comment]
I don't think it is particularly big, since we are talking about four loc only. My plan was to leave, at least for now, the `REQUIRE_ROOT` in place (since it is used for testing in different ways), and only remove that particular check.

**Comment by maugustosilva** [comment]
@mpeters ok, I have re-read the first comment by @kaifeng and now see that he would like to remove the `REQUIRE_ROOT` altogether. This is fine, I do not oppose to it, but you're right: it will become a much longer (subsequent) commit.

**Comment by kaifeng** [comment]
It appears interacting with TPM via abrmd doesn't require root, but accessing IMA log would need it, we still need some kind of privilege promotion stuff. Anyway we are running verifier/registrar as non-root for quite a while.

**Comment by maugustosilva** [comment]
@kaifeng We can change ownership of `/sys/kernel/security/ima/ascii_runtime_measurements` and `/sys/kernel/security/tpm0/binary_bios_measurements` via an udev rule, and have full functionality for the `agent`. Either way, I believe we all agree the time for removal of "check if non-root, and quit if true" code on the `agent` has come, right?

**Comment by mpeters** [comment]
There's been a lot of discussion on this and 2 different proposals that could be somewhat overlapping, but I wanted to pull together their discussion here:

A). Drop keylime's objection to running as non-root and let the installer/packaging take care of making sure keylime has the right permissions to do what it needs. Keylime would check these permissions at startup and then fail if they aren't correct
B). Keylime starts as root and then changes to a different user:group as soon as it can.

Other daemons use approach A because they to bind to a privileged port, but keylime doesn't need to do that. The files keylime needs access to could be adjusted to give us read access, but will packagers want to do that? Telling them they need to make the IMA measurements readable by non-root could be a non-starter for some simply because it's always been just root.

Now that we have the 2 approaches side by side in PR #626 and PR #611, what do others think?

@maugustosilva @stefanberger @kaifeng @axelsimon @lukehinds @galmasi

**Comment by stefanberger** [comment]
> Other daemons use approach A because they to bind to a privileged port, but keylime doesn't need to do that. The files keylime needs access to could be adjusted to give us read access, but will packagers want to do that? Telling them they need to make the IMA measurements readable by non-root could be a non-starter for some simply because it's always been just root.

The packagers would have to have a script that runs on every reboot to set the permissions/ownership of the TPM and IMA log files.
