### ISSUE TITLE
Some more dev env stubs to clean up

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#442]
We can remove the following lines:

https://github.com/keylime/keylime/blob/bdd3a68261ba6180b9d4b3c9a4d8a4e6489265b3/keylime/config.py#L314-L348

Tagged as good first issue, so a new conributor can pick this up.

**Comment by kaifeng** [comment]
Stuff between L314-L330 is not referenced and can be removed, but STUB_IMA is reference in many places, I would be glad to remove the STUB code but need a confirmation.

**Comment by dcmiddle** [comment]
Close me?
