### ISSUE TITLE
Store allowlist in a separate table

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#485]
Current allowlist is saved with the agent record, there are two issues here:
1. An allowlist can't be shared between agents, so we can't apply the same data to identical OSes.
2. Since the ima measurements could be very large, it has impact on query efficiency when the allowlist does not participate in the processing.

The proposal is to create a new table named ``allowlists`` to save allowlist, and alter the ``agent.allowlist`` to a foreign key to the allowlist table. A full allowlist management and API is beyond this proposal.

**Comment by maugustosilva** [comment]
I strongly support this move, for several additional reasons. One of the most relevant for me is the fact that I am working on support for "TPM2 event log" processing on KeyLime (which should allow a more intelligent verification of PCRs [0-9,14]) and this would require the introduction of a "golden event log template" or some such, which would be also shared across multiple nodes.

**Comment by lukehinds** [comment]
For this change we should factor in multi-tenancy which is underway, so I expect we would need to consider somehow having a relational map to a `group_id` at some point in the future. This way in multi tenant scenario users could implement versioning to groups , e.g. a beta release list could go into a `testing` group and in turn not available to use a production system. 

https://github.com/keylime/enhancements/issues/7

**Comment by lukehinds** [comment]
> I strongly support this move, for several additional reasons. One of the most relevant for me is the fact that I am working on support for "TPM2 event log" processing on KeyLime (which should allow a more intelligent verification of PCRs [0-9,14]) and this would require the introduction of a "golden event log template" or some such, which would be also shared across multiple nodes.

Sorry I should not hijack this thread, but if this requires changes to the agent code we should consider this will need to go into the rust agent, its likely worth syncing with @puiterwijk who has some plans to optimising tpm2 quotes in the rust project.

**Comment by mpeters** [comment]
I agree, this sounds like a good idea for all of the right reasons :)

**Comment by kaifeng** [comment]
> 
> 
> > I strongly support this move, for several additional reasons. One of the most relevant for me is the fact that I am working on support for "TPM2 event log" processing on KeyLime (which should allow a more intelligent verification of PCRs [0-9,14]) and this would require the introduction of a "golden event log template" or some such, which would be also shared across multiple nodes.
> 
> @maugustosilva
> 
> Sorry I should not hijack this thread, but if this requires changes to the agent code we should consider this will need to go into the rust agent, its likely worth syncing with @puiterwijk who has some plans to optimising tpm2 quotes in the rust project.

@lukehinds the allowlist is stored in the verifier database, so the proposed change doesn't have impact on the agent side. I am not sure why multi-tenancy involves the change, since my basic understanding on multi-tenancy is provides user management for accessing APIs, right?

**Comment by lukehinds** [comment]
@kaifeng it was more for @maugustosilva notes on "which should allow a more intelligent verification of PCRs [0-9,14])" which is why I mentioned being sorry for hijacking the issue.

**Comment by stefanberger** [comment]
> A full allowlist management and API is beyond this proposal.

I think this will require that the keylime_tenant tool learns to manage the IMA allowlist, like giving it a name:
```
keylime_tenant -c add ... --allowlist myallowlist.txt --allowlist-name fedora-32.update5
```

Then also referencing an IMA allowlist by name:
```
keylime_tenant -c add ... --allowlist name:fedora-32.update5
```

Or just a whole separate set of keylime_tenant subcommands for managing the life-cycle of an allowlist: creation with a name, update by name, deletion by name.
The same probably also applies to other lists to be applied to systems: firmware whitelist, lists of signature verification keys

I wonder what the sequence of adding this should be versus multi-tenancy. Probably multi-tenancy should come first...  ?

**Comment by mpeters** [comment]
That's a good question about the ordering. I actually think this can come before multi-tenancy because multi-tenancy needs to touch a lot of different parts so adding one more won't really make that more complicated. But this could be useful even if we don't have segmented groups of users.

**Comment by kaifeng** [comment]
> > A full allowlist management and API is beyond this proposal.
> 
> I think this will require that the keylime_tenant tool learns to manage the IMA allowlist, like giving it a name:
> 
> ```
> keylime_tenant -c add ... --allowlist myallowlist.txt --allowlist-name fedora-32.update5
> ```
> 
> Then also referencing an IMA allowlist by name:
> 
> ```
> keylime_tenant -c add ... --allowlist name:fedora-32.update5
> ```
> 
> Or just a whole separate set of keylime_tenant subcommands for managing the life-cycle of an allowlist: creation with a name, update by name, deletion by name.
> The same probably also applies to other lists to be applied to systems: firmware whitelists, exclude lists, lists of signature verification keys
> 
> I wonder what the sequence of adding this should be versus multi-tenancy. Probably multi-tenancy should come first... ?

Excluding the whitelist management from this issue is simply because this would be a large change, I want to break it down to smaller steps. I was thinking about getting a whitelist from the agent, then reuse it for other hosts, the name could be autogenerated from information collected from the host, firmware/OS etc.

**Comment by maugustosilva** [comment]
I second @kaifeng on this one. A smaller, incremental change where the lifecycle of the `allowlist` is done out-of-band (i.e., simply delete the table) now is better than a complete solution later. On other hand I do see the point @stefanberger is making as an unavoidable one: we will need to add a new CLI parameter on `keylime_tenant`, (I particularly like`--allowlist-name`) with a "reasonable default" (the agent's UUID?) as a good initial solution

**Comment by kaifeng** [comment]
Well, the unfortunate thing is that sqlite doesnot support alter, I am testing a migration script and it complains

```
[root@Controller-1 vtu]# keylime_verifier
Using config file /etc/keylime.conf
2021-01-12 14:57:54.369 - alembic.env - INFO - Migrating database cloud_verifier
2021-01-12 14:57:54.369 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2021-01-12 14:57:54.370 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2021-01-12 14:57:54.378 - alembic.runtime.migration - INFO - Running upgrade  -> 8a44a4364f5a, Initial database migration
2021-01-12 14:57:54.389 - alembic.runtime.migration - INFO - Running upgrade 8a44a4364f5a -> eeb702f77d7d, allowlist rename
2021-01-12 14:57:54.391 - alembic.runtime.migration - INFO - Running upgrade eeb702f77d7d -> eb869a77abd1, create_allowlist_table
2021-01-12 14:57:54.415 - keylime.cloudverifier - ERROR - No support for ALTER of constraints in SQLite dialect
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/keylime/cmd/verifier.py", line 20, in main
    keylime.cmd.migrations_apply.apply('cloud_verifier')
  File "/usr/lib/python3.6/site-packages/keylime/cmd/migrations_apply.py", line 31, in apply
    alembic.config.main(argv=alembic_args)
  File "/usr/lib/python3.6/site-packages/alembic/config.py", line 527, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python3.6/site-packages/alembic/config.py", line 521, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python3.6/site-packages/alembic/config.py", line 501, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/usr/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/keylime/migrations/env.py", line 147, in <module>
    run_migrations_online()
  File "/usr/lib/python3.6/site-packages/keylime/migrations/env.py", line 127, in run_migrations_online
    context.run_migrations(engine_name=name)
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/usr/lib/python3.6/site-packages/keylime/migrations/versions/eb869a77abd1_create_allowlist_table.py", line 20, in upgrade
    globals()["upgrade_%s" % engine_name]()
  File "/usr/lib/python3.6/site-packages/keylime/migrations/versions/eb869a77abd1_create_allowlist_table.py", line 51, in upgrade_cloud_verifier
    'allowlists', ['allowlist_id'], ['id'])
  File "<string>", line 8, in create_foreign_key
  File "<string>", line 3, in create_foreign_key
  File "/usr/lib/python3.6/site-packages/alembic/operations/ops.py", line 640, in create_foreign_key
    return operations.invoke(op)
  File "/usr/lib/python3.6/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 150, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "/usr/lib/python3.6/site-packages/alembic/ddl/sqlite.py", line 35, in add_constraint
    "No support for ALTER of constraints in SQLite dialect"
NotImplementedError: No support for ALTER of constraints in SQLite dialect
exception: No support for ALTER of constraints in SQLite dialect
```

The migration script:
```
def upgrade_cloud_verifier():
    op.create_table('allowlists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(255), nullable=False),
                    sa.Column('tpm_policy', sa.String(length=1000), nullable=True),
                    sa.Column('vtpm_policy', sa.String(length=1000), nullable=True),
                    sa.Column('allowlist', sa.Text(length=429400000), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', name='uniq_allowlists0name'),
                    mysql_ENGINE='InnoDB',
                    mysql_DEFAULT_CHARSET='UTF8'
                    )

    op.add_column('verifiermain', sa.Column('allowlist_id', sa.Integer(),
                                            nullable=True))
    op.create_foreign_key('fk_verifiermain_allowlists', 'verifiermain',
                          'allowlists', ['allowlist_id'], ['id'])
```

If we want to keep sqlite supported, we probably can't use foreign keys.

**Comment by mpeters** [comment]
Did you create this migration by hand? I wonder if maybe doing automatic migrations would allow alembic to figure out the right order of events. Maybe you have to add foreign keys at the same time as the create? Or some other change to the order maybe.

**Comment by kaifeng** [comment]
The skeleton of the script is created by alembic, but the db operation is by hand. Applying a foreign key will issue an alter command, but there is no difference by adding a column with foreign key because sqlalchemy will issue two commands with the latter one an alter.
There seems to be a way to address this with batch migration, but the side effect could be introducing difficulties when something is wrong during the migration.
