### ISSUE TITLE
Integrated test environment for keylime

### ISSUE THREAD

**Issue by galmasi** [keylime/keylime#500]
This is a place holder issue -- we had an initial discussion with @mpeters about the desirability of an integrated test environment. This would allow catching of bugs beyond what unit tests are capable of doing, and contribute to improving SW quality.

@mpeters has promised to make inquiries about required infrastructure support.

Our ideas run in terms of:
* a collection of virtual machines booted with recent versions of Fedora/RHEL/Ubuntu.
* each virtual machine would come with swtpm supported virtual TPMs with a self-signed (but testable) manufacturer key.
* our current strategy favors keylime running in containers (packaging trouble) but that's flexible
* measured boot and IMA can be tested by "seeding" the system with allow lists calculated from the VM images themselves
* the test suite could run multiple variations of (a) mult-verifier deployments and (b) database connections

**Comment by lukehinds** [comment]
I think this is a good idea, at the moment we have a hybrid of unit tests and integration tests thrown in together. It would be good to see both seperated and the integration tests run a full end to end case with its own CI job. a  big +1 from me. 

tagging @mbestavros for when we need to consider GH actions etc.

**Comment by galmasi** [comment]
We have not made a lot of progress on this -- 

* the first major issue to settle is to provide some hardware for running end-to-end tests. We are experimenting in the IBM intranet with setting up an end-to-end test based on 6 to 8 virtual machines running in a single physical machine, each of the VMs supported by swtpm. This makes the test environment look *almost* identical to real hardware.

* for deploying those virtual machines, we are using an internal project called Demeter. We are working on open sourcing this, but even absent demeter we could deploy the VMs with something like terraform.

* in order to minimize the packaging issues related to Keylime, right now we are dockerizing the test environment -- not terribly unlike keylime's own.

* our automated deployment mechanism also "feeds" keylime with allow lists, boot aggregates and (eventually) boot logs harvested from the nodes themselves.

**Comment by mpeters** [comment]
This is actually being done by the Red Hat QE team and the resulting tests are included in our pre-commit CI
