### ISSUE TITLE
DCO check is missing for the Keylime project

### ISSUE THREAD

**Issue by idvoretskyi** [keylime/keylime#506]
Greetings, project maintainers.

CNCF's IP policy (https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy) requires all projects to use either CLA (Contributor License Agreements) or DCO (Developer Certificate of Origin). Unless there's a strong necessity to use CLA, we encourage projects to use DCO as it's easier to setup and use. Ref.: https://github.com/cncf/foundation/issues/130

During the audit, we've noticed that one or a few repositories of your project doesn't have the DCO check enabled. Please enable the DCO check for all repositories in your GitHub organization. You may find more details here - https://github.com/apps/dco.

Thanks

**Comment by lukehinds** [comment]
hi @idvoretskyi does DCO need to be retrospective or can it just for new code. It might be challenge to get old contributors to sign as they have since moved on. We could apply it going forward though, and implement the bot to check each new PR for a sign off?

**Comment by idvoretskyi** [comment]
@lukehinds yes, please enable it for the future PRs at least, thanks.

**Comment by lukehinds** [comment]
hey @mbestavros are you interested in taking this one on?

**Comment by mbestavros** [comment]
@lukehinds We used this [Action](https://github.com/probot/dco) on the Enarx project to great effect. It works well (adds another PR check that succeeds when the commit is signed with `git commit -s` and is really easy to set up. Does need to be installed and enabled by a project admin, however, so I can't enable it myself.

**Comment by mbestavros** [comment]
@lukehinds Seems like this is active; should we close this now?

**Comment by idvoretskyi** [comment]
Yes, it works here - https://github.com/keylime/keylime/pull/515/checks?check_run_id=1728548215, closing now.

Thanks!
