### ISSUE TITLE
tpm.readPCR is not working

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#518]
Calling tpm.readPCR will raise an exception as following:

```
>>> tpm.readPCR(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/keylime/tpm/tpm2.py", line 1152, in readPCR
    return '{0:0{1}x}'.format(jsonout[hash_alg][pcrval], alg_size)
ValueError: Unknown format code 'x' for object of type 'str'
>>>
```

The value passed to format string should be an integer instead of string. It appears that there is no need to padding manually, as tpm tools already outputs padded values, but I am not sure if there is any historical reason to do so?

**Comment by THS-on** [comment]
@kaifeng this works for me in Keylime 6.3.1 on Ubtunu 18.04 with Python 3.6 and Fedora 34, so I think this can be closed.

cc: @mpeters
