### ISSUE TITLE
ans1 package needed in CI and installation scripts

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#521]
The [IMA file signing patch](https://github.com/keylime/keylime/pull/496) introduced a new dependency asn1, but this was not added to the docker images for CI and the installer.sh (and ansible role), it is currently only in the requirements.txt

Luckily this is packaged in Fedora as python3-pyasn1

This issue means the changes should be made. I also think we should think of a way handling additional dependencies in a way that we can make sure they are supported and packaged correctly. I expect we should do something in enhancements.

**Comment by lukehinds** [comment]
another example of why we need this: https://github.com/keylime/keylime/issues/519#issuecomment-766951400

**Comment by stefanberger** [comment]
I just sent PR #524 that gets rid of this package and rather unused DSA keys.

**Comment by stefanberger** [comment]
Some householding: Is this still an issue or can we close it?
