### ISSUE TITLE
Discontinue TPM 1.2

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#526]
We should consider dropping 1.2.  I don't have a hard time in mind to propose, but let's at least get this up for discussion so its on the record for when we do drop it.

**Comment by mpeters** [comment]
Agreed. There have been a couple of discussion about new features where we've just decided to not include support for 1.2, but that means it's piecemeal. Would be good to formally drop everywhere.

**Comment by galmasi** [comment]
+1. We are a bit hamstrung in our measured boot work by the existence of TPM1 code. Without TPM1 support we could streamline the code with fewer headaches.

**Comment by lukehinds** [comment]
Let's drop it then. I don't see any reason for hanging around here. Let's have this sit for the rest of Jan and ship a 6.x release where we nuke TPM 1.2 support.
