### ISSUE TITLE
implement vulnerability handling process

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#53]
As per @jetwhiz 's comment https://github.com/keylime/python-keylime/pull/47#pullrequestreview-201399617 , let's get started forming an approach to vulnerability management.

initially I think we should get something simple in place as we are still a young project, over time we can increase the scope. 

I quickly dumped down the following points for discussion. In time I will port this into some markdown and we can have a final review when its put into a PR. 

To start I recommend:
1. Include a 'How to report a security vulnerability in Keylime' section on the README.md
2. Create a [security@keylime.groups.io](mailto:security@keylime.groups.io) email, with just core team members able to see this. This is the contact point for security researchers reporting an issue.
3. Core team member creates a private discussion in the [core team area](https://github.com/orgs/keylime/teams/core). They include all of the information provided by the researcher. 
4.  The reported issue is triaged (is it invalid, reproducible).
5. If [4] is confirmed, a core member requests a CVE number.
6.  Patch is proposed and reviewed using .patch diff file in the team area discussion at point [3]
7. If applicable, installers (ansible, installer.sh) are evaluated for patching to address the issue and patches proposed in the team discussion.
8. Patch is applied to master, and backported to previous releases. This should happen during the days (Monday to Thursday) to allow users time to make the change.
9. A new release is cut on github (using semver x.x.\<incremented number\>).
9. Notifications are sent to the following (using an email template that we will have)
* main@keylime.groups.io 
* oss-security@lists.openwall.com

**Comment by lukehinds** [comment]
I wonder if we should just put some brief details up on the readme for now, until the above is finalised into a nice process flow?.............

# Report a Security Vulnerability

Please contact us directly at [security@keylime.groups.io](mailto:security@keylime.groups.io) for any bug that might impact the security of this project.

**Comment by jetwhiz** [comment]
> 
> 
> I wonder if we should just put some brief details up on the readme for now, until the above is finalised into a nice process flow?.............
> # Report a Security Vulnerability
> 
> Please contact us directly at [security@keylime.groups.io](mailto:security@keylime.groups.io) for any bug that might impact the security of this project. **Do not** use a github issue to report any potential security bugs.

I think that's a good idea, at least so we have a temporary/simple policy in-place about how to report security bugs found.
