### ISSUE TITLE
Remove Deep Quote Code

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#530]
Let's drop the deep quote code

1. It only works on xen, is anyone using xen (I am not sure if even works on current xen versions)?
2. We have had security researchers pick holes in the code. Considering point 1, its a false optic having it there.

I propose we let this sit for Jan and then nuke it in a 6.x release.

**Comment by kaifeng** [comment]
Not sure it works on xen now but pretty sure logic around it was broken for quite a time.
Speaking about security, I suggest we consider using popular api framework for agent and registrar, they are implementing http service on std lib, which is discouraged in production environment.

**Comment by galmasi** [comment]
I agree with @kaifeng that the logic around deep quote is broken. Add to that the fact that it is not TCG compliant and has serious issues (some were pointed out by @stefanberger a while ago). 

How much of the "provider" keylime infrastructure goes away along with the deep quote? @lhinds I am assuming you are not just referring to the "deepquote" function in tpm_abstract.py

**Comment by stefanberger** [comment]
My criticism about deep quote is how can one establish trust top-down if 'down' may be completely corrupted? If you do it, you have to do it bottom-up, just like the BIOS taking measurements, then the bootloader, then the OS -- all bottom-up.

**Comment by lukehinds** [comment]
To piggy back on this discussion, the deep quote was originally of course for VMs as a workaround (to grab the nearest word) for a lack of no HWRootOfTrust. If anyone has any ideas of an implementation to leverage trust into containers / vms they would like to propose and experiment with in Keylime - I would heartily recommend to go for it. 

We have this work that was trailed out a year ago: https://github.com/keylime/keylime/wiki/VTPM-Design

**Comment by kaifeng** [comment]
My thought on the VM world is treating VMs the same way as Hosts. If we trust swtpm/qemu running at the underlying OS, we should be able to trust the EK Cert (if memory serves, swtpm can do this) as well as the EK goes with it.

**Comment by stefanberger** [comment]
@kaifeng That is if the machine is trusted to be instrumented with trusted boot and IMA (rather than a corrupted machine loading some extends into the pcrs that make it look good) and the recipient of the quote and EK certificate knowing for sure that the VM is located on top of this host (rather than the corrupted host forwarding the quote request to a remote machine).
