### ISSUE TITLE
keylime_client does not work on real tpm

### ISSUE THREAD

**Issue by SeJohnEff** [keylime/keylime#531]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Raspbian
 * Processor architecture: Raspberry pi4
 * TPM Manufacturer: Infienon
 * Keylime version: Latest

# Description 

## Expected behavior vs. actual behavior 
Expected: communication with real tpm
Actual: it does not

## Steps to reproduce problem
1. Install keylime, manual, start keylime client

# Relevant logs
[b'ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI \n', b'ERROR: Could not load tcti, got: "tabrmd:bus_name=com.intel.tss2.Tabrmd"\n']

Attach any relevant log files that can help to debug your issue. 

Solved by commenting  line 39 in tpm2.py " # env['TPM2TOOLS_TCTI'] = 'tabrmd:bus_name=com.intel.tss2.Tabrmd'"
and setting  TPM2TOOLS_TCTI="device:/dev/tpmrm0" (in my .bashrc)

**Comment by SeJohnEff** [comment]
I actually thought that "if 'TPM2TOOLS_TCTI' not in env:" would check env but seems it does not so that is why I simply commented out "env['TPM2TOOLS_TCTI'] = 'tabrmd:bus_name=com.intel.tss2.Tabrmd".
Guess the if case somehow doesn't work.

**Comment by lukehinds** [comment]
hey @SeJohnEff , would you happen to have slack at all? 

If so please jump on the CNCF server: https://cloud-native.slack.com and join the channel #keylime 

We can work quicker to help you on there. I have a pi4 here as well with the same chip. 

If not we can debug in here, but it might take a little longer.

**Comment by SeJohnEff** [comment]
OK, will try

**Comment by SeJohnEff** [comment]
My mistake, no bug
