### ISSUE TITLE
keylime.tpm1 - ERROR

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#549]
This is probably a documentation issue, not a SW bug.

# Environment
 * OS / version: Ubuntu
 * Processor architecture: x86
 * TPM Manufacturer: SW TPM
 * Keylime version: unknown

# Description 

keylime_agent seems to default to TPM 1.2.

## Expected behavior vs. actual behavior 

I expect a way for the agent to target TPM 2.0.

## Steps to reproduce problem

1. Run keylime_agent with no TPM 1.2

# Relevant logs

2021-02-17 15:25:29.411 - keylime.tpm1 - INFO - Failed to call TPM 9/10 times, trying again in 1.000000 seconds...
2021-02-17 15:25:30.429 - keylime.tpm1 - ERROR - TPM appears to be in use by another application.  Keylime is incompatible with other TPM TSS applications like trousers/tpm-tools. Please uninstall or disable.

I assume tpm1 means TPM 1.2, right?  Is there a configuration option to tell the agent to use TPM 2.0.?

Is there documentation on how to configure and run the agent?

**Comment by lukehinds** [comment]
do you also have trousers and the tpm1 env set up?

Here is the code which sets the tpm version to use (Its based on tooling present)

https://github.com/keylime/keylime/blob/1d0f695c0848b001acb0ab01de46094494884506/keylime/tpm/tpm_obj.py#L22-L37

I don't honestly think the above is a good approach, but shortly TPM1 will be removed and so will this code. If you have trousers etc are you OK to remove them from the machine? If not we can find a temp workaround for you.

**Comment by kgold2** [comment]
Thanks for the reply.  That was the issue.  I just remained getcapability.

I agree that it's not a good way to decide - forcing an uninstall.  Perhaps a command line argument to the program or an entry in the configuration file would be better?

**Comment by lukehinds** [comment]
We are just on the verge of removing tpm1 support, so this slip up won't happen again.
