### ISSUE TITLE
keylime_agent is not flushing keys when it completes

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#550]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu
 * Processor architecture: x86
 * TPM Manufacturer: SW TPM
 * Keylime version: unknown

# Description 

keylime_agent is not flushing keys when it completes

## Expected behavior vs. actual behavior 

Expected it to flush all resources when complete.

## Steps to reproduce problem
1. run keylime_agent
2. run it again

After the first run, there are still two loaded transient objects.

# Relevant logs

021-02-17 15:43:10.938 - keylime.tpm2 - INFO - Flushing old ak handle: /var/lib/keylime/secure/tmp7juv4r_2
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/agent.py", line 15, in main
    keylime_agent.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/keylime_agent.py", line 503, in main
    (ek, ekcert, aik, ek_tpm, aik_name) = tpm.tpm_init(self_activate=False, config_pw=config.get(
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 944, in tpm_init
    self.__create_aik()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 676, in __create_aik
    retDict = self.__run(command, outputpaths=akpubfile.name)
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 374, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_createak', '-C', '0x81000000', '-c', '/var/lib/keylime/secure/tmpsdty_lea', '-G', 'rsa', '-g', 'sha256', '-s', 'rsassa', '-u', '/tmp/tmp2zl56wfi', '-f', 'pem', '-p', 'mRvqLQoYo4TwEOLYCCsY', '-P', 'keylime'] returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_Create.c:398:Esys_Create_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x00000902) \n', b'ERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts\n', b'ERROR: Unable to run tpm2_createak\n']

**Comment by lukehinds** [comment]
Apologies this is proving unruly.

I would recommend we clean down the env. Try this:

1. Stop all three servicers (keylime_registrar, keylime_verifier, keylime_agent)
2. `unmount /var/lib/keylime/secure`
3. `rm -r /var/lib/keylime`

Might be worth clearing the state of your vtpm as well and creating a fresh one with swtpm.

After that run the keylime_verifier, keylime_registrar, keylime_agent and let's see what transpires, feel free to post the result in this issue.

**Comment by kgold2** [comment]
Thanks for the post, which answers my "how do I wipe everything and start over" question.

When I do this, I'm back to https://github.com/keylime/keylime/issues/551. Two snips of the long trace are below.

1. How could a TPM 2.0 not have a valid EK?
2. Could it be trying to say that it does not have a valid EK **certificate**?  Should I be provisioning EK certificates?  I can do that.  Does keylime have/need and EK certificate CA, or will any CA do?

------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 869, in verify_ek
    ek509 = M2Crypto.X509.load_cert_der_string(ekcert)
  File "/usr/local/lib/python3.8/dist-packages/M2Crypto/X509.py", line 885, in load_cert_der_string
    cptr = m2.d2i_x509(bio._ptr())
M2Crypto.X509.X509Error: not enough data

---------------

 File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 890, in verify_ek
    raise Exception("Error processing ek/ekcert. Does this TPM have a valid EK?").with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 869, in verify_ek
    ek509 = M2Crypto.X509.load_cert_der_string(ekcert)
  File "/usr/local/lib/python3.8/dist-packages/M2Crypto/X509.py", line 885, in load_cert_der_string
    cptr = m2.d2i_x509(bio._ptr())
Exception: Error processing ek/ekcert. Does this TPM have a valid EK?

**Comment by lukehinds** [comment]
ah yes, good point

In the keylime root directory (of this repo) is a tpm_cert_store, we often put this in /var/lib/keylime, its a configurable value

https://github.com/keylime/keylime/blob/1d0f695c0848b001acb0ab01de46094494884506/keylime.conf#L282-L283

This contains the manufacturer's certificate chain (intermediate certs?). Now with the vtpm you need to get this yourself. Our man @stefanberger can help there, he did point me to a readme, but I am on a different machine now.

The other option is to turn off, `require_ek` in keylime.conf, but this of course turns off all the root of trust, so may not suit your current use.

**Comment by stefanberger** [comment]
@lukehinds From what I am hearing from Ken is that his setup is using tpm_server rather than swtpm. I have never used it so I don't know whether an EK & EK cert is created when tpm_server is used. If running the agent inside a QEMU VM with swtpm attached and started by libvirt I would know where to go for the certs: /var/lib/swtmp-localca. A wiki entry from the swtpm project is [here](https://github.com/stefanberger/swtpm/wiki/Certificates-created-by-swtpm_setup#verifying-your-ek-cert-against-the-ca).

When it comes to this issue here I would recommend 'somehow' restarting both tpm_server and tpm2-abrmd. I haven't run into this particular issue with left-over state myself in the setups I have tried it with.

**Comment by kgold2** [comment]
I've restarted tpm_server many times.  The connection is OK.  In fact, the issue for this PR is that keylime is loading keys and then not cleaning up when it's done.  

However, no matter how many times I restart the TPM, that won't create an EK certificate.  So, what's the process?

(BTW, Stefan sent me to you.)

**Comment by lukehinds** [comment]
ok got it, for the tpm_server we set `require_ek` to `false` , as we never knew of a way of creating an EK in the tpm_server (not making a statement that its not possible, you if anyone would know if it is).

I will try go grab some time today to bring up an instance and make some checks with master against the tpm_server. This was our startup script if its anyuse https://raw.githubusercontent.com/keylime/keylime/master/scripts/tpm_serverd

**Comment by stefanberger** [comment]
I also ran into this context management issue (`tpm:warn(2.0): out of memory for object contexts`) in #602 where I had run the tpm2_tools without tpm2-abrmd. Some of the tools worked and others seem to need tpm2-abrmd to work properly. My system used tpm2-tools v4.3.0. So **maybe** this is related to either the version of the tpm2-tools you are using or a missing tpm2-abrmd?

**Comment by kgold2** [comment]
Ping stalebot

**Comment by mpeters** [comment]
Is there anything else to do here? Did Luke's suggestion of setting `require_ek` to `false` in keylime.conf because you're using tpm_server not work?
