### ISSUE TITLE
keylime_verifier: UnboundLocalError: local variable 'query_all' referenced before assignment

### ISSUE THREAD

**Issue by MartinMa28** [keylime/keylime#554]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 33 Workstation 
 * Processor architecture: x86_64
 * TPM Manufacturer: tpm simulator https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz
 * Keylime version: keylime-5.7.2-2.fc33

# Description 
Seems like a syntax error in the verifier.

## Expected behavior vs. actual behavior 
Expected: Should start
Actual: Failed to start

## Steps to reproduce problem
1. dnf install keylime-5.7.2-2.fc33
2. sudo keylime_verifier

# Relevant logs
Using config file /etc/keylime.conf
2021-02-26 01:08:12.355 - keylime.cloudverifier - ERROR - SQLAlchemy Error: (sqlite3.OperationalError) no such column: verifiermain.ima_whitelist
[SQL: SELECT verifiermain.agent_id AS verifiermain_agent_id, verifiermain.v AS verifiermain_v, verifiermain.ip AS verifiermain_ip, verifiermain.port AS verifiermain_port, verifiermain.operational_state AS verifiermain_operational_state, verifiermain.public_key AS verifiermain_public_key, verifiermain.tpm_policy AS verifiermain_tpm_policy, verifiermain.vtpm_policy AS verifiermain_vtpm_policy, verifiermain.meta_data AS verifiermain_meta_data, verifiermain.ima_whitelist AS verifiermain_ima_whitelist, verifiermain.revocation_key AS verifiermain_revocation_key, verifiermain.tpm_version AS verifiermain_tpm_version, verifiermain.accept_tpm_hash_algs AS verifiermain_accept_tpm_hash_algs, verifiermain.accept_tpm_encryption_algs AS verifiermain_accept_tpm_encryption_algs, verifiermain.accept_tpm_signing_algs AS verifiermain_accept_tpm_signing_algs, verifiermain.hash_alg AS verifiermain_hash_alg, verifiermain.enc_alg AS verifiermain_enc_alg, verifiermain.sign_alg AS verifiermain_sign_alg 
FROM verifiermain]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/bin/keylime_verifier", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/verifier.py", line 15, in main
    cloud_verifier_tornado.main()
  File "/usr/lib/python3.9/site-packages/keylime/cloud_verifier_tornado.py", line 666, in main
    for row in query_all:
UnboundLocalError: local variable 'query_all' referenced before assignment

Attach any relevant log files that can help to debug your issue.

**Comment by lukehinds** [comment]
@mpeters I wonder if this is an alemic issue and we need something in the RPM to handle migrations?

**Comment by lukehinds** [comment]
actually this seems to be present only on 5.7.2

**Comment by mpeters** [comment]
This bug is no longer present in trunk
