### ISSUE TITLE
keylime_agent: Unable to run tpm2_getcap

### ISSUE THREAD

**Issue by MartinMa28** [keylime/keylime#555]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 33 Workstation
 * Processor architecture: x86_64
 * TPM Manufacturer: tpm simulator https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz
 * Keylime version: keylime-6.0.0-1.fc33

# Description 
Seems like keylime_agent cannot run tpm2_getcap.
File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 860, in get_tpm_manufacturer
    retDict = self.__run(["tpm2_getcap", "properties-fixed"])
ERROR: Unable to run tpm2_getcap

## Expected behavior vs. actual behavior 
Expected: agent should start
Actually: agent failed to start

## Steps to reproduce problem
1. dnf install keylime-6.0.0-1.fc33 gcc make openssl-devel
2. mkdir ibmtpm1332 
3. wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz
4. tar -zxvf ibmtpm1332.tar.gz -C ibmtpm1332
5. cd ./ibmtpm1332/src
6. make
7. ./tpm_server
8. open another terminal
9. export TPM2TOOLS_TCTI="mssim:port=2321"
10. sudo keylime_agent

# Relevant logs
Using config file /etc/keylime.conf
2021-02-26 01:22:13.747 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/agent.py", line 15, in main
    keylime_agent.main()
  File "/usr/lib/python3.9/site-packages/keylime/keylime_agent.py", line 498, in main
    (ekcert, ek_tpm, aik_tpm) = instance_tpm.tpm_init(self_activate=False, config_pw=config.get(
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 890, in tpm_init
    self.warn_emulator()
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm_abstract.py", line 123, in warn_emulator
    if self.is_emulator():
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 883, in is_emulator
    return self.get_tpm_manufacturer() == 'SW'
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 860, in get_tpm_manufacturer
    retDict = self.__run(["tpm2_getcap", "properties-fixed"])
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 375, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_getcap', 'properties-fixed'] returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_GetCapability.c:303:Esys_GetCapability_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:107:Esys_GetCapability() Esys Finish ErrorCode (0x00000100) \n', b'ERROR: Esys_GetCapability(0x100) - tpm:error(2.0): TPM not initialized by TPM2_Startup or already initialized\n', b'ERROR: Unable to run tpm2_getcap\n']

Attach any relevant log files that can help to debug your issue.

**Comment by lukehinds** [comment]
@MartinMa28 might have a fix for this, just need to bring up an instance with the ibm emu and verify: https://github.com/keylime/keylime/pull/557

**Comment by lukehinds** [comment]
actually as this is an ibm emulator there is no ek, so you may not need the fix.

run again, but before you do so, change the following value from true to false in /etc/keylime.conf:

`require_ek_cert = False`

going forwards it might better to use the vtpm , if you need the steps to set it up, just let me know in this issue.

**Comment by MartinMa28** [comment]
Sure, if swtpm is a better option compared to ibm emulator for keylime, I do need some help on running swtpm in addition to its wiki. Thanks!

**Comment by MartinMa28** [comment]
In my case, change `require_ek_cert` from `True` to `False` doesn't fix this issue. I am still getting the same error.

**Comment by lukehinds** [comment]
I see the issue now, we have a fix in master for this: https://github.com/keylime/keylime/commit/f54343c33bcd83d704a0683b9f4321a63131a71b

I am going to push out a fedora update asap this morning. 

Hang ten on the vtpm stuff, let me document this for you. If OK with you, you can then validate and review the content to make sure it works 

Sorry about the breakages. we just went up a major release (6.x) and depreciated a lot of code. Things will stabilize a lot more now.  If you ever need more help around issues or how to get the best of keylime we all hang out in the CNCF slack, in there is a keylime channel. You're welcome to join, we also have weekly meetings there. 

https://cloud-native.slack.com/

**Comment by lukehinds** [comment]
@MartinMa28 keylime 6.0.1 is on fedora 32/33/34

To get the swtpm to work, run the following in the same shell as where you start the keylime agent:

```
dnf install -y dbus \
dbus-daemon \
dbus-devel \
swtpm \
swtpm-tools
```

swtpm.sh 

```
#!/bin/bash
set -x

# Configure swtpm2
mkdir /tmp/tpmdir
swtpm_setup --tpm2 \
     --tpmstate /tmp/tpmdir \
     --createek --decryption --create-ek-cert \
     --create-platform-cert \
     --display
swtpm socket --tpm2 \
     --tpmstate dir=/tmp/tpmdir \
     --flags startup-clear \
     --ctrl type=tcp,port=2322 \
     --server type=tcp,port=2321 \
     --daemon
export TPM2TOOLS_TCTI=tabrmd:

# Configure dbus
sudo rm -rf /var/run/dbus
sudo mkdir /var/run/dbus
sudo dbus-daemon --system

tpm2-abrmd \
    --logger=stdout \
    --tcti=swtpm: \
    --flush-all \
    --allow-root &
```

**Comment by lukehinds** [comment]
I will close this for now, please open if you see it again
