### ISSUE TITLE
Remove TPM 1.2 from install script.

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#562]
# Environment
 * OS / version: all
 * Processor architecture: all
 * TPM Manufacturer: all
 * Keylime version: master

# Description 

installer.sh contains a flag to install with 'modern libraries' (which means 2.0), tpm1.2 is deprecated, so this needs removal.

**Comment by mpeters** [comment]
TPM 1.2 stuff has been removed from the installer
