### ISSUE TITLE
Automated installer fails on Build and install tpm2-tools

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#570]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: ubuntu 20
 * Processor architecture: x86
 * TPM Manufacturer: sw tpm
 * Keylime version: master

# Description 

Automated installer fails on Build and install tpm2-tools

## Expected behavior vs. actual behavior 

Expected no error

## Steps to reproduce problem

./installer.sh -o -m

# Relevant logs

tss:

config.status: creating Makefile
config.status: creating Doxyfile
config.status: executing libtool commands
config.status: executing depfiles commands
config.status: error: in `/tmp/tmp.gw9rr8aFlE/tpm/tpm2-tss':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
Makefile:14664: *** missing separator.  Stop.
Makefile:14664: *** missing separator.  Stop.
/tmp/tmp.gw9rr8aFlE/tpm

**Comment by lukehinds** [comment]
This looks like an upstream issue in there Makefile, I don't think there is much we can do in our installer (although thanks for flagging it up). I wonder if we should switch ubuntu / debian to using apt-get for install tss/tools etc (the last time this was looked at ubuntu / debian packaging was running very old versions).

**Comment by kgold2** [comment]
Pinging stalebot.

**Comment by mpeters** [comment]
We should now be installing tpm2-tools, etc using the system packages, so this should be fixed.
