### ISSUE TITLE
Pythin on ubuntu 16 xenial

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#574]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: ubuntu 16
 * Processor architecture: x86
 * TPM Manufacturer: na
 * Keylime version: master

# Description 

Keylime expects a version of python that is not available.  The documentation needs to include a remediation or work arounnd.

## Expected behavior vs. actual behavior 

Expected no install error, got install error.

## Steps to reproduce problem
1. Download keylime master
2. Use apt to update the platform
3. ./installer.sh -o -m

# Relevant logs

ERROR: Minimum Python version is 3.6.7, but 3.5.2 is installed!
This may introduce security issues, instability or an incomplete install!  Continue? [y/N] y
-c:1: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.

**Comment by stefanberger** [comment]
Ubuntu 16.04 is likely too old at this point.

This is from installer.sh:
```
[...]
# Minimum version requirements
MIN_PYTHON_VERSION="3.6.7"
[...]
```

So, something may have driven the minimum python version requirement to 3.6.7. It looks like this patch here did that:

```
commit b39d2824ffe0768daec2161e328a04d80e569108
Author: Luke Hinds <lhinds@redhat.com>
Date:   Thu Jun 13 09:59:17 2019 +0100

    Python 3 Port
[...]
@@ -35,7 +35,7 @@ TPM2TSS_VER="2.0.x"
 TPM2TOOLS_VER="3.X"

 # Minimum version requirements
-MIN_PYTHON_VERSION="2.7.10"
+MIN_PYTHON_VERSION="3.6.7"
 MIN_PYSETUPTOOLS_VERSION="0.7"
 MIN_PYTORNADO_VERSION="4.3"
 MIN_PYM2CRYPTO_VERSION="0.21.1"
```

Whether that's a hard requirement, as in 'doesn't work with 3.6.6`, is not clear, but bionic-updates (Ubuntu 18.04) has this particular version of python3: https://packages.ubuntu.com/search?suite=bionic-updates&arch=any&searchon=names&keywords=python3

**Comment by kgold2** [comment]
Please don't, stalebot.

**Comment by THS-on** [comment]
@kgold2 now that even Python 3.6 is EOL and we generally targeting 3.6 as the minium version (and also our dependencies), I think this can be closed. We will probably not going to start supporting Python 3.5.

The README also includes a note that Python 3.6 or grater is required: https://github.com/keylime/keylime#installer-script

cc: @mpeters
