### ISSUE TITLE
RHEL 7.9 python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#581]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: RHEL 7.9
 * Processor architecture: x86
 * TPM Manufacturer: n/a
 * Keylime version: master

# Description 

python3 -m pip install -r requirements.txt fails

## Expected behavior vs. actual behavior 

Expected success, got error.

## Steps to reproduce problem
1. python3 -m pip install -r requirements.txt

# Relevant logs

Collecting cryptography>=2.9 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lxm9qhgg/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lxm9qhgg/cryptography/

**Comment by stefanberger** [comment]
I ran into a similar problem today and could avoid it by running the following on Fedora 32:

```
sudo pip3 install --update cryptography==3.0.0
```

I had cryptography already installed and this put it to v3.0.0 and satisfied the cryptography>=2.9 requirement from requirements.txt, thus not triggering the pip install/update that is part of Keylime's install.sh file. The error you are running into seems like a dependency issue of the cryptography package... I hope this helps.

**Comment by stefanberger** [comment]
3.3.2 is the last 3.3.x version at the moment and it works:

```
# sudo pip3 install cryptography==3.3.2
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting cryptography==3.3.2
  Using cached https://files.pythonhosted.org/packages/32/48/ec2a3e98d8b61d2c65e4c6905aad370049c4bd4a6b1b1d78f8983d38effe/cryptography-3.3.2-cp36-abi3-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/site-packages (from cryptography==3.3.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography==3.3.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography==3.3.2)
Installing collected packages: cryptography
  Found existing installation: cryptography 3.3
    Uninstalling cryptography-3.3:
      Successfully uninstalled cryptography-3.3
Successfully installed cryptography-3.3.2
```

`cryptography==3.4.6` does not work for me even after installing setuptools_rust due to this error here:

```
[...]
    If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

    This package requires Rust >=1.41.0.

    ----------------------------------------
  Rolling back uninstall of cryptography
[...]
```

**Comment by mpeters** [comment]
So should we bump up the requirement for cryptography to 3.3.2?

**Comment by stefanberger** [comment]
If we need to install we should probably only install 3.3.2 to avoid the rust issues.

**Comment by kgoldman** [comment]
> 
> 
> So should we bump up the requirement for cryptography to 3.3.2?

I think the question has to roll back to a marketing approach - "what versions of what distros should keylime run on?"  Is it expected to run broadly or on just a specified set of distros and versions.

If broadly, it has to run on older versions of python packages.  If restricted, it would be very useful to document those requirements.

**Comment by mpeters** [comment]
I ran into an issue today where CentOS 7 didn't have a package of the python3 gnupg module and that kind of situation is only going to get worse. Keylime is new enough that I don't feel we need to support older versions of dependencies or operating systems.

**Comment by kgoldman** [comment]
Like I said, this seems like a marketing decision.  I don't know Centos, but wikipedia says EOL 2024.  I know systems that are still using RHEL 7.

**Comment by mpeters** [comment]
You're right that product people might have different ideas, but just because RHEL/CentOS is supported until 2024 doesn't mean all new software will be supported on those platforms. It just means that existing software will continue to be supported. They get bug and security fixes but not usually new features. And keylime is definitely a new feature

**Comment by mpeters** [comment]
This issue should be fixed by https://github.com/keylime/keylime/pull/598

**Comment by kgoldman** [comment]
> just because RHEL/CentOS is supported until 2024 doesn't mean all new software will be supported on those platforms

To me, keylime is in a different category than a word processor or browser.  It's monitoring software.  I can easily understand requiring the verifier side to be a recent distro.  However, can keylime say to a data center that it can only monitor 20% of their machines?
