### ISSUE TITLE
keylime_agent broken for non-x86_64 architectures due to libefivar.so not being available

### ISSUE THREAD

**Issue by stefanberger** [keylime/keylime#582]
# Environment
 * OS / version: Fedora 32
 * Processor architecture: PowerPC64
 * TPM Manufacturer: Nuvoton
 * Keylime version: today's master (1766957a748140d6040df70f)

# Description 

The keylime_agent fails to start on ppc64. The needed package providing the library is not available on this platform.

```
# keylime_agent                       
Using config file /etc/keylime.conf
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/keylime/cmd/agent.py", line 9, in <module>
    from keylime import keylime_agent
  File "/usr/local/lib/python3.8/site-packages/keylime/keylime_agent.py", line 37, in <module>
    from keylime.tpm.tpm_main import tpm
  File "/usr/local/lib/python3.8/site-packages/keylime/tpm/tpm_main.py", line 26, in <module>
    from keylime import tpm_bootlog_enrich
  File "/usr/local/lib/python3.8/site-packages/keylime/tpm_bootlog_enrich.py", line 50, in <module>
    efivarlib_functions = CDLL(efivarlib)
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libefivar.so: cannot open shared object file: No such file or directory
```

## Expected behavior vs. actual behavior 

keylime_agent should work

## Steps to reproduce problem
1. See above

**Comment by mpeters** [comment]
@maugustosilva It seems that requiring libefivar just for `tpm_bootlog_enrich()` means it gets pulled in for the agent, which we don't want. Can we change `tpm_main` to dynamically load `tpm_bootlog_enrich`  just in calls to `parse_binary_bootlog`? This should remove the need for the agent to depend on a lib it doesn't use.

**Comment by stefanberger** [comment]
On Fedora efivar-libs-37-14 has this content

```
$ rpm -q --list efivar-libs
/usr/lib/.build-id
/usr/lib/.build-id/e5
/usr/lib/.build-id/e5/7a921d131d6238a68eab784c1847e9831f3234
/usr/lib/.build-id/f8
/usr/lib/.build-id/f8/d95982f367c6cc0eea3b7c22b62d285c46f106
/usr/lib64/libefiboot.so.1
/usr/lib64/libefiboot.so.1.37
/usr/lib64/libefivar.so.1
/usr/lib64/libefivar.so.1.37
```

Only efivar-devel has the symlink /usr/lib64/libefivar.so but this one is typically not installed.

```
$ rpm -q --list efivar-devel
[..]
/usr/lib64/libefiboot.so
/usr/lib64/libefivar.so
[...]
```
also see: https://fedora.pkgs.org/33/fedora-x86_64/efivar-libs-37-14.fc33.x86_64.rpm.html
and here: https://fedora.pkgs.org/33/fedora-x86_64/efivar-devel-37-14.fc33.x86_64.rpm.html

So, on Fedora you may have try to to load libefivar.so.1 and if that fails short-out the rest of tpm_bootlog_enrich.py. This would then probably also solve it for other architectures that do also not have the library.

I installed both of these libraries now on a Fedora 33 system with SeaBIOS and it doesn't affect the start of keylime_agent.
