### ISSUE TITLE
Occasional tpm2_quote failures

### ISSUE THREAD

**Issue by stefanberger** [keylime/keylime#585]
# Environment
 * OS / version:  Fedora 32 
 * Processor architecture: PowerPC64
 * TPM Manufacturer: Nuvoton
 * Keylime version: git master ()
 * tpm2-tools: 4.1.3-1.fc32

# Description 

I see occassional tpm2_quote failures. I don't know what is causing these failures. Maybe it's activity on the system, but that's just a guess.

```
2021-03-14 20:11:18.695 - keylime.cloudagent - INFO - GET identity quote returning 200 response.
2021-03-14 20:11:18.727 - keylime.cloudagent - INFO - POST of U key returning 200
----------------------------------------
Exception happened during processing of request from ('9.47.152.88', 48098)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib64/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/keylime/keylime_agent.py", line 117, in do_GET
    quote = tpm_instance.create_quote(
  File "/usr/local/lib/python3.8/site-packages/keylime/tpm/tpm_main.py", line 953, in create_quote
    retDict = self.__run(command, lock=False, outputpaths=[quotepath.name, sigpath.name, pcrpath.name])
  File "/usr/local/lib/python3.8/site-packages/keylime/tpm/tpm_main.py", line 377, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_quote', '-c', '/var/lib/keylime/secure/tmpqyd2ekl5', '-l', 'sha256:15,16,22+sha1:10', '-q', '6354674e68713748624e4c4f526e675674656f4c', '-m', '/tmp/tmp5xn_gcxw', '-s', '/tmp/tmpu55gzfrh', '-o', '/tmp/tmpib6xl8b8', '-g', 'sha256', '-p', 'U6r1jVs7WS6Du5JfG3AC'] returned 1, expected 0, output [b'quoted: ff54434780180022000bf6a403972502b28e39c78e3da485ff790ca2991707d02c3a0b365cfbcee3210100146354674e68713748624e4c4f526e675674656f4c000000038d0efbb0000000910000000001000100030001000000000002000b0300804100040300040000207895a3e620508e67809b15af29417490ce97b491bf689a247722bac42c61a995\n', b'signature:\n', b'  alg: rsassa\n', b'  sig: 2f5fc43b85b17e71a31e871eff35ad4358fa5ff3c5ffc40964c196a353149961318f72fb8f613d3de0af92b38628dc93e86a88a6bf41a701bac02f78f87b439e32a8109abf9e2977f41dcf3d954b50643fae740acdec1190ce92da5e0dda27405021a22cd22b8322a9b8d34414a367e7036737a3da0b114c1c9474cef8b482acab097d702b811b24c9192f5f7c36b18fbf56ff7b245f08b9e4f9ad5500fc94e0578fbd7b1732af29ad5275918f75541861413b4294ff842f17076f5cd956f67bb5f61ae768eeb0216e18e74adb6d9613518b4e713742f03d394217b74c810be6826ead399472bcdbe61b53d1d0695fe8d311f24ee1c5c354bf06fb0a51b40ca3\n', b'pcrs:\n', b'  sha256:\n', b'    15: 0x0000000000000000000000000000000000000000000000000000000000000000\n', b'    16: 0x31A7885516F1F8A893B5B5468F18CE0EFE81A61BF47046DA06F3C2E59943E45F\n', b'    22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n', b'  sha1:\n', b'    10: 0xBA2060B6585594E7CD0B5EA3CD0D18AA7F2B0414\n', b'calcDigest: 669b824850eec41ee91c27524dbfed0a5f570cfdefda6b5543ea9747c5959acb\n'], stderr [b"ERROR: FATAL ERROR: PCR values failed to match quote's digest!\n", b'ERROR: Error validating calculated PCR composite with quote\n', b'ERROR: Unable to run tpm2_quote\n']
----------------------------------------
$ rpm -q --whatprovides `which tpm2_quote`
tpm2-tools-4.1.3-1.fc32.ppc64le
```

## Expected behavior vs. actual behavior 

tpm2_quote should always work.

The sha1 and sha256 banks seems to be active on this system:

```
$ tpm2_pcrread 
sha1:
  0 : 0xD0CC41E11CB1BF728BF3311CEE1B4F2BB7FEFC37
  1 : 0x4042FB3D00D0528DA9F44A44F0604AD8C8104F90
  2 : 0xF719CE202DB9DA46E7FAA9C1A82BD0C338B43399
  3 : 0xF719CE202DB9DA46E7FAA9C1A82BD0C338B43399
  4 : 0x0CA90DB82918E1212DCA9912822C0FF9DA23E9CC
  5 : 0x64BA7DD01CCB6F7D35143B64D2EF3F82C306C416
  6 : 0xC702A4BC41521737BABE95F38C0DA40F070C2FAD
  7 : 0xF719CE202DB9DA46E7FAA9C1A82BD0C338B43399
  8 : 0x0000000000000000000000000000000000000000
  9 : 0x0000000000000000000000000000000000000000
  10: 0xF4EE742EBBB59400C02CE9D4872173207E71E793
  11: 0x0000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000
  14: 0x0000000000000000000000000000000000000000
  15: 0x0000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000
sha256:
  0 : 0x0CBDED4E1B11F1AECD1B97BF54A067D00B97CB50DF828D1805A265D3DF460C7F
  1 : 0x54810D396803952AFF9AB362783F6BA71A4812248D13855C8BDADBFA6F005340
  2 : 0x76A21EBF19B31966352D4A088AC058DA21D84CC60078E094958BB56C37715DC1
  3 : 0x76A21EBF19B31966352D4A088AC058DA21D84CC60078E094958BB56C37715DC1
  4 : 0xDD8B850BE84748096648879ADC8EFE6DE61A488F594148B546B949A4BFA33ED7
  5 : 0x22C854242808E381E994EBAF3DAA7B88E9CD172F3DE0A369F3D310F0FE9FB4E2
  6 : 0x82A01B2D435174D394CDF8D84F3F8BD0C2CE2B0AE861007836C9F81199C0A09B
  7 : 0x76A21EBF19B31966352D4A088AC058DA21D84CC60078E094958BB56C37715DC1
  8 : 0x0000000000000000000000000000000000000000000000000000000000000000
  9 : 0x0000000000000000000000000000000000000000000000000000000000000000
  10: 0x9AB1F6DF98EEA5C09B274FDA477793797F77C7F48345CABB53EFB8267176E010
  11: 0x0000000000000000000000000000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000000000000000000000000000
  14: 0x0000000000000000000000000000000000000000000000000000000000000000
  15: 0x0000000000000000000000000000000000000000000000000000000000000000
  16: 0x31A7885516F1F8A893B5B5468F18CE0EFE81A61BF47046DA06F3C2E59943E45F
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by stefanberger** [comment]
On the `tpm2_quote` side, run by  the keylime_agent, one would have to repeat the retrieval of the PCR values and quote until they match. On a busy system this could take a while but it's not quite clear why the checking is done in the first place. Are we not trusting the quote done by the TPM 2? What are we gaining from this? However, it seems necessary that we transmit the PCR values (along with the quote) to the verifier since on the verifier side we are running `tpm2_checkquote` that does the same thing again of checking the read PCRs against the quote. It seems unnecessary since the quote is presumably signed by a trusted TPM key, or do we have doubts about the validity of  the quote?? If so, replaying PCR values doesn't gain much.

**Comment by stefanberger** [comment]
... Though when walking the list of (IMA) measurements one has to know the PCR (10) value of the TPM at the time of the quote, so it does seem necessary to have a trusted value here, which is more complicated to come by when multiple PCRs are quoted, as is the case here (`sha256:15,16,22+sha1:10`; what  is in pcr15, 16 and 22?). I guess the only way to fix this is in the tpm2_quote tool or on the agent side repeating the tpm2_quote until it succeeds.

**Comment by stefanberger** [comment]
Quoting and PCR retrieval are two distinct operations that may have problems on a busy system unless they were to be executed atomically, meaning nothing can come in between the quote and the PCR retrieval, but this is not possible today. If we have a system with lots of IMA measuring activity, such as may be the case during boot or when a large application is started up, the current tpm2_quote tool will not work since the PCRs and the quote won't 'match' until the system has settled, which may be several seconds later. What I see at the moment is that when the system is busy the keylime agent passes the tpm2_quote error on to the verifier and the verifier then reports this error and stops monitoring the system. I don't know whether there's an option to work around this issue...

**Comment by stefanberger** [comment]
@mpeters @puiterwijk @maugustosilva @lukehinds @kaifeng Is there a tolerance knob to turn on that allows tpm2_quote failures on the agent side? From what I have seen on the verifier side is that it gives up monitoring a system if the tpm2_quote failed on the agent side. tpm2_quote will have PCR matching failures on a system with activity on the host and this will also prevent it from activating the agent earlier during the boot process when lots of processes are starting up.

**Comment by mpeters** [comment]
@stefanberger there isn't a tolerance knob that I'm aware of, but given the problem you've laid out it does seem like something like that might be necessary

**Comment by stefanberger** [comment]
I haven't used it with measured boot so far. Are the measured boot PCRs included in any quote?

There are a couple of choices:

1. introduce a per-agent tolerance counter on the verifier side and ignore up to n consecutive failures until declaring a system as untrusted
2. modify tpm2_quote to loop over retrieving quote and PCRs until a match has been found or a maximum of x times; this can delay tpm2_quote results for a long time until the system has 'settled' or may still lead to tpm2_quote failures ...
3. only get a quote over PCR 10 (and a separate quote for all other PCRs involved in measured boot?) and ignore the actual PCR 10 value; when walking the measurement list replay the PCR 10 extensions and rebuild the hash what was quoted; stop when the measurement that had the state of PCR 10 at quote time was reached; if it is never reached then something was wrong on that system (measurement list must be retreived after the quote on the agent side); we cannot use tpm2_quote anymore and with that also not tpm2_checkquote then on the verifier side and should probably replace these tools (possibly others) with a native python implementation; the consequence is also that over-the wire data changes and interoperability between versions of keylime will be lost, iff that was to be an issue
4. ? anything else

Now the matching exercise is to match the words 'hack', 'bandaid', and 'possible solution' to the above

**Comment by mpeters** [comment]
> I haven't used it with measured boot so far. Are the measured boot PCRs included in any quote?

Probably a question for @maugustosilva and crew

> 
> There are a couple of choices:
> 
> 1. introduce a per-agent tolerance counter on the verifier side and ignore up to n consecutive failures until declaring a system as untrusted

Does this make things less secure? Would it create a window where a system could be compromised but then shimmed up in a way to pretend to not be compromised later? I can't think of a scenario that would work since if it passes quote checks in the future it means past failures weren't really failures.

> 2. modify tpm2_quote to loop over retrieving quote and PCRs until a match has been found or a maximum of x times; this can delay tpm2_quote results for a long time until the system has 'settled' or may still lead to tpm2_quote failures ...

Are we talking on the agent side before it sends the quote, or on the verifier side requesting it multiple times before it makes a ruling?

> 3. only get a quote over PCR 10 (and a separate quote for all other PCRs involved in measured boot?) and ignore the actual PCR 10 value; when walking the measurement list replay the PCR 10 extensions and rebuild the hash what was quoted; stop when the measurement that had the state of PCR 10 at quote time was reached; if it is never reached then something was wrong on that system (measurement list must be retreived after the quote on the agent side); we cannot use tpm2_quote anymore and with that also not tpm2_checkquote then on the verifier side and should probably replace these tools (possibly others) with a native python implementation; the consequence is also that over-the wire data changes and interoperability between versions of keylime will be lost, iff that was to be an issue

I seem to remember a discussion about this in the not too distant past. I like this because it's not delaying notification for a compromised system, but it does increase the complexity on the verifier side which in turns gives more places for us to get it wrong.

> 4. ? anything else

A combination of some, or all of the above? Right now I'm leaning toward thinking 1+3 would actually be pretty robust.

> Now the matching exercise is to match the words 'hack', 'bandaid', and 'possible solution' to the above

Well, when you're trying to perform atomic operations in a system that doesn't support them... those are the words that are used a lot to describe it

**Comment by kgold2** [comment]
Long term, the solution is straightforward (and has already implemented and tested).  Ignore the TPM's PCRs - they add no value.  Verify the quote hash against the event logs.  This just works.

Any looping solution will be unreliable and perform poorly.

**Comment by maugustosilva** [comment]
> > I haven't used it with measured boot so far. Are the measured boot PCRs included in any quote?
> 
> Probably a question for @maugustosilva and crew
> 
> > There are a couple of choices:
> > 
> > 1. introduce a per-agent tolerance counter on the verifier side and ignore up to n consecutive failures until declaring a system as untrusted
> 
> Does this make things less secure? Would it create a window where a system could be compromised but then shimmed up in a way to pretend to not be compromised later? I can't think of a scenario that would work since if it passes quote checks in the future it means past failures weren't really failures.
> 
> > 1. modify tpm2_quote to loop over retrieving quote and PCRs until a match has been found or a maximum of x times; this can delay tpm2_quote results for a long time until the system has 'settled' or may still lead to tpm2_quote failures ...
> 
> Are we talking on the agent side before it sends the quote, or on the verifier side requesting it multiple times before it makes a ruling?
> 
> > 1. only get a quote over PCR 10 (and a separate quote for all other PCRs involved in measured boot?) and ignore the actual PCR 10 value; when walking the measurement list replay the PCR 10 extensions and rebuild the hash what was quoted; stop when the measurement that had the state of PCR 10 at quote time was reached; if it is never reached then something was wrong on that system (measurement list must be retreived after the quote on the agent side); we cannot use tpm2_quote anymore and with that also not tpm2_checkquote then on the verifier side and should probably replace these tools (possibly others) with a native python implementation; the consequence is also that over-the wire data changes and interoperability between versions of keylime will be lost, iff that was to be an issue
> 
> I seem to remember a discussion about this in the not too distant past. I like this because it's not delaying notification for a compromised system, but it does increase the complexity on the verifier side which in turns gives more places for us to get it wrong.
> 
> > 1. ? anything else
> 
> A combination of some, or all of the above? Right now I'm leaning toward thinking 1+3 would actually be pretty robust.
> 
> > Now the matching exercise is to match the words 'hack', 'bandaid', and 'possible solution' to the above
> 
> Well, when you're trying to perform atomic operations in a system that doesn't support them... those are the words that are used a lot to describe it

so @mdrocco wrote a couple of patches with the intent of solving (or at least alleviating) the problems with `PCR 10` and `IMA` log being out of sync. His patch greatly reduced the amount of attestation errors but I have been seeing occasional errors on my (for now, reduced to 4K agents) scalability testbed. 

I still believe the problem only manifests itself with `IMA` enabled on keylime, at least on my experience.

**Comment by kgold2** [comment]
"I can't think of a scenario that would work since if it passes quote checks in the future it means past failures weren't really failures."
Correct.  It would not be nice if a fully secured system was reported as failing because of a bug in the verifier.

"His patch greatly reduced the amount of attestation errors but I have been seeing occasional errors on my (for now, reduced to 4K agents) scalability testbed."
I would expect occasional errors because the quote and PCR read are not atomic.

"I still believe the problem only manifests itself with IMA enabled on keylime, at least on my experience."
That's because there are no quotes during pre-OS.  The quotes only happen post-OS. It's not an IMA issue.  IMA is fine.  It's a keylime issue.  

The fix is well-known.  Don't verify against PCRs.

**Comment by stefanberger** [comment]
It seems we are quoting PCRs 0-9 + 10 + 11-15. We can replay logs for 0-9 probably from bios measurements 10 from IMA log. But what is logging 11 - 15 so that these  could be replayed and used in a quote verification?

**Comment by maugustosilva** [comment]
@stefanberger right, PCRs 0-9 can be rebuilt from tpm2 event log sent by the `keylime agent` , PCR 10 from the IMA log (thanks to @mdrocco patch on keylime, we keep checking if we get a match for PCR 10 before the end of IMA log sent by the agent: this greatly reduced the number of quote errors) and PCRs 11-15 are theoretically used by some disk encryption OS tools (e.g., I believe Windows BitLocker uses PCR 11). We added these latter mostly for completeness, given that on our current production deployments, they remain unextended.

**Comment by maugustosilva** [comment]
> 
> 
> > I haven't used it with measured boot so far. Are the measured boot PCRs included in any quote?
> 
> Probably a question for @maugustosilva and crew
> 
> > There are a couple of choices:
> > 
> > 1. introduce a per-agent tolerance counter on the verifier side and ignore up to n consecutive failures until declaring a system as untrusted
> 
> Does this make things less secure? Would it create a window where a system could be compromised but then shimmed up in a way to pretend to not be compromised later? I can't think of a scenario that would work since if it passes quote checks in the future it means past failures weren't really failures.
> 
> > 1. modify tpm2_quote to loop over retrieving quote and PCRs until a match has been found or a maximum of x times; this can delay tpm2_quote results for a long time until the system has 'settled' or may still lead to tpm2_quote failures ...
> 
> Are we talking on the agent side before it sends the quote, or on the verifier side requesting it multiple times before it makes a ruling?
> 
> > 1. only get a quote over PCR 10 (and a separate quote for all other PCRs involved in measured boot?) and ignore the actual PCR 10 value; when walking the measurement list replay the PCR 10 extensions and rebuild the hash what was quoted; stop when the measurement that had the state of PCR 10 at quote time was reached; if it is never reached then something was wrong on that system (measurement list must be retreived after the quote on the agent side); we cannot use tpm2_quote anymore and with that also not tpm2_checkquote then on the verifier side and should probably replace these tools (possibly others) with a native python implementation; the consequence is also that over-the wire data changes and interoperability between versions of keylime will be lost, iff that was to be an issue
> 
> I seem to remember a discussion about this in the not too distant past. I like this because it's not delaying notification for a compromised system, but it does increase the complexity on the verifier side which in turns gives more places for us to get it wrong.
> 
> > 1. ? anything else
> 
> A combination of some, or all of the above? Right now I'm leaning toward thinking 1+3 would actually be pretty robust.
> 
> > Now the matching exercise is to match the words 'hack', 'bandaid', and 'possible solution' to the above
> 
> Well, when you're trying to perform atomic operations in a system that doesn't support them... those are the words that are used a lot to describe it

@mpeters @stefanberger would this per-agent tolerance counter (option 1) be kept in memory? If in memory, we need to deal with `verifier` restarts, if on db, we would be introducing a "historical" information which cannot be rebuilt from the information accessed from `agent` and `registrar` 

@mpeters before we consider long term solutions, I believe should instrument the `verifier` code to log the actual reason for the attestation error, including PCR # and source of validation data (e.g., event log, IMA log, individual PCR policy).

**Comment by stefanberger** [comment]
> @mpeters @stefanberger would this per-agent tolerance counter (option 1) be kept in memory? If in memory, we need to deal with `verifier` restarts, if on db, we would be introducing a "historical" information which cannot be rebuilt from the information accessed from `agent` and `registrar`

I would think it can be long-term statless, so no entry in the database. Option 3 would obsolete option 1 anyway since it should never lead to quote+PCR-retrieval-mismatch-failures.

**Comment by stefanberger** [comment]
> @stefanberger right, PCRs 0-9 can be rebuilt from tpm2 event log sent by the `keylime agent` , PCR 10 from the IMA log (thanks to @mdrocco patch on keylime, we keep checking if we get a match for PCR 10 before the end of IMA log sent by the agent: this greatly reduced the number of quote errors) and PCRs 11-15 are theoretically used by some disk encryption OS tools (e.g., I believe Windows BitLocker uses PCR 11). We added these latter mostly for completeness, given that on our current production deployments, they remain unextended.

An extended PCR without a log that goes with it would be difficult to reason about what the state of the PCR means. I don't see why they are included in the quote.

**Comment by stefanberger** [comment]
The mechanisms for option 1 are actually there on the keylime_agent side, but they don't work.

The reported error looks like this (after some instrumentation):

```
2021-03-19 17:15:16.896 - keylime.tpm - INFO - fptr=tpm2_quote, reterr=[b"ERROR: FATAL ERROR: PCR values failed to match quote's digest!\n", b'ERROR: Error validating calculated PCR composite with quote\n', b'ERROR: Unable to run tpm2_quote\n']
```

The code in tpm_main.py looks like this:

```
           # keep trying to get quote if a PCR race condition occurred in deluxe quote
            logger.info("fptr=%s, reterr=%s\n" %(fprt, reterr))
            if fprt == "tpm2_quote" and "Error validating calculated PCR composite with quote" in reterr:
                numtries += 1
```

reterr is an array. PR sent.

**Comment by stefanberger** [comment]
Wit the fix merged I think we are good for now.
