### ISSUE TITLE
Missing: PGP-signed signature verification keys and downloadable signature verification keys

### ISSUE THREAD

**Issue by stefanberger** [keylime/keylime#595]
This is likely an enhancement but we can discuss this here first before I formally file an enhancement request.

@mpeters , @puiterwijk Would it make sense to add similar extensions you have done for the allowlist for the signature verification keys as well, such as  URL to download the signature verification key(s) and a PGP file with a signature for the key file? Can you use this as a basis for the integration with signed files on the 'compose side' (OSTree) as well?

**Comment by mpeters** [comment]
Yes, I like that idea. I don't know what it would take to have that implemented on the OSTree side though.

**Comment by stefanberger** [comment]
This may be a detail at this point but nevertheless I am wondering how to support multiple remote keys and remote signatures for some of those keys. The agent currently supports providing multiple keys/key files, so this should probably also be supported for remote keys:

```
--sign_verification_key_url https://server.com/path/to/key \
    --sign_verification_key_signature_url https://server.com/path/to/key/signature \
    --sign_verification_key_signature_key gpg_key_file \
--sign_verification_key_url https://server.com/path/to/key2
```

I guess the rule could be that if keys have signatures they have to be listed first along with their signature URLs and the key to use for verification.

Also note, I used `_` instead of `-` between the option's words.

**Comment by stefanberger** [comment]
PR #597 addressed the issue
