### ISSUE TITLE
keylime_webapp - no GUI, just json

### ISSUE THREAD

**Issue by kgoldman** [keylime/keylime#605]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: fedora 32
 * Processor architecture: x86
 * TPM Manufacturer: na
 * Keylime version: latest master

# Description 

May be related to https://github.com/keylime/keylime/issues/519.  I applied that patch.

## Expected behavior vs. actual behavior 

Expected GUI.  Got json.  This worked (with the patch) before downloading the latest master.

## Steps to reproduce problem

1. Download latest master and install
1. Start keylime_webapp
2. Browse https://localhost/webapp/

# Relevant logs

webapps: {"code": 500, "status": "Internal Server Error", "results": {}}

agents: {"code": 200, "status": "Success", "results": {"uuids": ["D432FBB3-D2F1-4A97-9EF7-75BD81C00000"]}}

/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

logs: {"code": 400, "status": "uri not supported", "results": {}}

2021-03-31 08:50:18.525 - keylime.tenant_webapp - WARNING - GET returning 400 response. uri not supported: /logs/

2021-03-31 08:50:18.525 - keylime.tenant_webapp - WARNING - GET returning 400 response. uri not supported: /logs/

**Comment by stefanberger** [comment]
Can you try again with latest code from master?

**Comment by kgold2** [comment]
> Can you try again with latest code from master?

webapp now shows the GUI.  agents and logs are still showing just json.

**Comment by stefanberger** [comment]
A git revert of e23b9f resolved that issue for me now:

`git revert e23b9f`

```
commit e23b9fc79ef3baaa4d7f3cae7fae9975ebc3b2e0
Author: root <root@localhost.localdomain>
Date:   Wed Mar 24 13:17:48 2021 -0400

    Add support for keylime_webapp service to read intervals from keylime.conf
    
    Signed-off-by: root <root@localhost.localdomain>
```

@mpeters Who added this patch?

**Comment by stefanberger** [comment]
I deleted my previous comment. It works for me now. I had to add missing variables to /etc/keylime.conf's webapp section:

```
# The intervals for populating agents, updating agents and updating terminal.
populate_agents_interval = 4000
update_agents_interval = 1500
update_terminal_interval = 2000
```

Not sure why it wasn't updated. But if these variables are missing, nothing works.

The log now shows this here repeating forever:

```
 InsecureRequestWarning,
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by stefanberger** [comment]
@kgoldman  @kgold2 
> # Relevant logs
> 
> webapps: {"code": 500, "status": "Internal Server Error", "results": {}}
> 
> agents: {"code": 200, "status": "Success", "results": {"uuids": ["D432FBB3-D2F1-4A97-9EF7-75BD81C00000"]}}
> 
[...]
> 
> logs: {"code": 400, "status": "uri not supported", "results": {}}
> 
> 2021-03-31 08:50:18.525 - keylime.tenant_webapp - WARNING - GET returning 400 response. uri not supported: /logs/
> 
> 2021-03-31 08:50:18.525 - keylime.tenant_webapp - WARNING - GET returning 400 response. uri not supported: /logs/

These two URLS (`/agents/` and `/logs/`) are REST API URLs as documented here: https://keylime-docs.readthedocs.io/en/latest/rest_apis.html#tenant-webapp

The REST APIs won't return html.

Here's how they are registered:

https://github.com/keylime/keylime/blob/master/keylime/tenant_webapp.py#L712-L719

```
    app = tornado.web.Application([
        (r"/webapp/.*", WebAppHandler),
        (r"/(?:v[0-9]/)?agents/.*", AgentsHandler),
        (r"/(?:v[0-9]/)?logs/.*", AgentsHandler),
        (r'/static/(.*)', tornado.web.StaticFileHandler,
         {'path': root_dir + "/static/"}),
        (r".*", MainHandler),
    ])
```

This is the code for the `/webapp/` URL:

https://github.com/keylime/keylime/blob/master/keylime/tenant_webapp.py#L95-L319

```
class WebAppHandler(BaseHandler):
    def head(self):
        """HEAD not supported"""
        config.echo_json_response(self, 405, "HEAD not supported")

    def get(self):
        """This method handles the GET requests to retrieve status on agents for all agents in a Web-based GUI.
        Currently, only the web app is available for GETing, i.e. /webapp. All other GET uri's
        will return errors.
        """
```

This one returns html here: https://github.com/keylime/keylime/blob/master/keylime/tenant_webapp.py#L123-L316
