### ISSUE TITLE
Bug report: keylime_tenant -c reglist now requires a "-t" parameter for no reason

### ISSUE THREAD

**Issue by galmasi** [keylime/keylime#629]
# Environment
 * OS / version: Ubuntu (but it does not matter)
 * Processor architecture: (does not matter)
 * TPM Manufacturer: virtual (swtpm) -- but it does not matter
 * Keylime version: any commit later than 23c2ae3f9aa1ab22f9a2fec02fc5e888475c38b3

# Description 
In commit 23c2ae3f the list of exclusions for the --targethost parameter changes from
`['list', 'regdelete', 'reglist', 'delete', 'status']`
to
`['list', 'regdelete', 'delete', 'status', 'addallowlist', 'deleteallowlist', 'showallowlist']`
... for some reason reglist has been left out of the new list.

## Expected behavior vs. actual behavior 
* expected behavior: `keylime_tenant -c reglist` should work
* actual behavior: `keylime_tenant -c reglist` requires a -t argument which is not used.

## Steps to reproduce problem
1. Run keylime as normal
2. issue the command `keylime_tenant -c reglist`

# Relevant logs

Attach any relevant log files that can help to debug your issue. 
```
[root@cssf-uc3 /]# keylime_tenant -c reglist 
Using config file /etc/keylime.conf
2021-04-16 17:20:09.467 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-04-16 17:20:09.470 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 1026, in main
    raise UserError(
keylime.tenant.UserError: -t/--targethost is required for command reglist
```

**Comment by mpeters** [comment]
George, I'm assuming this fixes it for you: https://github.com/keylime/keylime/pull/630

**Comment by mpeters** [comment]
Fixed by https://github.com/keylime/keylime/pull/630
