### ISSUE TITLE
Unable to check signature of revocation message

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#633]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: fedora 32
 * Processor architecture: x86
 * TPM Manufacturer: sw tpm
 * Keylime version: master

# Description 

Is it expected that, when a quote fails, the agent will get the message below?  What is getting revoked?  Is it expected that the agent will stop?  I can recover by deleting the tenant and starting over with (apparently) enrollment, but is that expected?

## Expected behavior vs. actual behavior 

I'm not sure what is expected, but I didn't expect quotes to stop and revoking something because of a single quote failure.

## Steps to reproduce problem
1. Maliciously hack the agent to reuse a nonce.
2. Run the agent and tenant.

# Relevant logs

GET integrity quote returning 200 response.
2021-04-19 17:45:28.984 - keylime.revocation_notifier - WARNING - Unable to check signature of revocation message: /var/lib/keylime/secure/unzipped/RevocationNotifier-cert.crt not available

**Comment by utkarsh2102** [comment]
Not sure if it's even remotely related but..

> 2021-04-19 17:45:28.984 - keylime.revocation_notifier - WARNING - Unable to check signature of revocation message: /var/lib/keylime/secure/unzipped/RevocationNotifier-cert.crt not available

And I get this:

2021-04-23 06:00:35.109 - keylime.ima_file_signatures - WARNING - No key with id 0xf3452d23 available
2021-04-23 06:00:35.109 - keylime.ima_file_signatures - WARNING - No key with id 0x531f4025 available

I don't expect this to happen, weird. But maybe I am missing something?

**Comment by kgoldman** [comment]
Your ahead of me!  How did you configure keylime to turn in IMA and process event logs?

A guess:  IMA files have signatures and a verifier should check the signatures.  Perhaps it's missing the public key for verification.  IMA's public key identifier is a 4-byte value, so it's an educated guess.  :-)

**Comment by utkarsh2102** [comment]
> How did you configure keylime to turn in IMA and process event logs?

Heh, I simply used the installer.sh script to set the ball rolling and to see what happens. All I wanted to do was get the tests working and so I installed and setup keylime using the installer script but it still fails; cf: #641. But that's about it. I didn't do anything differently, really.

**Comment by kgoldman** [comment]
I think you're running a test script.  If you ever figure out how to get keylime to send and verify UEFI or IMA logs, let me know.  "Out of the box", it seems to send PCRs and a quote and verify that, but not process event logs.

**Comment by stefanberger** [comment]
> Not sure if it's even remotely related but..
> 
> > 2021-04-19 17:45:28.984 - keylime.revocation_notifier - WARNING - Unable to check signature of revocation message: /var/lib/keylime/secure/unzipped/RevocationNotifier-cert.crt not available
> 
> And I get this:
> 
> 2021-04-23 06:00:35.109 - keylime.ima_file_signatures - WARNING - No key with id 0xf3452d23 available
> 2021-04-23 06:00:35.109 - keylime.ima_file_signatures - WARNING - No key with id 0x531f4025 available
> 
> I don't expect this to happen, weird. But maybe I am missing something?

These are two totally different problems, @utkarsh2102 . I am not even sure what you are doing when you are running in this issue and I think it should be filed as a separate issue.

**Comment by utkarsh2102** [comment]
> These are two totally different problems, @utkarsh2102 . I am not even sure what you are doing when you are running in this issue and I think it should be filed as a separate issue.

Ack, thank you!
