### ISSUE TITLE
Duplicated API calls to verifier in webapp backend

### ISSUE THREAD

**Issue by MartinMa28** [keylime/keylime#634]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: 
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: 

# Link to PR
#635 

# Description 
In keylime_webapp, to get the registered agents' latest states, there are 2 steps:
1. Call keylime_registrar to get a list of registered agents' uuids
2. Call keylime_verifier for each uuid to retrieve the latest state

However, currently in the first step, after receiving a list of uuids from registrar, keylime_webapp will also sort the uuid list in terms of agent states. So, it's going to make an API call to verifier for each uuid synchronously, which is pretty slow. More interestingly, right now keylime_webapp is making a wrong API call. [In this line](https://github.com/keylime/keylime/blob/8da88eb479a8edd147d03c6c41cc16aaa5050cf6/keylime/tenant_webapp.py#L435), agent_id is always None (agent should be used here instead of agent_id). As a result, keylime_webapp simply put all agent uuids in a single category. It's not sorting them at all.

## Expected behavior vs. actual behavior 
Expected: 
When the agent_id is not provided in the endpoint, keylime_webapp should get a list of registered uuids from keylime_registrar. I don't think sorting the agents can make a significant change in GUI. And later, we are going to submit another PR for the NEW GUI, where the order of agents is not required.

Actual:
Extra API calls are made. If there are 50 registered agents, then 101 API calls will be made within each interval (101 = 1 (registrar: get the uuid list) + 50 (verifier: get the state) + 50 (verifier: get the state for sorting)). And, agents are not sorted correctly.

**Comment by maugustosilva** [comment]
This was solved by #635. Closing it now
