### ISSUE TITLE
installer deletes tpm_cert_store files - minor git issue

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#643]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: ubuntu 20 groovy
 * Processor architecture: x86
 * TPM Manufacturer: na
 * Keylime version: master

# Description 

installer.sh has this line:

  mv $KEYLIME_DIR/tpm_cert_store /var/lib/keylime/tpm_cert_store

I suspect that it should be cp, not mv.  The logic is "If the directory isn't there, create it and **move** the files.  If it's there, **copy** the files.  The (minor) problem is that git status now shows all those files as deleted.

## Expected behavior vs. actual behavior 

Expected git status to show no changes.
Actual shows all the certificates as deleted.
 
## Steps to reproduce problem
1. installer.sh
2. git status

# Relevant logs

Attach any relevant log files that can help to debug your issue. 

snippet of git status:
	deleted:    tpm_cert_store/GS_TPM_RT.pem
	deleted:    tpm_cert_store/IFX1.pem
	deleted:    tpm_cert_store/IFX15.pem

**Comment by utkarsh2102** [comment]
Hello,

I was wondering about the same thing and so, I believe:

>  The logic is "If the directory isn't there, create it and move the files. If it's there, copy the files.

Honestly, I don't see why **both** of them should be `cp` instead? Even if there's no directory, just copy it as is there and not move them. This way we have the git copy with a "clean status" and also the certs are stored in the right place. What do you think?

**Comment by kgoldman** [comment]
> What do you think?

It sounds like you agree.  Are there any maintainers listening?  Should I create a pull request?

**Comment by mpeters** [comment]
@ken

>Should I create a pull request?

Absolutely!

**Comment by jronnblom** [comment]
Shouldn't this be in the keylime-deb also?

**Comment by utkarsh2102** [comment]
> Shouldn't this be in the keylime-deb also?

Actually, no. The Debian package doesn't use the installer script and doesn't copy/move files like this. I am in midst of opening a bunch of PR to entirely revamp the whole keylime-deb repository. Let me know if you have questions or anything.

**Comment by kgold2** [comment]
Created pull request #649
