### ISSUE TITLE
Ubuntu groovy abrmd not installing

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#655]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu groovy
 * Processor architecture: x86
 * TPM Manufacturer: na
 * Keylime version: master

# Description 

installer does not install Intel's abrmd.

## Expected behavior vs. actual behavior 

Expected abrmd to be installed.

## Steps to reproduce problem
1. ./installer.sh -o -m 
2. abrmd not installed
[installer.log](https://github.com/keylime/keylime/files/6395178/installer.log)

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by kgold2** [comment]
Same on Ubuntu 18 bionic:
In the installer, I see for Fedora:
            TPM2_TOOLS_PKGS="tpm2-tools tpm2-tss tpm2-abrmd"
but it's not set for Ubuntu or Debian.  Could that be the problem?

**Comment by mpeters** [comment]
@THS-on is this fixed by recent changes you made to the installer for Ubuntu?

**Comment by THS-on** [comment]
@mpeters we don't use abrmd by default any more, so I think this can be closed.
