### ISSUE TITLE
agent_uuid set to dmidecode crashes Keylime

### ISSUE THREAD

**Issue by jronnblom** [keylime/keylime#664]
# Environment
 * OS / version: Ubuntu 18.04
 * Processor architecture: amd64
 * TPM Manufacturer: swtpm
 * Keylime version: 6.1.0 from 

# Description 
Change agent_uuid to dmidecode to automatically read the UUID from the system crashes the agent:

May 10 16:28:28 u18can20 keylime_agent[4687]: Traceback (most recent call last):
May 10 16:28:28 u18can20 keylime_agent[4687]:   File "/usr/bin/keylime_agent", line 11, in <module>
May 10 16:28:28 u18can20 keylime_agent[4687]:     load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
May 10 16:28:28 u18can20 keylime_agent[4687]:   File "/usr/lib/python3/dist-packages/keylime/cmd/agent.py", line 15, in main
May 10 16:28:28 u18can20 keylime_agent[4687]:     keylime_agent.main()
May 10 16:28:28 u18can20 keylime_agent[4687]:   File "/usr/lib/python3/dist-packages/keylime/keylime_agent.py", line 507, in main
May 10 16:28:28 u18can20 keylime_agent[4687]:     sys_uuid = ret['retout'].decode('utf-8')
May 10 16:28:28 u18can20 keylime_agent[4687]: AttributeError: 'list' object has no attribute 'decode'

## Expected behavior vs. actual behavior 
To work.

## Steps to reproduce problem
1. Change agent_uuid to dmidecode in /etc/keylime.conf
2. Restart the agent

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by jronnblom** [comment]
I also think the sys_uuid should be check for validity before continuing.

**Comment by stefanberger** [comment]
Can you test it with PR #672 ?

Current patch: https://github.com/keylime/keylime/commit/8da24928bb743794bc75b0a7bffc1235a601272d.patch

**Comment by jronnblom** [comment]
That works.

> Can you test it with PR #672 ?

**Comment by stefanberger** [comment]
Can you close this issue?
