### ISSUE TITLE
Can't run keylime_agent w/o a priviliged user

### ISSUE THREAD

**Issue by utkarsh2102** [keylime/keylime#666]
Hello,

Thanks for your work on this! 🎉 

However, I have been trying to run keylime as a normal user (`keylime` in this case; as used in keylime-deb repository) and not as a privileged one. Since I was told that running code as non-root is something that you are pioneering here, I am unsure how to achieve that atm?

With keylime user and apt permissions, as set via [postinst in keylime/keylime-deb](https://github.com/keylime/keylime-deb/blob/7ee8bfce40c7d9dcdcc2fca7ff2e79883aa41418/postinst), I get:
```
● keylime_agent.service - The Keylime compute agent
   Loaded: loaded (/lib/systemd/system/keylime_agent.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2021-05-11 11:31:29 UTC; 14min ago
  Process: 3938 ExecStart=/usr/bin/keylime_agent (code=exited, status=0/SUCCESS)
 Main PID: 3938 (code=exited, status=0/SUCCESS)

May 11 11:31:29 ibm systemd[1]: Started The Keylime compute agent.
May 11 11:31:29 ibm keylime_agent[3938]: Using config file /etc/keylime.conf
May 11 11:31:29 ibm keylime_agent[3938]: importing [''], __package__='keylime.elchecking'
May 11 11:31:29 ibm keylime_agent[3938]: 2021-05-11 11:31:29.470 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
May 11 11:31:29 ibm keylime_agent[3938]: 2021-05-11 11:31:29.497 - keylime.cloudagent - CRITICAL - This process must be run as root.
```

Further diving into this, I see the following in `keylime/keylime_agent.py` (in v6.1.0):
```
[...]
def main():
    if os.getuid() != 0 and config.REQUIRE_ROOT:
        logger.critical("This process must be run as root.")
        return
[...]
```

So I believe running keylime_agent with `User=keylime` isn't really viable atm? I hope I am not missing anything?

**Comment by maugustosilva** [comment]
@utkarsh2102 you will need at least this PR: https://github.com/keylime/keylime/pull/611

**Comment by utkarsh2102** [comment]
Hi maugustosilva,

> @utkarsh2102 you will need at least this PR: #611

Awesome, thanks! Can this please be released at the earliest, but of course, whenever the time is right & other things that the maintainers might need to take care of?

**Comment by maugustosilva** [comment]
Release 6.1.1 solves this issue
