### ISSUE TITLE
http requests (sent by using RequestsClient) don’t use any connection timeout value

### ISSUE THREAD

**Issue by igurel** [keylime/keylime#678]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 20
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: [d632e2a](https://github.com/keylime/keylime/commit/d632e2a3b510167ba997197f5232bc4456aa0394)

# Description 
http requests (sent by using RequestsClient) don’t use any connection timeout value

## Expected behavior vs. actual behavior 
Default timeout should be provided while making http requests. (timeout value should ideally be configurable in keylime.conf)

## Steps to reproduce problem
1. No time out while e.g. in [tenant.py#L558](https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L558), tenant.py#L593](https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L593),..

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by maugustosilva** [comment]
@mpeters I believe this has been indeed solved in the latest code (e.g., `timeout=self.request_timeout` on all REST API calls)

**Comment by THS-on** [comment]
Yes is is fixed.
