### ISSUE TITLE
The tenant registers agent to the verifier first before handling initial quote provided by the agent. 

### ISSUE THREAD

**Issue by igurel** [keylime/keylime#680]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 20.04
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: [d632e2a](https://github.com/keylime/keylime/commit/d632e2a3b510167ba997197f5232bc4456aa0394)

# Description 
The tenant registers agent to the verifier first and then it handles initial quote provided by the agent. 

## Expected behavior vs. actual behavior 
The tenant registers agent to the verifier first and then it handles initial quote provided by the agent. This may lead to an issue that the verifier keeps asking quotes from the agent before proper attestation quote validation by the tenant. This may happen by e.g. a malicious agent, another malicious process or http request (sent to the agent by the tenant) which doesn’t timeout

## Steps to reproduce problem
1. See the order in [tenant.py#L1176](https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L1176)

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
I've tried switching the order of `do_cv()` and `do_qoute()` and nothing immediately broke. 
On first glance I couldn't find that `do_qoute()` has a dependency on `do_cv()` other than removing the agent from the verifier if it failed.  Is there another reason why we don't just switch the order?

There would be a change in behavior.  The failed agent never gets added to the verifier and is there in a stopped state. If that is desired the order should not be changed and only the EK validation could be moved before the `do_cv()`.

**Comment by igurel** [comment]
> I've tried switching the order of `do_cv()` and `do_qoute()` and nothing immediately broke.

I've tried too and it should work fine.

**Comment by maugustosilva** [comment]
While I am certainly willing to support such change, we would need a new enhancement proposal for this.

**Comment by ansasaki** [comment]
@igurel Hello, do you plan to propose the enhancement? I think this change makes sense (together with #679), and would like to offer help, if needed.
