### ISSUE TITLE
TLS connections (e.g. tenant->verifier) are established without server certificate validation

### ISSUE THREAD

**Issue by igurel** [keylime/keylime#681]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: 
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: [d632e2a](https://github.com/keylime/keylime/commit/d632e2a3b510167ba997197f5232bc4456aa0394)

# Description 
TLS connections (e.g. tenant->verifier) are established without server certificate validation. This can lead to MiTM

## Expected behavior vs. actual behavior 
The expected behaviors is that server certificates are validated properly to mitigate MiTM attacks. The actual behavior skips validating server certificates. See [tenant.py#L557](https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L557)

## Steps to reproduce problem
1. See [tenant.py#L557](https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L557), [tenant.py#L644](https://github.com/keylime/keylime/blob/master/keylime/tenant.py#L644),..

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by mpeters** [comment]
@THS-on was this cleared up as part of the recent mTLS work?

**Comment by THS-on** [comment]
@mpeters only the code for checking the certs was added. I have not modified the tenant to check certificates. Can you assign this issue to me?

**Comment by THS-on** [comment]
@mpeters fixing this will require adding a new config option to specify the root certificate for the CAs (registrar and verifier). I'll do that but it again complicates the TLS setup of Keylime.
