### ISSUE TITLE
keylime_agent persists the EK but then never uses it

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#684]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: RHEL
 * Processor architecture: x86
 * TPM Manufacturer: SW TPM
 * Keylime version: master

# Description 

The LOC in tpm_main.py that calls tpm2_createek uses -c - as a parameter.  This causes the Intel tool to persist the EK.  However, tracing the TPM commands, this persistent EK is never used.

## Expected behavior vs. actual behavior 

The TPM persistent slots are limited.  There are perhaps 7.  They should not be consumed unless really necessary.

## Steps to reproduce problem

1. Run the agent on a system with a clean keylime state

# Relevant logs

An AK enrollment needs these 7 TPM commands:

* createprimary the EK
* createprimary an SRK
* create an AK
* load the AK
* startauthsession
* policysecret
* activatecredential

keylime is using 121 TPM commands.  It's worth removing extra commands to make the code more maintainable (not for performance).

**Comment by THS-on** [comment]
With the rust agent now being mostly feature complete, I don't think it is worth putting effort into changing the TPM code of the Python agent.

The rust agent does not have this issue.

**Comment by mpeters** [comment]
Agreed.
