### ISSUE TITLE
Building keylime agent as a non-root user

### ISSUE THREAD

**Issue by osresearch** [keylime/keylime#689]
# Environment
 * OS / version:  Ubuntu 20.04,2
 * Processor architecture: x86-64
 * TPM Manufacturer: NA
 * Keylime version: 480c9b107c155e7a20442afe3be929cf5d50fb86

# Description 

Building the semi-portable agent tarball with `-t` requires root access and modifies the underlying build system.  If there are steps that require `root`, such as installing dependencies, these steps could be exposed as a separate flag to be run once during bootstrap.

## Expected behavior vs. actual behavior 

Expected to be able to build the agent tar file as a normal user.

Actual behavior:

```
% ./installer.sh -t -o
ubuntu selected.
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
This script must be run as root in order to install keylime and its dependencies
```

## Steps to reproduce problem
1. Run `installer.sh` as non-root

**Comment by nabilschear** [comment]
@osresearch this is probably easy to hack into place because elevated access is only required to install packages with apt or yum.
