### ISSUE TITLE
UUID case

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#691]
So it turns out UUID's should be lower case ("a" through "f" are in fact  hexadecimal values)

https://datatracker.ietf.org/doc/html/rfc4122#section-3

we hit this issue in the rust keylime agent, where the UUID crate generates a UUID lowercase, which does not map to the entry in keylime.conf

So this to me suggests we should user lower in the python side. Where lower is the default and everything is canonicalised to `.lower()`

**Comment by jronnblom** [comment]
Also note that different version of dmidecode can return UPPER or lower. Like in Ubuntu 18.04 vs Ubuntu 20.04. 

This causes a problem in the old python agent.
