### ISSUE TITLE
No documentation about `--mb_refstate`

### ISSUE THREAD

**Issue by aplanas** [keylime/keylime#693]
# Description 

After #568, and in relation with #491 a new feature has been added, that will help to do a replay of the measured boot tracked by the event log.  There is no documentation about how this parameter can be used. Seems that is a JSON document but there is no description about the fields and how will be used.

**Comment by aplanas** [comment]
@maugustosilva Can you help me here? I am checking https://github.com/keylime/keylime/commit/c93fff3953fcaa11010fe5bc212e50a472b00215, https://github.com/keylime/keylime/commit/62e11ebd7dee435c14849189e0e278477cd25bb1, https://github.com/keylime/keylime/commit/1766957a748140d6040df70fd522452a12606a5e and https://github.com/keylime/keylime/commit/5f6bb2e075a7e80f7a54db254353fce89cc645b1 to figure out the JSON format and the expectations of behavior

**Comment by lkatalin** [comment]
I am also having this same problem.

**Comment by maugustosilva** [comment]
@aplanas @lkatalin yes, I have started the process of documenting it in https://github.com/keylime/keylime-docs/pull/62, but never quite finished it. In its simplest form, a "refstate" would be an empty dictionary. As the aforementioned document explains, this would means that verifier would get the measure boot log, replay it, and compare the states of PCRs 0-9 with the current quote from the agent.

```
[root@css-flex14vm1 /]# cat /tmp/mb_refstate_0FC2F2DC-E946-5F94-9D03-5A542D237927.txt
{} 
```

**Comment by aplanas** [comment]
@maugustosilva thanks for the confirmation.

**Comment by maugustosilva** [comment]
Given the existence of a documentation for this feature in https://github.com/keylime/keylime-docs/blob/master/docs/user_guide/use_measured_boot.rst, I will go ahead and close it for now. Feel free to reopen if needed.
