### ISSUE TITLE
If the PCR belong to a measured boot list, it is not validated

### ISSUE THREAD

**Issue by aplanas** [keylime/keylime#694]
# Description 

If the PCR belongs to a hard-coded list of PCRs under `config.MEASUREDBOOT_PCRS` and `--mb_refstate` is not used, the check of match do not happens, so the tpm-policy parameter gets ignored.

## Expected behavior vs. actual behavior 

If we pass a `--tpm-policy` with a PCR that belong to the list, like PCR 0 for example, the validation of this register never happens in the verifier unless we some value to `--mb_refstate` is passed.

I would expect that if this second parameter is not passed, a plain validation still occurs.

**Comment by aplanas** [comment]
please assign

**Comment by maugustosilva** [comment]
This is a fair functional expectation for "non-MB", "non-IMA" cases.
