### ISSUE TITLE
CFSSL is is not FIPS certified

### ISSUE THREAD

**Issue by aplanas** [keylime/keylime#696]
# Description 

IIUC seems that CFSSL is using the golang crypto libraries, instead of using a system library like libopenssl from the system.  Also, IIUC CFSSL is required when we need to revoke certificates.  Can be possible to leverage openssl in this situation too?

**Comment by mpeters** [comment]
AFAIK OpenSSL doesn't have a CA revocation mechanism.

**Comment by aplanas** [comment]
I have no idea, is in my TODO to research, but I found this "crl" parameter early, with some documentation here: https://jamielinux.com/docs/openssl-certificate-authority/certificate-revocation-lists.html

I do not know how much it can help.

**Comment by lukehinds** [comment]
It's actually the go library that is not FIPS compliant, there are ways around that though.

Red Hat has a go fips compliant tool chain that will use OpenSSL bindings.

https://developers.redhat.com/blog/2019/06/24/go-and-fips-140-2-on-red-hat-enterprise-linux

This is how Red Hat ships openshift (which is built in go), while still remaining in FIPS land.

Hope that helps.

**Comment by aplanas** [comment]
That helps a lot actually, I think that openSUSE will follow this too.
