### ISSUE TITLE
[enhancement] No useful default class to convert mb-refstate into a valid Test

### ISSUE THREAD

**Issue by aplanas** [keylime/keylime#703]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
Any

# Description 
After researching https://github.com/keylime/keylime/issues/693 is clear that there is no mechanism in Keylime to transform a `mb-refstate` JSON document into a valid Test class.

We should implement one and make it the default, instead of AcceptAll.

**Comment by maugustosilva** [comment]
It is on my to-do list :-)

**Comment by aplanas** [comment]
I am giving a try for the simplest possible parser, using directly the combinators already implemented. Lets see.

**Comment by aplanas** [comment]
Yes, thanks, lets close it!
