### ISSUE TITLE
Running tpm_server from scripts/tpm_serverd is not optimal

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#733]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: F34
 * Processor architecture: x86_64
 * TPM Manufacturer: IBM TPM emulator
 * Keylime version: 6.1.1

# Description 
tpm_server is executed from tpm_serverd on background via:

tpm_server -rm tpm_server.log &

This is causing issues e.g. when running tpm_serverd from ansible since the tpm_server process is terminated when
the shell session is closed.

## Expected behavior vs. actual behavior 
Process is not properly daemonized. It should be running as a daemon, detached from a current shell.
Ideally it would be a systemd service but at least it should detach using nohup.
The following line worked for me
nohup tpm_server -rm 0<&- 2>&1 >> ${TPM_PATH}/tpm_server.log &

## Steps to reproduce problem
1. When using ansible playbook from keylime-vagrant-ansible-tpm-emulator from
https://github.com/keylime/keylime-vagrant-ansible-tpm-emulator/blob/6a38961f8219b72da451b961e9ff70d3485c8c70/roles/ansible-keylime-tpm20/tasks/ibm-tpm.yml#L40
the tpm_serverd is executed via

- name: Start TPM Emulator
  command: /usr/local/bin/tpm_serverd
  become: yes

which starts tpm_server process and terminates it few seconds later.

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by kkaarreell** [comment]
To add more context, the following thread describes same problem
https://www.reddit.com/r/ansible/comments/dlvh9y/cant_run_bash_script_in_the_background/

**Comment by THS-on** [comment]
Should be fixed with https://github.com/keylime/keylime-vagrant-ansible-tpm-emulator/pull/57.
