### ISSUE TITLE
keylime_tenant -c cvlist fails due to Unexpected response from Cloud Verifier

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#800]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora35
 * Processor architecture:  x86
 * TPM Manufacturer: swtpm
 * Keylime version: current latest (head a712b8393c75f6db0d29f95e57c268fc56450d7d)

# Description 
keylime_tenant -c cvlist fails
Using config file /etc/keylime.conf
2021-12-01 09:48:08.816 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2021-12-01 09:48:08.818 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-12-01 09:48:08.819 - keylime.tenant - WARNING - Using default UUID d432fbb3-d2f1-4a97-9ef7-75bd81c00000
/usr/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-12-01 09:48:08.849 - keylime.tenant - INFO - Status command response: 500. Unexpected response from Cloud Verifier 127.0.0.1 on port 8881. <Response [500]>

## Expected behavior vs. actual behavior 
command works

## Steps to reproduce problem
1. run the above comment for a registered agent

I have identified that the breakage is introduced by this commit
https://github.com/keylime/keylime/commit/e6d4d12faa8ee490dad3dcb993ee1b57db7f9c53
With keylime code from the former commit a55a5594ccb192a55ff556a99dd60e97f73c1920 things work well.

FYI, test code is available at
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/functional/basic-attestation-on-localhost/test.sh

**Comment by kkaarreell** [comment]
FYI @sergio-correia

**Comment by sergio-correia** [comment]
Thanks, I found the issue and will submit a fix soon.
