### ISSUE TITLE
IMA emulator should use SHA256 instead of SHA1

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#801]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora35
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: latest upstream (a712b8393c75f6db0d29f95e57c268fc56450d7d)

# Description 
swtpm starting version 0.7.0 stopped using SHA1 for pcs, uses SHA256 instead.
Keylime IMA emulator should be also rather using SHA256 as it would allow to test e.g. system configured in FIPS.

For more details see https://bugzilla.redhat.com/show_bug.cgi?id=2028023

**Comment by THS-on** [comment]
The current issue is that we hardcode the IMA PCR to be SHA1 and most kernels today use the SHA1 in the IMA log (but they also extent to SHA256 PCRs).
We should make this algorithm independent. It should be rather simple to extend to current parser to validate also other algorithms and then we could deprecate that we force the agent to also sent the sha1 PCR value for the IMA log (tracking issue #30).

Once that is fixed we can then also migrate the IMA emulator.

**Comment by THS-on** [comment]
@kkaarreell #803 now contains a new IMA emulator that has the option to use multiple hash algorithms.
