### ISSUE TITLE
Better support for running Keylime not as root

### ISSUE THREAD

**Issue by THS-on** [keylime/keylime#864]
## Issue
Currently Keylime supports running as a normal user, but the support can be improved.

First the Keylime still contains code (i.e. `REQUIRE_ROOT` in `config.py`) that checks explicitly for root. This is not required anymore and should be removed. @mpeters this is on your TODO list, right?

Second Keylime requires access to IMA and the UEFI eventlog, which are are provided by securityfs and are only readable by root.
The UEFI eventlog is not that big of an issue because it never changes after boot, so we can just copy it to a location for the agent to read. The issue is that the agent requires continuous read access to the IMA log (`/sys/kernel/security/ima/ascii_runtime_measurements`).

The verifier and registrar only require that `/var/{lib,run,log}/keylime` are there with the correct permissions before startup.

## Proposed fixes
Here is an overview of the potential fixes that we discussed.

### chown/chmod IMA file
Debian package currently use the approach to change the permissions on that file, so that the keylime user can read it. It changes the ownership to the `tss` group.

This could be a problem if other applications expect this file to be owned by a different user/group. To my knowledge such applications currently do not exist. The `tss` group is used by most distros for owning all TPM related devices (`/dev/tmp*`), so I think it is fine to add also the IMA and UEFI log to be owned by this group. We could also add another group that owns those files, as long as we can agree on the same group.

### dbus service for providing access to IMA
Alberto proposed this can be solved by providing the IMA log via a dbus service. This solves the issue, but seems a bit overkill.  Adding dbus as a dependency is fine because for Python and Rust there seems to be good library support.
Supporting authentication in dbus seems not to be trivial and adding polkit also as a dependency seems not to be ideal.

### unix socket for providing IMA 
Similar to the dbus service we could expose an API reading the IMA log via a unix socket. This has the advantage that the we do not add dbus as a dependency, but has the disadvantage that we have to define a custom protocol for the communication.

### Drop privileges for web components but run as root for IMA log
We could run a part of the agent as root to read the IMA log, but drop the privileges for the rest of the agent. 
This works, but has some potential issues. First we might forget to drop the privileges for some part that does not require it. Second parts of Keylime still run as root, which we do not want.  

### Pass file descriptor from privileged process to the Keylime process
Matthias gave the idea that we could open the file descriptor in process owned by root and pass it to the agent process.
For this there exists an API in newer Kernel versions \[1\], but supporting it for older Kernel versions seems to be quite tricky and I do not know how easily we can implement this in Python.

cc: @aplanas, @kkaarreell, @sergio-correia, @utkarsh2102

\[1\]: https://copyconstruct.medium.com/seamless-file-descriptor-transfer-between-processes-with-pidfd-and-pidfd-getfd-816afcd19ed4

Edit: SUSE does not change the permissions on the IMA file I misread the discussion.

**Comment by aplanas** [comment]
> The SUSE and Debian package currently use the approach to change the permissions on that file, so that the keylime user can read it. SUSE makes it completely world readable

That is not correct. The openSUSE package still use `root` for keylime_agent. We will not change ownership of the `securityfs` files, as will be considered not sound.

**Comment by aplanas** [comment]
> This seems like a simple solution to me, but I do not know if it is actually intended that securityfs can be mounted multiple times.

I can bind mount / mount multiple times, but I cannot set uid / gid. Are you sure that this option can be done?

**Comment by aplanas** [comment]
> Drop privileges for web components but run as root for IMA log

IMHO this kind of looks the more simple approach?

We can create in the agent's `keylime.conf` entry a non-privilege user where to downgrade. This allow us to use the same strategy to read both securityfs.

A similar approach is to split the keylime_agent is two services. One for the web, that will be running from the start as an unprivileged user, and another that will read the securityfs files, or execute TPM actions that require privilege access.

Can be generalized if we want to split it in three services (securityfs + web + payload execution).

The main drawback is that the agent is not a single entity, and complicate the installation and deployment (something that is very valuable to have).

So a drop of privileges is kind of the best of both worlds here (single entry point / management, minimal privilege in any point, and single service)

**Comment by THS-on** [comment]
> The openSUSE package still use root for keylime_agent. We will not change ownership of the securityfs files, as will be considered not sound.

Yeah, I misread the original discussion. It was only a (equally wrong) idea that was not implemented. Sorry.

> I can bind mount / mount multiple times, but I cannot set uid / gid. Are you sure that this option can be done?

I thought it worked, but indeed we cannot change the uid/gid and even if we mount it twice it will change the permission at both mount points (which makes sense).


>>    Drop privileges for web components but run as root for IMA log

>IMHO this kind of looks the more simple approach?

Yes this is probably the best bet for the rust agent. It would also allow us easily to run the payload with a different user.

On the Python side we initialize some objects at module loading time and also executing somewhat arbitrary code with the revocation actions, so we need to ensure that if we drop privileges permanently and don't have a way to escalate back to root. 
I don't know how we can ensure that in Python.

**Comment by stefanberger** [comment]
Here are the patches from a proposal that I had made a while ago: https://github.com/stefanberger/keylime/commits/stefanberger/agent_drop_privileges

Basically the idea was to start keylime agent as root, open files that can only be opened as root, drop privileges to nobody:nobody, access files via the open fd and `seek()`ing on them.

**Comment by THS-on** [comment]
@stefanberger thank you for the patches. It looks like that starting a root and dropping privileges after opening the IMA and UEFI log seems rather doable.

@aplanas I now agree with you that this is probably the simplest option to fix this issue. How do we want to proceed with this?

**Comment by aplanas** [comment]
The problem with `chown` is that we are taking ownership of a system resource, during a package installation. The user should expect to still use the resource in other situations too, and a package should not have this side effect.

The udev rule seems reasonable, because can be present independently if keylime has been installed or not. But seems that securityfs have some limitations, like missing ACL and other stuff. But I did not research fully the udev approach.

**Comment by stefanberger** [comment]
Another way: Open file descriptors as root and run the agent with lower privileges and pass in file descriptors via command line options. A wrapper could be a simple script or maybe systemd can also do that?

**Comment by THS-on** [comment]
@stefanberger I couldn't find a way to do that using systemd, also passing file descriptors to non child processes looked rather tricky. I tried some things with udev, but it did not seem to work.

Unfortunately systemd also not exposes a mount unit (https://github.com/hramrach/systemd-1/commit/160481f68d0a5f26f75c04fb576fb854fd5416a5) which we could modify. 

We could add a service that sets the correct permissions (changing the group of IMA log and UEFI eventlog to a predefined group) during startup which would be it's own package. @aplanas any opinions on that idea?

**Comment by aplanas** [comment]
> We could add a service that sets the correct permissions (changing the group of IMA log and UEFI eventlog to a predefined group) during startup which would be it's own package. @aplanas any opinions on that idea?

We can do this yes.

I asked around here about if there is a problem having a file descriptor open for years and the feedback is clear: none. Seems that this is the usual thing to do when downgrading privileges, even for write file descriptors (IMA will be open "ro", that can be considered safer).

I am more inclined for the downgrading approach here, but I can go with any.

**Comment by mpeters** [comment]
I'm also more inclined to go the downgrading approach. It's the standard way that lots of daemons do what they need to do (like open privileged ports, files, etc)

**Comment by THS-on** [comment]
Dropping privileges is probably a better approach and gives us the option to run the payload as a different user in the future.

**Comment by aplanas** [comment]
> Dropping privileges is probably a better approach and gives us the option to run the payload as a different user in the future.

That is a very good point: separating the web agent user from the payload executor user in the future.

**Comment by stefanberger** [comment]
Opened PR #900 now.

**Comment by THS-on** [comment]
PR #900 was merged, so I will close this issue.
