### ISSUE TITLE
Difficult agent mTLS configuration 

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#878]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: 
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: current latest 37d338f

# Description 
keylime agent uses the following options for mTLS
```
# The name of the RSA key that Keylime should use for protecting shares of U/V.
rsa_keyname = tci_rsa_key

# The name of the X509 certificate that is used for mTLS. Uses the rsa_keyname as a key.
mtls_cert = tci_mtls_cert

# The CA that signs the client certificates of the tenant and verifier.
# If set to default it tries to use /var/lib/keylime/cv_ca/cacert.crt
keylime_ca = default
```
keylime verifier uses
```
# mTLS configuration for connecting to the agent.
# Set 'agent_mtls_cert' to 'CV' for using the CV CA for the connections.
agent_mtls_cert = CV
agent_mtls_private_key =
agent_mtls_private_key_pw =
```
and tenant also uses
```
# mTLS configuration for connecting to the agent.
# Set 'agent_mtls_cert' to 'CV' for using the CV CA for the connections.
agent_mtls_cert = CV
agent_mtls_private_key =
agent_mtls_private_key_pw =
```

There are the following issues with this configuration:

1. `rsa_keyname` and `mtls_cert` assumes file names or paths relative to `/var/lib/keylime/secure`. This is not mentioned and in contradiction to `keylime_ca` or mTLS related options of tenant or verifier which assume absolute paths.

2. absolute paths for cloud agent should be also supported
3. when a file cannot be accessed due to incorrect path the message should be printed visibly (Warning or Error, currently only Debug).
4. agent mtls certificate needs to be self-signed, this fact is not documented
5. naming convention for agent options - should have similar names as tenant and verifier. `keylime_ca` should be rather named `ca_cert` or `mtls_ca_cert`.
6. verifier and tenant do not mention which CA cert is being used if 'CV' is not set.

**Comment by ansasaki** [comment]
I would like to extend this to all roles and not only the agent. The configuration options names to set keys and certificates are super confusing and the comments don't describe for what they are used.

For example, in the `cloud_verifier` section:
```
# The following three options set the filenames where the CA certificate,
# client certificate, and client private key file are, relative to the 'tls_dir'.
# If 'tls_dir = default', then default values will be used for 'ca_cert = cacert.pem',
# 'my_cert = client-cert.crt', and 'private_key = client-private.pem'.
registrar_ca_cert = default
registrar_my_cert = default
registrar_private_key = default
```
Some clarification would be welcome. For example:
```
# The following options set the keys and certificates the verifier will use as a client to connect to the registrar.
```
Also more consistency between the option names would be appreciated. Compare the above options with the following:
```
# mTLS configuration for connecting to the agent.
# Set 'agent_mtls_cert' to 'CV' for using the CV CA for the connections.
agent_mtls_cert = CV
agent_mtls_private_key =
agent_mtls_private_key_pw =
```
The purpose is basically the same (set which keys/certs to use when connecting to the agent), but the names are completely different, even for the default option (`default` vs `CV`).

**Comment by THS-on** [comment]
@ansasaki I fully agree that we should cleanup and normalize the names in the configuration. If/when we move the configuration to TOML (https://github.com/keylime/keylime/issues/895) we should redesign our configuration.
This change has to be done probably with a major version change.

Can you provide a list of what config options and descriptions are confusing? Then I can make a PR that at least adds more context to those options.

**Comment by ansasaki** [comment]
I think most of the options related with keys/certificates configurations are confusing or not clear:

In `cloud_verifier` section:
- `tls_dir`: could be more explicit, like `ca_dir`, `cv_ca_dir`, or `verifier_ca_dir`
- `registrar_tls_dir`: similar to above, could be `registrar_ca_dir` or `registrar_access_ca_dir`. I understand it is difficult to select a name as it is not usual to have the option to select different keys/certs to use for each individual connection.  The description comments could also be more explicit (e.g. `The following options set the keys and certificates the verifier will use as a client to connect to the registrar.`)
- `registrar_my_cert`: could be `registrar_access_cert` or something similar. The confusing part is to understand why we have registrar options in `cloud_verifier` section.
- `registrar_private_key`: the most confusing option, made me ask "why would any entity know other entity's private key?". This again could be something like `registrar_access_private_key`. A comment specifying explicitly the purpose of this option, like mentioned above, could clarify it.
- `agent_mtls_cert`, `agent_mtls_private_key`, `agent_mtls_private_key_pw`: these are not as confusing as the registrar related options, but consistency on naming would be nice. A clear and explicit comment about the purpose would be a plus.

In `tentant` section:
- All above applies here
- There are no options to set the keys/certificates used when connecting to the verifier. I understand `my_cert` and `private_key` are used in this case, but again some consistency is missing.
  - This also shows that probably https://github.com/keylime/keylime/issues/681 is still a valid issue.

**Comment by kkaarreell** [comment]
>     * `registrar_my_cert`: could be `registrar_access_cert` or something similar. The confusing part is to understand why we have registrar options in `cloud_verifier` section.

I would simply use something like `verifier_server_cert` and `verifier_client_cert`, which is in fact what these certs are expected to be. Comments surrounding these options should explain for what purpose these certs are being used in particular.

**Comment by ansasaki** [comment]
> > ```
> > * `registrar_my_cert`: could be `registrar_access_cert` or something similar. The confusing part is to understand why we have registrar options in `cloud_verifier` section.
> > ```
> 
> I would simply use something like `verifier_server_cert` and `verifier_client_cert`, which is in fact what these certs are expected to be. Comments surrounding these options should explain for what purpose these certs are being used in particular.
> 
> In fact, since it would be in `cloud_verifier` section it could be simply `server_cert` and `client_cert`.

This would be my preferred solution if it is acceptable to drop the possibility to set different keys/certs when connecting to each different service. I don't see any benefit of using individual keys/certs for each service.

It would be much simpler and clear if the services had `server_cert` and `server_key` if they work as a server and `client_cert` and `client_key` if they work as a client.

Another change that would simplify things is to have a single location to store all trusted CA certificates.

**Comment by kkaarreell** [comment]
Just to clarify, I wasn't suggesting using one certificate for all services. Just using that simple option name within a particular section.

**Comment by ansasaki** [comment]
> Just to clarify, I wasn't suggesting using one certificate for all services. Just using that simple option name within a particular section.

Also to clarify, I wasn't suggesting using one certificate for all services, but for each entity to have a single client certificate if it works as a client instead of having a client key/certificate per accessed service.

For example in `cloud_verifier` section there are options to configure:
- server key/cert via `private_key` and `my_cert`
- client key/cert to access the registrar via `registrar_private_key` and  `registrar_my_cert`
- client key/cert to access the agent via `agent_mtls_private_key` and `agent_mtls_cert`

Instead we could configure:
- server key/cert via `server_key` and `server_cert`
- client key/cert via `client_key` and `client_cert` to access any other service as a client

Similarly for each other service.

**Comment by THS-on** [comment]
@ansasaki I like the idea of only having one client certificate, but I don't know if this works because one cert can only be issued by one CA. At least we could simplify it to only use one key and dropping the password (this is not really necessary).

@maugustosilva do you split the CAs into agent, registrar and verifier in your installation? I think the idea that the registrar is used by different tenants is not used and we could always use the same CA for the registrar and verifier.

**Comment by THS-on** [comment]
Actually I think we can move all components to the same CA by adding the option to trust multiple CAs for mTLS connection. We can have only one CA that issues the certificates for agent, verifier or registrar mTLS connections and sever certificates for the registrar and verifier by default. Then we could use the `server_key/client_key` and `server_cert/client_cert` from @ansasaki and just add a option to the agent, verifier and registrar called `trusted_cas` which has a list of CAs for client connections.

This would still allow the agent, verifier and registrar to trust other CAs (and therefore for example other Keylime installations) with a more complex setup, but the default setup would be a lot simpler.

**Comment by THS-on** [comment]
@ansasaki #1068 fixes all of the issues raised here, right?

**Comment by ansasaki** [comment]
@THS-on From my point of view, yes, #1068 addresses the issues pointed here
