### ISSUE TITLE
Path to deprecation for loading revocation actions as Python modules

### ISSUE THREAD

**Issue by lkatalin** [keylime/keylime#884]
As discussed with @THS-on and @mpeters , there is not an advantage of running revocation actions as Python modules, and it would be better to directly execute both Python and non-Python scripts. However, [the code](https://github.com/keylime/keylime/blob/37d338fe3056fdb9345f936902426ac22d9afaf4/keylime/keylime_agent.py#L583-L590) running revocation actions this way cannot be immediately changed, because it would break existing revocation actions that are already in use.

Unless there are objections, I propose the following steps:
1. Put a deprecation warning on running rev actions as Python modules for at least one major version
2. After the warning has been in place for at least one major version, remove this method of running the revocation actions

**Comment by lkatalin** [comment]
Not stale :)

**Comment by THS-on** [comment]
We now removed the Python agent, so I'm closing this.
