### ISSUE TITLE
Error parsing EK ASN.1 certificate of Nuvoton HW TPM

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#944]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: CentOS Stream 9
 * Processor architecture: x86_64
 * TPM Manufacturer: Nuvoton
 * Keylime version: current upstream [6aeb105]

# Description 
What running the basic attestation scenario on localhost the agent fails to register and the following message is logged by registrar
```
2022-03-28 05:42:13,737 keylime.tpm INFO TPM2-TOOLS Version: 5.0
2022-03-28 05:42:13,752 keylime.registrar WARNING POST for d432fbb3-d2f1-4a97-9ef7-75bd81c00000 returning 400 response. Error: error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["RawCertificate::tbs_cert", "TbsCertificate::issuer", "0", "2"] }
2022-03-28 05:42:13,752 keylime.registrar WARNING POST for d432fbb3-d2f1-4a97-9ef7-75bd81c00000 returning 400 response. Error: error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["RawCertificate::tbs_cert", "TbsCertificate::issuer", "0", "2"] }
2022-03-28 05:42:13,753 keylime.registrar ERROR error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["RawCertificate::tbs_cert", "TbsCertificate::issuer", "0", "2"] }
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime-6.3.1-py3.9.egg/keylime/registrar_common.py", line 287, in do_POST
    ek509 = load_der_x509_certificate(
  File "/usr/local/lib64/python3.9/site-packages/cryptography/x509/base.py", line 538, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
ValueError: error parsing asn1 value: ParseError { kind: InvalidSetOrdering, location: ["RawCertificate::tbs_cert", "TbsCertificate::issuer", "0", "2"] }
```
I have tested it also with the latest cryptography module available in PIP v36.0.2, same behavior.

TPM EK cert cannot be parsed by cryptography module but it can be parsed by openssl (openssl-3.0.1)

## Expected behavior vs. actual behavior 
TPM EK cert works

## Steps to reproduce problem
1. run e.g. [/functional/basic-attestation-on-localhost ](https://github.com/RedHat-SP-Security/keylime-tests/tree/main/functional/basic-attestation-on-localhost) on a system with respective TPM (Dell PowerEdge R7425)

**Comment by kkaarreell** [comment]
@THS-on Please add your findings. Thank you.

**Comment by THS-on** [comment]
The issuer attribute seems non standard: `Issuer: CN = Nuvoton TPM Root CA 2110 + O = Nuvoton Technology Corporation + C = TW`. Normally those fields should be comma separated not with a `+`.

**Comment by THS-on** [comment]
Looking at [RFC 1779](https://datatracker.ietf.org/doc/html/rfc1779) it allows `+` as some kind of separator, but I have not seen anywhere else.

**Comment by mpeters** [comment]
Does this mean we need to fix upstream packages to allow for this part of the spec?

**Comment by THS-on** [comment]
I found out some more information. The `+` is used for RDNs which the cryptography library actually support. The issue seems to be that the order is wrong it should be `C, CN, O` not `CN, O, C`. 

I tried to generate other "wrong" certificates with openssl, but it reorders it for me. I'll have to find another way to produce a similar certificate.

**Comment by mpeters** [comment]
If there's an upstream ticket, we might have some contacts that work on that library that we can prod about getting it fixed.

**Comment by THS-on** [comment]
@mpeters no because I did not find a way to produce a "invalid" certificate with either the cryptography lib or openssl.

@kkaarreell @mpeters can we post the EK certificate for one of the devices in the testing farm publicly?

**Comment by kkaarreell** [comment]
Not sure if it helps but one can download Nuvoton root cert and it seems to be the same

```
$ wget --no-check-certificate https://www.nuvoton.com/security/NTC-TPM-EK-Cert/Nuvoton%20TPM%20Root%20CA%202110.cer -O nuvoton.cer
$ openssl x509 -inform der  -in ~/nuvoton.cer -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4581057599893149371 (0x3f932f9d993c16bb)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = Nuvoton TPM Root CA 2110 + O = Nuvoton Technology Corporation + C = TW
        Validity
            Not Before: Oct 19 04:32:00 2015 GMT
            Not After : Oct 15 04:32:00 2035 GMT
        Subject: CN = Nuvoton TPM Root CA 2110 + O = Nuvoton Technology Corporation + C = TW
...

**Comment by kkaarreell** [comment]
FTR, this behavioral change has been introduced by https://cryptography.io/en/latest/changelog/#v35-0-0

**Comment by THS-on** [comment]
I'm closing this for now because we have a workaround and the issue needs to be solved upstream.
