### ISSUE TITLE
keylime_agent: Inconsistent log levels for request responses

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#958]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: current master (3ab5531)

# Description 
The log level for request response error messages are inconsistent. For example, the following code logs the error message as `INFO`:

https://github.com/keylime/keylime/blob/3ab55312006e54c32cb4ccb58b577c43ae0dd459/keylime/keylime_agent.py#L98

While the following logs the error message as `WARNING`:

https://github.com/keylime/keylime/blob/3ab55312006e54c32cb4ccb58b577c43ae0dd459/keylime/keylime_agent.py#L130

## Expected behavior vs. actual behavior 
The log level for request response error messages is consistent throughout the code.

## Steps to reproduce problem
1. Inspect the code

# Relevant logs

N/A

**Comment by THS-on** [comment]
The python agent is removed, so this can be closed.
