### ISSUE TITLE
Required packaging module version is not sufficient

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#970]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Description 
requirements.txt states that packaging>=16.0 is [required](https://github.com/keylime/keylime/blob/master/requirements.txt#L14)
however in [api_version.py](https://github.com/keylime/keylime/blob/master/keylime/api_version.py) we are using `minor` and `major` attributes that are available only since v20.

## Expected behavior vs. actual behavior 
We should either require respective packaging version (which may not be available for some distributions, such as CentOS Stream 8) or workaround it it keylime code.

## Steps to reproduce problem
1. run test_api_version.py on CentOS Stream 8 system.

**Comment by kkaarreell** [comment]
The code introducing the feature to packaging module is in
https://github.com/pypa/packaging/pull/225/

**Comment by THS-on** [comment]
Fixed in #971.
